Run: 3
/cm/local/apps/slurm/var/spool/job969653/slurm_script: line 26: 
pip install -e tpot2
pip install -r tpot2/ImputerExperiments/requirements_.txt
: No such file or directory
RunStart
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
starting loops
../data/r/218/218.pkl
working on 
../data/r/218/reg_full_MCAR_0.3_1
3.145791530609131
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2024-09-24 10:25:20,267] A new study created in memory with name: no-name-4857f208-8f8c-47d4-a4a4-e16f1effe34c
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
[I 2024-09-24 10:25:20,796] Trial 12 finished with value: 0.34647563013231475 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 12 with value: 0.34647563013231475.
running
[I 2024-09-24 10:25:21,089] Trial 15 finished with value: 0.34647563013231475 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 12 with value: 0.34647563013231475.
running
[I 2024-09-24 10:25:21,320] Trial 16 finished with value: 0.15739396523957588 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 16 with value: 0.15739396523957588.
running
[I 2024-09-24 10:25:21,542] Trial 5 finished with value: 0.34647563013231475 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 16 with value: 0.15739396523957588.
running
[I 2024-09-24 10:25:21,677] Trial 3 finished with value: 0.34647563013231475 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 16 with value: 0.15739396523957588.
running
[I 2024-09-24 10:25:21,877] Trial 17 finished with value: 0.34647563013231475 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 16 with value: 0.15739396523957588.
running
[I 2024-09-24 10:25:22,024] Trial 20 finished with value: 0.15739396523957588 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 16 with value: 0.15739396523957588.
running
[I 2024-09-24 10:25:29,373] Trial 18 finished with value: 0.34243816247614406 and parameters: {'model_name': 'GAIN', 'batch_size': 198, 'hint_rate': 0.6790765458042042, 'alpha': 34, 'iterations': 1, 'learning_rate': 0.000464798412586125, 'p_miss': 0.0572817611338175}. Best is trial 16 with value: 0.15739396523957588.
running
[I 2024-09-24 10:25:29,676] Trial 0 finished with value: 0.3378706401812293 and parameters: {'model_name': 'GAIN', 'batch_size': 493, 'hint_rate': 0.6204202250589933, 'alpha': 82, 'iterations': 1, 'learning_rate': 0.0016903581445283243, 'p_miss': 0.26329323720727504}. Best is trial 16 with value: 0.15739396523957588.
running
[I 2024-09-24 10:25:31,951] Trial 23 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.18376440473132663, 'alpha': 11, 'iterations': 1, 'learning_rate': 0.00036692787123503005, 'p_miss': 0.2354692897277851}. Best is trial 16 with value: 0.15739396523957588.
running
[I 2024-09-24 10:25:32,149] Trial 1 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 2, 'hint_rate': 0.7033781280358223, 'alpha': 47, 'iterations': 4, 'learning_rate': 0.01769120533824717, 'p_miss': 0.22231972199736882}. Best is trial 16 with value: 0.15739396523957588.
running
[I 2024-09-24 10:25:33,781] Trial 6 finished with value: 0.15701886782364372 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 5, 'imputation_order': 'descending'}. Best is trial 6 with value: 0.15701886782364372.
running
[I 2024-09-24 10:25:35,558] Trial 19 finished with value: 0.24522507507816008 and parameters: {'model_name': 'VAE', 'batch_size': 115, 'iterations': 3, 'learning_rate': 0.015882323284083177, 'p_miss': 0.0943690621002204}. Best is trial 6 with value: 0.15701886782364372.
running
[I 2024-09-24 10:25:36,273] Trial 8 finished with value: 0.15687789388834053 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 8456, 'weights': 'uniform'}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:25:38,111] Trial 13 finished with value: 0.17255988465256977 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5033, 'weights': 'distance'}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:25:39,172] Trial 11 finished with value: 0.17239873095615982 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 6066, 'weights': 'distance'}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:25:42,877] Trial 22 finished with value: 0.17205158664189138 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 9049, 'weights': 'distance'}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:25:53,060] Trial 24 finished with value: 0.17190845357947357 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 10906, 'weights': 'distance'}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:25:53,595] Trial 29 finished with value: 0.15688477327925313 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 8762, 'weights': 'uniform'}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:25:57,045] Trial 27 finished with value: 0.15701886782364372 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 5, 'imputation_order': 'descending'}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:25:58,557] Trial 28 finished with value: 0.15701886782364372 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 5, 'imputation_order': 'descending'}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:26:01,310] Trial 30 finished with value: 0.15701886782364372 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 5, 'imputation_order': 'descending'}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:26:03,251] Trial 31 finished with value: 0.15701886782364372 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 5, 'imputation_order': 'descending'}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:26:07,500] Trial 26 finished with value: 0.1569185816662174 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 7, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:26:09,001] Trial 32 finished with value: 0.15701886782364372 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 5, 'imputation_order': 'descending'}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:26:09,401] Trial 34 finished with value: 0.15739396523957588 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 17402, 'weights': 'uniform'}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:26:12,618] Trial 35 finished with value: 0.15739396523957588 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 17165, 'weights': 'uniform'}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:26:13,977] Trial 21 finished with value: 0.2553572317782681 and parameters: {'model_name': 'VAE', 'batch_size': 281, 'iterations': 13, 'learning_rate': 0.0029679205070244274, 'p_miss': 0.04752311614736686}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:26:17,584] Trial 37 finished with value: 0.15739396523957588 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 17440, 'weights': 'uniform'}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:26:19,110] Trial 38 finished with value: 0.15739396523957588 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 17173, 'weights': 'uniform'}. Best is trial 8 with value: 0.15687789388834053.
running
[I 2024-09-24 10:26:21,726] Trial 41 finished with value: 0.15491447864664804 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 335, 'weights': 'uniform'}. Best is trial 41 with value: 0.15491447864664804.
running
[I 2024-09-24 10:26:23,265] Trial 39 finished with value: 0.15739396523957588 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 16914, 'weights': 'uniform'}. Best is trial 41 with value: 0.15491447864664804.
running
[I 2024-09-24 10:26:23,554] Trial 40 finished with value: 0.15739396523957588 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 16669, 'weights': 'uniform'}. Best is trial 41 with value: 0.15491447864664804.
running
[I 2024-09-24 10:26:23,791] Trial 33 finished with value: 0.15701886782364372 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 5, 'imputation_order': 'descending'}. Best is trial 41 with value: 0.15491447864664804.
running
[I 2024-09-24 10:26:29,119] Trial 44 finished with value: 0.1547973107915775 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 443, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:26:30,118] Trial 43 finished with value: 0.15696403126811614 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 11067, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:26:31,175] Trial 46 finished with value: 0.15653729701386604 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 81, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:26:33,283] Trial 47 finished with value: 0.155001868276613 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 525, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:26:37,452] Trial 50 finished with value: 0.15671958823812615 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 75, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:26:39,670] Trial 52 finished with value: 0.1616624920396191 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 19, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:26:40,201] Trial 51 finished with value: 0.15518701701609378 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 687, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:26:49,763] Trial 56 finished with value: 0.1566995125381941 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2347, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:30:43,168] Trial 10 finished with value: 0.342723250212689 and parameters: {'model_name': 'GAIN', 'batch_size': 35, 'hint_rate': 0.3519592930637751, 'alpha': 18, 'iterations': 277, 'learning_rate': 0.002029285342589075, 'p_miss': 0.0544017708637739}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:33:37,432] Trial 14 finished with value: 0.17347651772692935 and parameters: {'model_name': 'VAE', 'batch_size': 16, 'iterations': 195, 'learning_rate': 0.027186235235781293, 'p_miss': 0.24634481502208516}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:33:46,119] Trial 59 finished with value: 0.1566961745475262 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2261, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:33:54,972] Trial 60 finished with value: 0.1566927852227852 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2323, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:34:03,331] Trial 61 finished with value: 0.15588218511957536 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1151, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:37:16,086] Trial 7 finished with value: 0.2550821100953964 and parameters: {'model_name': 'VAE', 'batch_size': 148, 'iterations': 232, 'learning_rate': 0.00025871954980828985, 'p_miss': 0.06913016447982462}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:38:25,686] Trial 4 finished with value: 0.1722952416042545 and parameters: {'model_name': 'VAE', 'batch_size': 6, 'iterations': 283, 'learning_rate': 0.05259169098456089, 'p_miss': 0.012543880143961097}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:38:34,078] Trial 64 finished with value: 0.15632380335988186 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1641, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:47:22,433] Trial 62 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 5, 'hint_rate': 0.9878276027977253, 'alpha': 99, 'iterations': 2940, 'learning_rate': 0.06277588097788367, 'p_miss': 0.15557602033901985}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:47:31,127] Trial 66 finished with value: 0.1563445485518437 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1665, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:47:40,288] Trial 67 finished with value: 0.15673636074420919 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3891, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:47:48,613] Trial 68 finished with value: 0.15609614556493495 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1380, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:47:56,908] Trial 69 finished with value: 0.15585852675503367 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1126, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:50:50,227] Trial 36 finished with value: 0.17571586053453372 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 1, 'imputation_order': 'ascending'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:59:03,439] Trial 65 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 4, 'hint_rate': 0.9383415530376373, 'alpha': 98, 'iterations': 4705, 'learning_rate': 0.00010247859690110397, 'p_miss': 0.16051009550857834}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 10:59:12,084] Trial 72 finished with value: 0.15677113550798683 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3332, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 11:02:59,156] Trial 73 finished with value: 0.1659759842942741 and parameters: {'model_name': 'VAE', 'batch_size': 963, 'iterations': 28, 'learning_rate': 0.00798522924154722, 'p_miss': 0.2917708345023863}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 11:03:07,060] Trial 74 finished with value: 0.15580827849278633 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1100, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 11:03:15,564] Trial 75 finished with value: 0.15677538149864825 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3313, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 11:03:23,614] Trial 76 finished with value: 0.15547428804656327 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 886, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 11:03:31,411] Trial 77 finished with value: 0.15530473510339066 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 796, 'weights': 'uniform'}. Best is trial 44 with value: 0.1547973107915775.
running
[I 2024-09-24 11:03:32,201] Trial 78 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:33,002] Trial 79 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:33,747] Trial 80 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:34,605] Trial 81 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:35,299] Trial 82 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:36,075] Trial 83 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:37,021] Trial 84 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:37,827] Trial 85 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:38,595] Trial 86 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:39,472] Trial 87 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:40,271] Trial 88 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:40,965] Trial 89 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:41,928] Trial 90 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:42,645] Trial 91 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:43,440] Trial 92 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:44,149] Trial 93 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:44,859] Trial 94 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:45,586] Trial 95 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:46,428] Trial 96 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:47,228] Trial 97 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:48,019] Trial 98 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:48,751] Trial 99 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:49,465] Trial 100 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:50,107] Trial 101 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:50,942] Trial 102 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:51,666] Trial 103 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:52,422] Trial 104 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:53,213] Trial 105 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:54,122] Trial 106 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:54,927] Trial 107 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:55,729] Trial 108 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:56,565] Trial 109 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:57,254] Trial 110 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:03:57,758] Trial 111 finished with value: 0.34647563013231475 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:07:53,853] Trial 2 finished with value: 0.17476538787125392 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 3, 'imputation_order': 'arabic'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:07:55,087] Trial 113 finished with value: 0.34647563013231475 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:07:56,009] Trial 114 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:15:34,034] Trial 9 finished with value: 0.3459373282441918 and parameters: {'model_name': 'GAIN', 'batch_size': 573, 'hint_rate': 0.6681815408084235, 'alpha': 74, 'iterations': 2020, 'learning_rate': 0.09718093498175137, 'p_miss': 0.11174757164387988}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:15:34,935] Trial 116 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:15:35,701] Trial 117 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:39:12,703] Trial 54 finished with value: 0.3302100099546793 and parameters: {'model_name': 'GAIN', 'batch_size': 12, 'hint_rate': 0.977017635567563, 'alpha': 96, 'iterations': 3177, 'learning_rate': 0.09073710630845427, 'p_miss': 0.16242122996589273}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:39:13,344] Trial 119 finished with value: 0.15739396523957588 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 11:58:53,579] Trial 63 finished with value: 0.3313957999553879 and parameters: {'model_name': 'GAIN', 'batch_size': 7, 'hint_rate': 0.08711379509995237, 'alpha': 96, 'iterations': 3532, 'learning_rate': 0.08700273716873069, 'p_miss': 0.15782276468027454}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:08:29,628] Trial 112 finished with value: 0.16905075762129815 and parameters: {'model_name': 'VAE', 'batch_size': 39, 'iterations': 1322, 'learning_rate': 0.0008344483850732356, 'p_miss': 0.1941368355127756}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:08:30,459] Trial 122 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:08:30,910] Trial 123 finished with value: 0.34647563013231475 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:08:31,882] Trial 124 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:08:33,136] Trial 125 finished with value: 0.34647563013231475 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:08:33,936] Trial 126 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:08:34,765] Trial 127 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:08:35,645] Trial 128 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:08:36,541] Trial 129 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:08:37,311] Trial 130 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:08:37,799] Trial 131 finished with value: 0.15739396523957588 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:08:38,625] Trial 132 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:08:39,338] Trial 133 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:17:24,108] Trial 118 finished with value: 0.17086124853858545 and parameters: {'model_name': 'VAE', 'batch_size': 38, 'iterations': 1292, 'learning_rate': 0.0008445872627604916, 'p_miss': 0.17302870521001884}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:17:24,785] Trial 135 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:17:25,489] Trial 136 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:17:26,411] Trial 137 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:17:27,383] Trial 138 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:17:28,312] Trial 139 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:17:29,307] Trial 140 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:17:30,199] Trial 141 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:17:30,919] Trial 142 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:18:06,694] Trial 143 finished with value: 0.17211408616325857 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'median', 'n_nearest_features': 8, 'imputation_order': 'random'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:18:07,455] Trial 144 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:18:08,189] Trial 145 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:18:08,883] Trial 146 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:18:09,647] Trial 147 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:18:10,421] Trial 148 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:18:11,204] Trial 149 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:18:26,652] Trial 150 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.39139906596752894, 'alpha': 60, 'iterations': 60, 'learning_rate': 0.0057311653188063805, 'p_miss': 0.12157615137583626}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:18:27,113] Trial 151 finished with value: 0.34647563013231475 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:18:28,105] Trial 152 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:18:29,491] Trial 153 finished with value: 0.34647563013231475 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:18:59,411] Trial 154 finished with value: 0.299623211879097 and parameters: {'model_name': 'VAE', 'batch_size': 78, 'iterations': 9, 'learning_rate': 0.00012669405750409063, 'p_miss': 0.016147849070012432}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:00,150] Trial 155 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:00,946] Trial 156 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:01,685] Trial 157 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:02,437] Trial 158 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:03,212] Trial 159 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:04,209] Trial 160 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:04,883] Trial 161 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:05,715] Trial 162 finished with value: 0.15739396523957588 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:06,515] Trial 163 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:35,975] Trial 164 finished with value: 0.1695008032764982 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'median', 'n_nearest_features': 1, 'imputation_order': 'roman'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:37,087] Trial 165 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:38,121] Trial 166 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:39,178] Trial 167 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:40,301] Trial 168 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:41,303] Trial 169 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:42,436] Trial 170 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:43,389] Trial 171 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:44,036] Trial 172 finished with value: 0.34647563013231475 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:19:45,130] Trial 173 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:21:42,813] Trial 174 finished with value: 0.32167589682325176 and parameters: {'model_name': 'GAIN', 'batch_size': 2, 'hint_rate': 0.2808107915126531, 'alpha': 3, 'iterations': 74, 'learning_rate': 0.007281669116379517, 'p_miss': 0.28627950882952713}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:21:44,042] Trial 175 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:21:45,112] Trial 176 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:21:46,251] Trial 177 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:21:47,452] Trial 178 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:21:48,848] Trial 179 finished with value: 0.34647563013231475 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:21:49,700] Trial 180 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:21:50,610] Trial 181 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:21:51,624] Trial 182 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:33:43,446] Trial 120 finished with value: 0.16913333202191166 and parameters: {'model_name': 'VAE', 'batch_size': 49, 'iterations': 1130, 'learning_rate': 0.000984264743753669, 'p_miss': 0.18894840548527822}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:33:44,385] Trial 184 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:33:44,918] Trial 185 finished with value: 0.15739396523957588 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:33:45,913] Trial 186 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:33:46,710] Trial 187 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:33:47,541] Trial 188 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:33:48,364] Trial 189 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:33:49,240] Trial 190 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:33:50,236] Trial 191 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:33:51,103] Trial 192 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:33:51,965] Trial 193 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:34:29,087] Trial 194 finished with value: 0.24473987739469355 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 3, 'imputation_order': 'ascending', 'sample_posterior': True}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:34:29,913] Trial 195 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:34:30,642] Trial 196 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:34:31,593] Trial 197 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:34:32,521] Trial 198 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
running
[I 2024-09-24 12:34:33,310] Trial 199 finished with value: 0.14217079840079333 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 78 with value: 0.14217079840079333.
[I 2024-09-24 12:49:11,567] Trial 121 finished with value: 0.1674036683612365 and parameters: {'model_name': 'VAE', 'batch_size': 45, 'iterations': 882, 'learning_rate': 0.0009249433367793026, 'p_miss': 0.20090065958040731}. Best is trial 78 with value: 0.14217079840079333.
[I 2024-09-24 12:56:45,127] Trial 183 finished with value: 0.1682552459191014 and parameters: {'model_name': 'VAE', 'batch_size': 66, 'iterations': 687, 'learning_rate': 0.02758351921270218, 'p_miss': 0.19993844608897465}. Best is trial 78 with value: 0.14217079840079333.
[I 2024-09-24 13:30:33,884] Trial 45 finished with value: 0.16738018756717735 and parameters: {'model_name': 'VAE', 'batch_size': 13, 'iterations': 3553, 'learning_rate': 0.09127983540613324, 'p_miss': 0.1360931653693408}. Best is trial 78 with value: 0.14217079840079333.
[I 2024-09-24 14:18:30,317] Trial 58 finished with value: 0.1708384534983993 and parameters: {'model_name': 'VAE', 'batch_size': 6, 'iterations': 5169, 'learning_rate': 0.07060001398954892, 'p_miss': 0.15681307649382772}. Best is trial 78 with value: 0.14217079840079333.
[I 2024-09-24 14:28:27,477] Trial 70 finished with value: 0.16718564660174487 and parameters: {'model_name': 'VAE', 'batch_size': 48, 'iterations': 6110, 'learning_rate': 0.00011276890790605, 'p_miss': 0.16885279250988658}. Best is trial 78 with value: 0.14217079840079333.
[I 2024-09-24 14:50:54,554] Trial 55 finished with value: 0.1690954804626676 and parameters: {'model_name': 'VAE', 'batch_size': 12, 'iterations': 5378, 'learning_rate': 0.09449647984437261, 'p_miss': 0.1613088202883343}. Best is trial 78 with value: 0.14217079840079333.
[I 2024-09-24 15:45:03,543] Trial 53 finished with value: 0.17461588571878842 and parameters: {'model_name': 'VAE', 'batch_size': 9, 'iterations': 6738, 'learning_rate': 0.032314632068239355, 'p_miss': 0.16438006060514535}. Best is trial 78 with value: 0.14217079840079333.
[I 2024-09-24 15:56:06,709] Trial 42 finished with value: 0.17070038633367074 and parameters: {'model_name': 'VAE', 'batch_size': 9, 'iterations': 8661, 'learning_rate': 0.07937216174843328, 'p_miss': 0.011923151087999212}. Best is trial 78 with value: 0.14217079840079333.
[I 2024-09-24 16:09:46,095] Trial 25 finished with value: 0.20521583139693073 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 9493, 'learning_rate': 0.09334960694599435, 'p_miss': 0.010681215063388538}. Best is trial 78 with value: 0.14217079840079333.
[I 2024-09-24 16:12:05,085] Trial 115 finished with value: 0.17064683499728933 and parameters: {'model_name': 'VAE', 'batch_size': 37, 'iterations': 9644, 'learning_rate': 0.000883642030541086, 'p_miss': 0.1164876122076226}. Best is trial 78 with value: 0.14217079840079333.
[I 2024-09-24 16:15:47,271] Trial 134 finished with value: 0.21804509288270535 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 9367, 'learning_rate': 0.00647519493071404, 'p_miss': 0.11850269606791874}. Best is trial 78 with value: 0.14217079840079333.
[I 2024-09-24 16:15:58,081] Trial 57 finished with value: 0.17361255678065662 and parameters: {'model_name': 'VAE', 'batch_size': 11, 'iterations': 8518, 'learning_rate': 0.07941023929127689, 'p_miss': 0.15717149254318438}. Best is trial 78 with value: 0.14217079840079333.
[I 2024-09-24 16:18:18,757] Trial 48 finished with value: 0.17195119232874498 and parameters: {'model_name': 'VAE', 'batch_size': 10, 'iterations': 8877, 'learning_rate': 0.09840634596382077, 'p_miss': 0.15513058502258428}. Best is trial 78 with value: 0.14217079840079333.
[I 2024-09-24 16:19:21,921] Trial 49 finished with value: 0.16806675730341675 and parameters: {'model_name': 'VAE', 'batch_size': 13, 'iterations': 9675, 'learning_rate': 0.0984253764887905, 'p_miss': 0.14998139030222665}. Best is trial 78 with value: 0.14217079840079333.
[I 2024-09-24 16:24:35,759] Trial 71 finished with value: 0.1658608785575741 and parameters: {'model_name': 'VAE', 'batch_size': 909, 'iterations': 9989, 'learning_rate': 0.00010468527879581969, 'p_miss': 0.2961470086343146}. Best is trial 78 with value: 0.14217079840079333.
fit
auto fit
auto transform
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64
0.14217079840079333
{'model_name': 'SimpleImputer', 'strategy': 'median'}
running experiment 2/3 - Does reconstruction give good automl predictions
Start est fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746acd00> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4b20> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4310> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  1
Best root_mean_squared_error score: -36944.42167152001
Generation:   4%|▍         | 1/25 [01:06<26:29, 66.22s/it]Generation:  2
Best root_mean_squared_error score: -36586.745688020295
Generation:   8%|▊         | 2/25 [02:10<24:57, 65.13s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547472a9b0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554747096c0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547470ab60> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  3
Best root_mean_squared_error score: -36298.92606201643
Generation:  12%|█▏        | 3/25 [02:37<17:33, 47.91s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474732f80> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746ee9e0> 

Generation:  4
Best root_mean_squared_error score: -36160.26312884392
Generation:  16%|█▌        | 4/25 [12:42<1:33:37, 267.50s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547470a230> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  5
Best root_mean_squared_error score: -36160.26312884392
Generation:  20%|██        | 5/25 [22:06<2:04:51, 374.56s/it]Generation:  6
Best root_mean_squared_error score: -36160.26312884392
Generation:  24%|██▍       | 6/25 [22:40<1:21:53, 258.61s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f01a80> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a7bb0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  7
Best root_mean_squared_error score: -36160.26312884392
Generation:  28%|██▊       | 7/25 [23:20<56:08, 187.13s/it]  WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f00550> 

Generation:  8
Best root_mean_squared_error score: -36160.26312884392
Generation:  32%|███▏      | 8/25 [33:37<1:31:51, 324.20s/it]Generation:  9
Best root_mean_squared_error score: -36153.755804805594
Generation:  36%|███▌      | 9/25 [34:17<1:02:46, 235.42s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547470bfd0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  10
Best root_mean_squared_error score: -36153.755804805594
Generation:  40%|████      | 10/25 [35:23<45:47, 183.13s/it] WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467a84d00> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467bd7a00> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  11
Best root_mean_squared_error score: -36153.755804805594
Generation:  44%|████▍     | 11/25 [35:54<31:50, 136.47s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746ecd00> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546533ab90> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  12
Best root_mean_squared_error score: -36153.755804805594
Generation:  48%|████▊     | 12/25 [36:40<23:34, 108.84s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a6ad0> 

Generation:  13
Best root_mean_squared_error score: -36153.755804805594
Generation:  52%|█████▏    | 13/25 [46:52<52:17, 261.45s/it]Generation:  14
Best root_mean_squared_error score: -36153.755804805594
Generation:  56%|█████▌    | 14/25 [47:17<34:50, 190.03s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554659e8dc0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  15
Best root_mean_squared_error score: -36153.755804805594
Generation:  60%|██████    | 15/25 [47:48<23:40, 142.01s/it]Generation:  16
Best root_mean_squared_error score: -36153.755804805594
Generation:  64%|██████▍   | 16/25 [48:10<15:51, 105.77s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547472a050> 

Generation:  17
Best root_mean_squared_error score: -36153.755804805594
Generation:  68%|██████▊   | 17/25 [58:18<34:14, 256.76s/it]Generation:  18
Best root_mean_squared_error score: -36144.09017062705
Generation:  72%|███████▏  | 18/25 [58:35<21:33, 184.81s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546548c4c0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467bd9420> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  19
Best root_mean_squared_error score: -36114.39129982969
Generation:  76%|███████▌  | 19/25 [58:44<13:12, 132.14s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554656e52a0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  20
Best root_mean_squared_error score: -36114.39129982969
Generation:  80%|████████  | 20/25 [1:07:03<20:11, 242.22s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746ee6e0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546565c940> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  21
Best root_mean_squared_error score: -36068.47186616182
Generation:  84%|████████▍ | 21/25 [1:07:36<11:57, 179.45s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554654d2740> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554676e1480> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  22
Best root_mean_squared_error score: -36068.47186616182
Generation:  88%|████████▊ | 22/25 [1:08:10<06:47, 135.83s/it]Generation:  23
Best root_mean_squared_error score: -36068.47186616182
Generation:  92%|█████████▏| 23/25 [1:08:22<03:17, 98.69s/it] Generation:  24
Best root_mean_squared_error score: -36068.47186616182
Generation:  96%|█████████▌| 24/25 [1:08:48<01:16, 76.78s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554653b9de0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  25
Best root_mean_squared_error score: -36053.04642425112
Generation: 100%|██████████| 25/25 [1:09:10<00:00, 60.30s/it]Generation: 100%|██████████| 25/25 [1:09:13<00:00, 166.12s/it]
2024-09-24 17:33:59,387 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:37093' caused the cluster to lose scattered data, which can't be recovered: {'ndarray-fd28d5dd8046ec9d68a5e8f9d79ff3f2', 'DataFrame-4849a007d34cf0419f2cfa91df79b9dd'} (stimulus_id='handle-worker-cleanup-1727224439.387823')
Fitted
Pipeline(steps=[('lgbmregressor',
                 LGBMRegressor(max_depth=8, n_estimators=66, n_jobs=1,
                               num_leaves=22, verbose=-1))])
score start
train score: {'explained_var': 0.6371947274750452, 'r2': 0.6371947274750451, 'rmse': 31825.39938939645}
original test score: {'explained_var': 0.6536641743214948, 'r2': 0.6536541620354193, 'rmse': 31110.553550806366}
imputed test score: {'explained_var': 0.548121495806611, 'r2': 0.5479192135141878, 'rmse': 35543.54796125179}
score end
check intended
EXP2 Finished
running experiment 3/3 - What is the best automl settings?
<tpot2.search_spaces.pipelines.sequential.SequentialPipeline object at 0x155434fd2fb0>
Start tpot fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a42b0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a5390> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f22f20> 

Generation:  1
Best root_mean_squared_error score: -37540.65895371289
Generation:   4%|▍         | 1/25 [10:03<4:01:22, 603.45s/it]Generation:  2
Best root_mean_squared_error score: -36615.86462178983
Generation:   8%|▊         | 2/25 [12:18<2:05:42, 327.92s/it]Generation:  3
Best root_mean_squared_error score: -36538.49128107344
Generation:  12%|█▏        | 3/25 [14:06<1:23:22, 227.38s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465aaff10> 

Generation:  4
Best root_mean_squared_error score: -36436.213509935114
Generation:  16%|█▌        | 4/25 [24:09<2:11:34, 375.91s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f0a500> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554653910c0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  5
Best root_mean_squared_error score: -36259.62276403364
Generation:  20%|██        | 5/25 [25:52<1:32:26, 277.33s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f396c0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746af190> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  6
Best root_mean_squared_error score: -36259.62276403364
Generation:  24%|██▍       | 6/25 [28:06<1:12:27, 228.79s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554747117e0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554678fd300> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  7
Best root_mean_squared_error score: -36249.169286238655
Generation:  28%|██▊       | 7/25 [29:55<56:49, 189.43s/it]  Generation:  8
Best root_mean_squared_error score: -36228.971389548366
Generation:  32%|███▏      | 8/25 [32:22<49:49, 175.84s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554548b5330> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155452375450> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  9
Best root_mean_squared_error score: -36228.971389548366
Generation:  36%|███▌      | 9/25 [34:04<40:46, 152.88s/it]Generation:  10
Best root_mean_squared_error score: -36228.971389548366
Generation:  40%|████      | 10/25 [38:17<45:58, 183.89s/it]Generation:  11
Best root_mean_squared_error score: -36225.462463285585
Generation:  44%|████▍     | 11/25 [39:53<36:38, 157.02s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f05e70> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464f299f0> 

Generation:  12
Best root_mean_squared_error score: -36225.462463285585
Generation:  48%|████▊     | 12/25 [49:58<1:03:32, 293.29s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467b39600> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  13
Best root_mean_squared_error score: -36225.462463285585
Generation:  52%|█████▏    | 13/25 [50:38<43:19, 216.58s/it]  Generation:  14
Best root_mean_squared_error score: -36186.58130179483
Generation:  56%|█████▌    | 14/25 [52:23<33:28, 182.61s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467e7d810> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  15
Best root_mean_squared_error score: -36178.49477658907
Generation:  60%|██████    | 15/25 [53:57<26:00, 156.03s/it]Generation:  16
Best root_mean_squared_error score: -36178.49477658907
Generation:  64%|██████▍   | 16/25 [54:05<16:44, 111.57s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464dc1f30> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554648fb460> 

Generation:  17
Best root_mean_squared_error score: -36178.49477658907
Generation:  68%|██████▊   | 17/25 [1:04:10<34:39, 259.99s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465343d00> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464d6dd50> 

Generation:  18
Best root_mean_squared_error score: -36178.49477658907
Generation:  72%|███████▏  | 18/25 [1:14:15<42:25, 363.59s/it]Generation:  19
Best root_mean_squared_error score: -36178.49477658907
Generation:  76%|███████▌  | 19/25 [1:15:19<27:20, 273.45s/it]Generation:  20
Best root_mean_squared_error score: -36178.49477658907
Generation:  80%|████████  | 20/25 [1:16:52<18:16, 219.36s/it]Generation:  21
Best root_mean_squared_error score: -36178.49477658907
Generation:  84%|████████▍ | 21/25 [1:21:35<15:54, 238.60s/it]Generation:  22
Best root_mean_squared_error score: -36178.49477658907
Generation:  88%|████████▊ | 22/25 [1:21:49<08:33, 171.21s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467a8a620> 

Generation:  23
Best root_mean_squared_error score: -36116.670184986826
Generation:  92%|█████████▏| 23/25 [1:31:56<10:03, 301.74s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467e6d1e0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  24
Best root_mean_squared_error score: -36116.670184986826
Generation:  96%|█████████▌| 24/25 [1:32:32<03:42, 222.23s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464e7ea40> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  25
Best root_mean_squared_error score: -36116.670184986826
Generation: 100%|██████████| 25/25 [1:33:57<00:00, 180.91s/it]Generation: 100%|██████████| 25/25 [1:33:57<00:00, 225.50s/it]
2024-09-24 19:08:12,467 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:37335' caused the cluster to lose scattered data, which can't be recovered: {'DataFrame-85163266695b78d58c83e4a298b972b5', 'DataFrame-4849a007d34cf0419f2cfa91df79b9dd'} (stimulus_id='handle-worker-cleanup-1727230092.4673984')
Fitted
Pipeline(steps=[('simpleimputer', SimpleImputer()),
                ('histgradientboostingregressor',
                 HistGradientBoostingRegressor(early_stopping=False,
                                               l2_regularization=0.0004691275209,
                                               learning_rate=0.0281225041758,
                                               max_features=0.4616996692145,
                                               max_leaf_nodes=187,
                                               min_samples_leaf=38,
                                               tol=0.0001))])
transform worked
try transform
transform worked
score start
train score: {'explained_var': 0.655084390574227, 'r2': 0.6550843905740948, 'rmse': 31030.837148746745}
test score: {'explained_var': 0.5372745897670208, 'r2': 0.5371934759414422, 'rmse': 35962.71640549432}
original test score: {'explained_var': 0.6450312669922775, 'r2': 0.6448626958268662, 'rmse': 31502.926422740507}
score end
218
lvl
0.3
type
MCAR
num_run
1
reg_full
finished
all finished
full run takes
8.71658096253872
hours
DONE
