Run: 30
/cm/local/apps/slurm/var/spool/job970625/slurm_script: line 26: 
pip install -e tpot2
pip install -r tpot2/ImputerExperiments/requirements_.txt
: No such file or directory
RunStart
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
starting loops
../data/r/218/218.pkl
working on 
../data/r/218/reg_full_MAR_0.1_2
0.43213891983032227
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2024-09-25 09:36:16,285] A new study created in memory with name: no-name-40c2150e-9c80-424e-971f-e2dd8000cb98
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
[I 2024-09-25 09:36:16,584] Trial 11 finished with value: 0.10575061406768378 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 11 with value: 0.10575061406768378.
running
[I 2024-09-25 09:36:16,799] Trial 14 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:36:17,070] Trial 15 finished with value: 0.4244507302044508 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:36:17,215] Trial 5 finished with value: 0.4244507302044508 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:36:23,103] Trial 1 finished with value: 0.10673204822100553 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 6597, 'weights': 'uniform'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:36:23,226] Trial 16 finished with value: 0.10575061406768378 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 15893, 'weights': 'uniform'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:36:23,376] Trial 20 finished with value: 0.42445074218911405 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:36:23,534] Trial 3 finished with value: 0.10691852128421823 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5020, 'weights': 'uniform'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:36:23,654] Trial 17 finished with value: 0.10575061406768378 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 17686, 'weights': 'uniform'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:36:26,657] Trial 24 finished with value: 0.10964997090656652 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'constant', 'n_nearest_features': 5, 'imputation_order': 'roman'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:36:26,784] Trial 9 finished with value: 0.19370831219260037 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 2, 'imputation_order': 'roman', 'sample_posterior': True}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:36:28,118] Trial 0 finished with value: 0.12268705113386964 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'constant', 'n_nearest_features': 4, 'imputation_order': 'ascending'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:36:28,487] Trial 23 finished with value: 0.10628848562498214 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 9514, 'weights': 'uniform'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:39:40,734] Trial 28 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 8, 'hint_rate': 0.48486255596127376, 'alpha': 32, 'iterations': 28, 'learning_rate': 0.0004513904286337352, 'p_miss': 0.018378438253446316}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:39:41,869] Trial 21 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.37270726274209587, 'alpha': 47, 'iterations': 29, 'learning_rate': 0.00044647259313955847, 'p_miss': 0.04030584737002019}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:39:43,155] Trial 7 finished with value: 0.40915182994842914 and parameters: {'model_name': 'GAIN', 'batch_size': 16, 'hint_rate': 0.4356210019559604, 'alpha': 24, 'iterations': 5, 'learning_rate': 0.013221344929346087, 'p_miss': 0.15707991336425875}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:39:48,966] Trial 10 finished with value: 0.35125913613990534 and parameters: {'model_name': 'VAE', 'batch_size': 570, 'iterations': 1, 'learning_rate': 0.0022320148794740175, 'p_miss': 0.24269554128511867}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:39:49,535] Trial 32 finished with value: 0.10575061406768378 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:39:50,217] Trial 33 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:39:51,484] Trial 26 finished with value: 0.3619742778116406 and parameters: {'model_name': 'VAE', 'batch_size': 410, 'iterations': 4, 'learning_rate': 0.00015999784053669086, 'p_miss': 0.15165913248770352}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:39:52,266] Trial 35 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:39:53,126] Trial 36 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:39:53,801] Trial 37 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:39:54,613] Trial 38 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:39:55,446] Trial 39 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:39:56,195] Trial 40 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:39:57,102] Trial 41 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:39:59,782] Trial 6 finished with value: 0.21924784987498488 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 7, 'learning_rate': 0.019473760175910255, 'p_miss': 0.10293701491772755}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:40:00,442] Trial 43 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:41:18,435] Trial 18 finished with value: 0.44519006343016454 and parameters: {'model_name': 'GAIN', 'batch_size': 493, 'hint_rate': 0.5675698308272261, 'alpha': 81, 'iterations': 66, 'learning_rate': 0.07950705103473352, 'p_miss': 0.18273919908329708}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:41:19,397] Trial 12 finished with value: 0.40294517335408153 and parameters: {'model_name': 'GAIN', 'batch_size': 287, 'hint_rate': 0.5242517494316101, 'alpha': 96, 'iterations': 70, 'learning_rate': 0.002084494542916104, 'p_miss': 0.23906079896353782}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:41:20,129] Trial 46 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:41:20,811] Trial 47 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:42:42,052] Trial 27 finished with value: 0.4725297983404288 and parameters: {'model_name': 'GAIN', 'batch_size': 940, 'hint_rate': 0.9569462691158113, 'alpha': 7, 'iterations': 121, 'learning_rate': 0.019248106328928996, 'p_miss': 0.21728517723392776}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:43:50,039] Trial 8 finished with value: 0.4055769529383264 and parameters: {'model_name': 'GAIN', 'batch_size': 611, 'hint_rate': 0.13924035117933442, 'alpha': 67, 'iterations': 176, 'learning_rate': 0.0010980296296582103, 'p_miss': 0.21216716813333295}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:43:59,960] Trial 4 finished with value: 0.16301969780209016 and parameters: {'model_name': 'VAE', 'batch_size': 41, 'iterations': 105, 'learning_rate': 0.0015024326825964246, 'p_miss': 0.17057501884245235}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:54:29,041] Trial 13 finished with value: 0.45043964393223257 and parameters: {'model_name': 'GAIN', 'batch_size': 224, 'hint_rate': 0.7700978667767845, 'alpha': 53, 'iterations': 758, 'learning_rate': 0.0448029229847689, 'p_miss': 0.25068793905304915}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 09:56:59,303] Trial 19 finished with value: 0.4365693020886573 and parameters: {'model_name': 'GAIN', 'batch_size': 318, 'hint_rate': 0.10118982073353662, 'alpha': 92, 'iterations': 853, 'learning_rate': 0.06971195810188273, 'p_miss': 0.14440642740075638}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:08:22,142] Trial 22 finished with value: 0.17126132869183402 and parameters: {'model_name': 'VAE', 'batch_size': 2, 'iterations': 776, 'learning_rate': 0.0002702614262903802, 'p_miss': 0.03970021093629485}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:09:39,966] Trial 25 finished with value: 0.13116858077783639 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 787, 'learning_rate': 0.07728831875479467, 'p_miss': 0.06236498011979749}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:11:23,730] Trial 34 finished with value: 0.11504785839249843 and parameters: {'model_name': 'VAE', 'batch_size': 869, 'iterations': 636, 'learning_rate': 0.09651591768388801, 'p_miss': 0.2830141872442975}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:11:24,166] Trial 56 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:11:24,739] Trial 57 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:32:38,775] Trial 2 finished with value: 0.11331571529160742 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 5, 'imputation_order': 'arabic'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:32:39,287] Trial 59 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:32:39,828] Trial 60 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:32:40,121] Trial 61 finished with value: 0.42445074218911405 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:32:40,631] Trial 62 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:32:41,156] Trial 63 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:32:46,130] Trial 64 finished with value: 0.10953634421581733 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 8, 'imputation_order': 'descending'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:32:46,562] Trial 65 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:32:46,970] Trial 66 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:32:47,383] Trial 67 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:32:47,885] Trial 68 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:53:22,960] Trial 44 finished with value: 0.10965924623633302 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 8, 'imputation_order': 'arabic'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:53:27,067] Trial 70 finished with value: 0.1042172326116875 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 100, 'weights': 'distance'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:53:27,504] Trial 71 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:53:27,911] Trial 72 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:53:28,274] Trial 73 finished with value: 0.10575061406768378 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:53:28,841] Trial 74 finished with value: 0.4244507302044508 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:53:35,359] Trial 75 finished with value: 0.10553675474209068 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 12512, 'weights': 'distance'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:53:35,805] Trial 76 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:53:36,265] Trial 77 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:53:36,753] Trial 78 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:53:37,045] Trial 79 finished with value: 0.42445074218911405 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:53:37,669] Trial 80 finished with value: 0.4244507302044508 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:53:47,022] Trial 81 finished with value: 0.1323701599187966 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'median', 'n_nearest_features': 1, 'imputation_order': 'random'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:53:47,435] Trial 82 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:53:47,848] Trial 83 finished with value: 0.10575061406768378 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:54:53,967] Trial 48 finished with value: 0.11070325551554465 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 8, 'imputation_order': 'arabic'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:54:54,565] Trial 85 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:54:55,184] Trial 86 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:54:55,652] Trial 87 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:55:02,400] Trial 45 finished with value: 0.10980031864378918 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 8, 'imputation_order': 'arabic'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:56:04,772] Trial 49 finished with value: 0.11040126213780052 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 8, 'imputation_order': 'descending'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:57:19,694] Trial 51 finished with value: 0.11006696323776628 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 8, 'imputation_order': 'random'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:57:25,322] Trial 50 finished with value: 0.11026317891509814 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 8, 'imputation_order': 'descending'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:57:32,192] Trial 92 finished with value: 0.3491069993763401 and parameters: {'model_name': 'VAE', 'batch_size': 91, 'iterations': 1, 'learning_rate': 0.0053493141840541426, 'p_miss': 0.10496635543035028}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:57:32,967] Trial 93 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:57:33,621] Trial 94 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:57:34,308] Trial 95 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:57:34,949] Trial 96 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:57:35,675] Trial 97 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 10:57:36,410] Trial 98 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 11:07:56,242] Trial 52 finished with value: 0.11106924489852239 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 8, 'imputation_order': 'arabic'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 11:10:32,387] Trial 53 finished with value: 0.11004494666925384 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 8, 'imputation_order': 'random'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 11:21:41,945] Trial 54 finished with value: 0.11013782627666133 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 8, 'imputation_order': 'arabic'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 11:23:21,357] Trial 55 finished with value: 0.1090518709031254 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 8, 'imputation_order': 'arabic'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 11:25:07,289] Trial 58 finished with value: 0.11098347214256969 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 8, 'imputation_order': 'descending'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 11:48:09,079] Trial 69 finished with value: 0.11065996142035588 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 8, 'imputation_order': 'random'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 11:48:14,248] Trial 105 finished with value: 0.10378887848485505 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 429, 'weights': 'distance'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 11:48:15,034] Trial 106 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 12:09:30,935] Trial 103 finished with value: 0.483359763126839 and parameters: {'model_name': 'GAIN', 'batch_size': 35, 'hint_rate': 0.9201584522002135, 'alpha': 0, 'iterations': 1987, 'learning_rate': 0.005469241525039409, 'p_miss': 0.29929077212227195}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 12:09:31,914] Trial 108 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 12:09:32,661] Trial 109 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 12:09:33,121] Trial 110 finished with value: 0.42445074218911405 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 12:09:33,936] Trial 111 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 12:24:40,091] Trial 99 finished with value: 0.43414245423422065 and parameters: {'model_name': 'GAIN', 'batch_size': 82, 'hint_rate': 0.9116295141600783, 'alpha': 0, 'iterations': 3865, 'learning_rate': 0.006300374814534406, 'p_miss': 0.10768728007755077}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:45:29,142] Trial 42 finished with value: 0.14889904955977623 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 6763, 'learning_rate': 0.09837153545401107, 'p_miss': 0.2827683206582301}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:45:29,861] Trial 114 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:45:30,598] Trial 115 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:45:31,457] Trial 116 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:45:32,306] Trial 117 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:45:33,032] Trial 118 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:45:33,807] Trial 119 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:45:35,090] Trial 120 finished with value: 0.4244507302044508 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:45:35,706] Trial 121 finished with value: 0.10575061406768378 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:22,004] Trial 122 finished with value: 0.35714247012255845 and parameters: {'model_name': 'VAE', 'batch_size': 8, 'iterations': 15, 'learning_rate': 0.00010008908227053783, 'p_miss': 0.07658015787027196}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:22,855] Trial 123 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:23,565] Trial 124 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:24,375] Trial 125 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:25,260] Trial 126 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:26,048] Trial 127 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:26,886] Trial 128 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:27,868] Trial 129 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:28,395] Trial 130 finished with value: 0.42445074218911405 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:35,920] Trial 131 finished with value: 0.10552137706783442 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 13158, 'weights': 'distance'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:36,729] Trial 132 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:37,510] Trial 133 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:38,267] Trial 134 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:38,883] Trial 135 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:39,760] Trial 136 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:40,399] Trial 137 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:41,672] Trial 138 finished with value: 0.4244507302044508 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:42,453] Trial 139 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:43,162] Trial 140 finished with value: 0.10575061406768378 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:46:54,723] Trial 141 finished with value: 0.411206922158694 and parameters: {'model_name': 'GAIN', 'batch_size': 128, 'hint_rate': 0.28369309066173504, 'alpha': 68, 'iterations': 2, 'learning_rate': 0.0009859888529875228, 'p_miss': 0.20545217367399293}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:50:03,902] Trial 100 finished with value: 0.4717859219829689 and parameters: {'model_name': 'GAIN', 'batch_size': 95, 'hint_rate': 0.7827398709775533, 'alpha': 2, 'iterations': 6897, 'learning_rate': 0.0061149950138947445, 'p_miss': 0.28503395662744224}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:50:04,737] Trial 143 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:50:05,457] Trial 144 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:50:06,148] Trial 145 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:50:06,860] Trial 146 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:50:07,640] Trial 147 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 13:50:50,207] Trial 107 finished with value: 0.4376062398628594 and parameters: {'model_name': 'GAIN', 'batch_size': 94, 'hint_rate': 0.9752270151656454, 'alpha': 9, 'iterations': 5086, 'learning_rate': 0.006791644868326338, 'p_miss': 0.08944214819829233}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:05,669] Trial 142 finished with value: 0.11492960414509423 and parameters: {'model_name': 'VAE', 'batch_size': 12, 'iterations': 266, 'learning_rate': 0.0341620321245329, 'p_miss': 0.0141464710225373}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:06,338] Trial 150 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:07,181] Trial 151 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:08,000] Trial 152 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:14,281] Trial 153 finished with value: 0.10599710172202728 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5180, 'weights': 'distance'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:15,082] Trial 154 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:15,483] Trial 155 finished with value: 0.42445074218911405 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:16,291] Trial 156 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:17,132] Trial 157 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:18,000] Trial 158 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:18,818] Trial 159 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:19,650] Trial 160 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:20,580] Trial 161 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:21,473] Trial 162 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:22,147] Trial 163 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:23,266] Trial 164 finished with value: 0.4244507302044508 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:23,968] Trial 165 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:24,716] Trial 166 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:25,382] Trial 167 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:26,322] Trial 168 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:26,913] Trial 169 finished with value: 0.10575061406768378 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:02:27,709] Trial 170 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:05:09,457] Trial 102 finished with value: 0.4840780654217694 and parameters: {'model_name': 'GAIN', 'batch_size': 10, 'hint_rate': 0.7959956220368682, 'alpha': 5, 'iterations': 7219, 'learning_rate': 0.005989188369960842, 'p_miss': 0.29843817463079114}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:06:47,571] Trial 148 finished with value: 0.12141758861923986 and parameters: {'model_name': 'VAE', 'batch_size': 8, 'iterations': 367, 'learning_rate': 0.033033186494040245, 'p_miss': 0.12814843371761497}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:06:48,299] Trial 173 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:06:49,016] Trial 174 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:06:49,674] Trial 175 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:06:50,619] Trial 176 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:06:51,567] Trial 177 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:06:52,332] Trial 178 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:06:53,053] Trial 179 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:06:53,879] Trial 180 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:06:54,622] Trial 181 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:07:00,898] Trial 182 finished with value: 0.10625823392964662 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 9656, 'weights': 'uniform'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:07:01,473] Trial 183 finished with value: 0.42445074218911405 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:07:02,265] Trial 184 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:07:03,029] Trial 185 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:07:03,833] Trial 186 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:07:04,756] Trial 187 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:07:05,410] Trial 188 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:07:06,229] Trial 189 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:07:06,977] Trial 190 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:07:07,842] Trial 191 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:07:08,792] Trial 192 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:07:10,198] Trial 193 finished with value: 0.4244507302044508 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:07:11,042] Trial 194 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:15:20,932] Trial 104 finished with value: 0.4662423148017571 and parameters: {'model_name': 'GAIN', 'batch_size': 105, 'hint_rate': 0.95959719635611, 'alpha': 9, 'iterations': 7107, 'learning_rate': 0.00010784909741867431, 'p_miss': 0.2983965034517657}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:15:21,863] Trial 196 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:15:22,658] Trial 197 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:15:23,445] Trial 198 finished with value: 0.10575061406768378 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 14 with value: 0.10089058114892657.
running
[I 2024-09-25 14:15:24,401] Trial 199 finished with value: 0.10089058114892657 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 14 with value: 0.10089058114892657.
[I 2024-09-25 14:28:52,337] Trial 101 finished with value: 0.4611779929401151 and parameters: {'model_name': 'GAIN', 'batch_size': 93, 'hint_rate': 0.9145304320315509, 'alpha': 2, 'iterations': 8277, 'learning_rate': 0.00010380614142164078, 'p_miss': 0.2833911725456822}. Best is trial 14 with value: 0.10089058114892657.
[I 2024-09-25 14:56:38,961] Trial 29 finished with value: 0.11503147189505562 and parameters: {'model_name': 'VAE', 'batch_size': 567, 'iterations': 6594, 'learning_rate': 0.08808566141622497, 'p_miss': 0.28419791490248447}. Best is trial 14 with value: 0.10089058114892657.
[I 2024-09-25 15:24:13,007] Trial 172 finished with value: 0.11618983435036853 and parameters: {'model_name': 'VAE', 'batch_size': 33, 'iterations': 2010, 'learning_rate': 0.011862423763468058, 'p_miss': 0.12603456225684173}. Best is trial 14 with value: 0.10089058114892657.
[I 2024-09-25 15:31:37,925] Trial 195 finished with value: 0.11494305687229449 and parameters: {'model_name': 'VAE', 'batch_size': 37, 'iterations': 1746, 'learning_rate': 0.0008812749554705123, 'p_miss': 0.18502505617378753}. Best is trial 14 with value: 0.10089058114892657.
[I 2024-09-25 15:37:50,853] Trial 149 finished with value: 0.11855853058001628 and parameters: {'model_name': 'VAE', 'batch_size': 13, 'iterations': 2333, 'learning_rate': 0.03067083149698022, 'p_miss': 0.12844944211538672}. Best is trial 14 with value: 0.10089058114892657.
[I 2024-09-25 15:45:06,345] Trial 171 finished with value: 0.11498247065317921 and parameters: {'model_name': 'VAE', 'batch_size': 35, 'iterations': 2464, 'learning_rate': 0.0006386193320887545, 'p_miss': 0.12251726620349554}. Best is trial 14 with value: 0.10089058114892657.
[I 2024-09-25 15:48:59,171] Trial 113 finished with value: 0.11737442013538427 and parameters: {'model_name': 'VAE', 'batch_size': 9, 'iterations': 4737, 'learning_rate': 0.0007780155878810796, 'p_miss': 0.12305990131861272}. Best is trial 14 with value: 0.10089058114892657.
[I 2024-09-25 15:59:30,025] Trial 30 finished with value: 0.11637694368948932 and parameters: {'model_name': 'VAE', 'batch_size': 582, 'iterations': 7635, 'learning_rate': 0.06620327591163391, 'p_miss': 0.2967340099503767}. Best is trial 14 with value: 0.10089058114892657.
[I 2024-09-25 16:00:11,510] Trial 88 finished with value: 0.11571245194129079 and parameters: {'model_name': 'VAE', 'batch_size': 92, 'iterations': 7653, 'learning_rate': 0.004477809041534881, 'p_miss': 0.10628600656251203}. Best is trial 14 with value: 0.10089058114892657.
[I 2024-09-25 16:08:13,003] Trial 84 finished with value: 0.11891473323822063 and parameters: {'model_name': 'VAE', 'batch_size': 53, 'iterations': 7228, 'learning_rate': 0.0060862589719096055, 'p_miss': 0.0933924000585504}. Best is trial 14 with value: 0.10089058114892657.
[I 2024-09-25 16:10:23,128] Trial 89 finished with value: 0.1163880517911668 and parameters: {'model_name': 'VAE', 'batch_size': 95, 'iterations': 8618, 'learning_rate': 0.006429276986044569, 'p_miss': 0.10450547249042838}. Best is trial 14 with value: 0.10089058114892657.
[I 2024-09-25 16:15:27,174] Trial 91 finished with value: 0.1158631458375535 and parameters: {'model_name': 'VAE', 'batch_size': 86, 'iterations': 9282, 'learning_rate': 0.006836637604233931, 'p_miss': 0.10408717390675289}. Best is trial 14 with value: 0.10089058114892657.
[I 2024-09-25 16:16:17,578] Trial 31 finished with value: 0.11519404067267817 and parameters: {'model_name': 'VAE', 'batch_size': 932, 'iterations': 8584, 'learning_rate': 0.0939532677510799, 'p_miss': 0.2999395556022211}. Best is trial 14 with value: 0.10089058114892657.
[I 2024-09-25 16:17:19,017] Trial 90 finished with value: 0.11627947118536693 and parameters: {'model_name': 'VAE', 'batch_size': 80, 'iterations': 9335, 'learning_rate': 0.005520123535774136, 'p_miss': 0.09397155624748196}. Best is trial 14 with value: 0.10089058114892657.
[I 2024-09-25 16:17:27,460] Trial 112 finished with value: 0.1175385778242463 and parameters: {'model_name': 'VAE', 'batch_size': 126, 'iterations': 8966, 'learning_rate': 0.000133302579762382, 'p_miss': 0.11158092069732484}. Best is trial 14 with value: 0.10089058114892657.
fit
auto fit
auto transform
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64
0.10089058114892657
{'model_name': 'SimpleImputer', 'strategy': 'median'}
running experiment 2/3 - Does reconstruction give good automl predictions
Start est fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474cd5090> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474866410> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4f40> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d315d0> 

Generation:  1
Best root_mean_squared_error score: -31298.393343932967
Generation:   4%|▍         | 1/25 [10:20<4:08:23, 620.98s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a6b90> 

Generation:  2
Best root_mean_squared_error score: -31193.352598711248
Generation:   8%|▊         | 2/25 [20:45<3:58:44, 622.79s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474234f40> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  3
Best root_mean_squared_error score: -31169.038737541105
Generation:  12%|█▏        | 3/25 [22:06<2:17:46, 375.75s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547486eef0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  4
Best root_mean_squared_error score: -31145.47281802364
Generation:  16%|█▌        | 4/25 [27:38<2:05:29, 358.54s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474c832e0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474cd6bf0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  5
Best root_mean_squared_error score: -31060.26077463919
Generation:  20%|██        | 5/25 [28:43<1:24:08, 252.41s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474cd4d60> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  6
Best root_mean_squared_error score: -31060.26077463919
Generation:  24%|██▍       | 6/25 [29:59<1:01:01, 192.70s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467ecf7f0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474049870> 

Generation:  7
Best root_mean_squared_error score: -31060.26077463919
Generation:  28%|██▊       | 7/25 [41:03<1:43:59, 346.62s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554744f71f0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467e0ffa0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  8
Best root_mean_squared_error score: -31060.26077463919
Generation:  32%|███▏      | 8/25 [42:52<1:16:47, 271.01s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547452e080> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746f9600> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545fb77c40> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  9
Best root_mean_squared_error score: -30964.145486151734
Generation:  36%|███▌      | 9/25 [44:35<58:16, 218.51s/it]  WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554740d2ef0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  10
Best root_mean_squared_error score: -30964.145486151734
Generation:  40%|████      | 10/25 [46:31<46:41, 186.77s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545fda6830> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  11
Best root_mean_squared_error score: -30964.145486151734
Generation:  44%|████▍     | 11/25 [48:24<38:20, 164.30s/it]Generation:  12
Best root_mean_squared_error score: -30964.145486151734
Generation:  48%|████▊     | 12/25 [58:25<1:04:22, 297.12s/it]Generation:  13
Best root_mean_squared_error score: -30964.145486151734
Generation:  52%|█████▏    | 13/25 [1:00:35<49:18, 246.55s/it]Generation:  14
Best root_mean_squared_error score: -30948.607437322753
Generation:  56%|█████▌    | 14/25 [1:09:22<1:00:43, 331.24s/it]Generation:  15
Best root_mean_squared_error score: -30948.607437322753
Generation:  60%|██████    | 15/25 [1:12:36<48:16, 289.67s/it]  WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554670bf640> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  16
Best root_mean_squared_error score: -30942.86848906437
Generation:  64%|██████▍   | 16/25 [1:15:19<37:44, 251.64s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545bab8070> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  17
Best root_mean_squared_error score: -30942.86848906437
Generation:  68%|██████▊   | 17/25 [1:22:34<40:53, 306.75s/it]Generation:  18
Best root_mean_squared_error score: -30942.86848906437
Generation:  72%|███████▏  | 18/25 [1:26:08<32:31, 278.83s/it]Generation:  19
Best root_mean_squared_error score: -30942.86848906437
Generation:  76%|███████▌  | 19/25 [1:28:41<24:07, 241.22s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545fb22650> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  20
Best root_mean_squared_error score: -30898.238654434892
Generation:  80%|████████  | 20/25 [1:34:52<23:20, 280.16s/it]Generation:  21
Best root_mean_squared_error score: -30898.238654434892
Generation:  84%|████████▍ | 21/25 [1:38:22<17:16, 259.02s/it]Generation:  22
Best root_mean_squared_error score: -30898.238654434892
Generation:  88%|████████▊ | 22/25 [1:49:34<19:08, 382.91s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545ba2a500> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  23
Best root_mean_squared_error score: -30898.238654434892
Generation:  92%|█████████▏| 23/25 [1:56:26<13:03, 391.77s/it]Generation:  24
Best root_mean_squared_error score: -30898.238654434892
Generation:  96%|█████████▌| 24/25 [2:00:25<05:45, 346.00s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474135930> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545fb75cc0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545d8f5cf0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  25
Best root_mean_squared_error score: -30898.238654434892
Generation: 100%|██████████| 25/25 [2:05:05<00:00, 325.95s/it]Generation: 100%|██████████| 25/25 [2:06:18<00:00, 303.15s/it]
2024-09-25 18:36:03,765 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:35367' caused the cluster to lose scattered data, which can't be recovered: {'DataFrame-4849a007d34cf0419f2cfa91df79b9dd', 'ndarray-a07e86125e12ad14549db995e15537e7'} (stimulus_id='handle-worker-cleanup-1727314563.7656996')
Fitted
Pipeline(steps=[('xgbregressor',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=None, device=None,
                              early_stopping_rounds=None,
                              enable_categorical=False, eval_metric=None,
                              feature_types=None, gamma=0.1320330654742,
                              grow_policy=None, importance_type=None,
                              interaction_constraints=None,
                              learning_rate=0.0390785226979, max_bin=None,
                              max_cat_threshold=None, max_cat_to_onehot=None,
                              max_delta_step=None, max_depth=16,
                              max_leaves=None, min_child_weight=11, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=100, n_jobs=1, nthread=1,
                              num_parallel_tree=None, ...))])
score start
train score: {'explained_var': 0.8425800136850217, 'r2': 0.8425799012184143, 'rmse': 20963.66220014167}
original test score: {'explained_var': 0.6892269115159924, 'r2': 0.6891933679580688, 'rmse': 29471.20747526843}
imputed test score: {'explained_var': 0.6852472128589492, 'r2': 0.6851962208747864, 'rmse': 29660.10926177979}
score end
check intended
EXP2 Finished
running experiment 3/3 - What is the best automl settings?
<tpot2.search_spaces.pipelines.sequential.SequentialPipeline object at 0x1553f8c60040>
Start tpot fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554741b1150> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474654c40> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554741b50f0> 

Generation:  1
Best root_mean_squared_error score: -31835.09441462774
Generation:   4%|▍         | 1/25 [10:08<4:03:30, 608.78s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547405e530> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554740a35b0> 
WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474205cc0> 


Exception in thread Thread-3 (funcwrap):
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ketrong/miniconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
func_timeout.dafunc.FunctionTimedOut4731295821142881742: Function objective_function (args=[<tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554740a35b0>]) (kwargs={'budget': None, 'X':               0  ...         7
0      0.000029  ...  1.000000
1      0.000088  ...  0.800000
2      0.000198  ...  0.555556
3      0.004572  ...  0.200000
4      0.000050  ...       NaN
...         ...  ...       ...
18222  0.000059  ...  0.500000
18223  0.000050  ...  1.000000
18224  0.003666  ...  0.628352
18225  0.001091  ...       NaN
18226  0.002864  ...  0.324324

[18227 rows x 8 columns], 'y':           price
6672    19800.0
5198   113700.0
3943    35200.0
7737   127500.0
15790   26500.0
...         ...
8672    14999.0
4854    15000.0
5451    27100.0
5296   153100.0
21219   39000.0

[18227 rows x 1 columns]}) timed out after 600.000000 seconds.

Generation:  2
Best root_mean_squared_error score: -31835.09441462774
Generation:   8%|▊         | 2/25 [20:13<3:52:29, 606.49s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474223af0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545cf38910> 

Generation:  3
Best root_mean_squared_error score: -31713.030873885884
Generation:  12%|█▏        | 3/25 [30:19<3:42:15, 606.14s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474844eb0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474074400> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474487760> 

Generation:  4
Best root_mean_squared_error score: -31315.42371438865
Generation:  16%|█▌        | 4/25 [40:26<3:32:13, 606.38s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547409c100> 

Generation:  5
Best root_mean_squared_error score: -31029.128473994766
Generation:  20%|██        | 5/25 [50:34<3:22:20, 607.03s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554678ef730> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  6
Best root_mean_squared_error score: -31029.128473994766
Generation:  24%|██▍       | 6/25 [56:11<2:43:13, 515.43s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545fde68f0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  7
Best root_mean_squared_error score: -31001.25168673727
Generation:  28%|██▊       | 7/25 [1:01:30<2:15:18, 451.00s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474082080> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  8
Best root_mean_squared_error score: -31001.25168673727
Generation:  32%|███▏      | 8/25 [1:06:43<1:55:19, 407.01s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554740bf430> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  9
Best root_mean_squared_error score: -31001.25168673727
Generation:  36%|███▌      | 9/25 [1:11:22<1:37:54, 367.16s/it]Generation:  10
Best root_mean_squared_error score: -30905.816076402756
Generation:  40%|████      | 10/25 [1:11:58<1:06:12, 264.81s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474872500> 

Generation:  11
Best root_mean_squared_error score: -30905.816076402756
Generation:  44%|████▍     | 11/25 [1:22:08<1:26:28, 370.57s/it]Generation:  12
Best root_mean_squared_error score: -30789.695411217603
Generation:  48%|████▊     | 12/25 [1:26:49<1:14:22, 343.30s/it]Generation:  13
Best root_mean_squared_error score: -30789.695411217603
Generation:  52%|█████▏    | 13/25 [1:31:19<1:04:12, 321.07s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155486487190> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545b2ab1c0> 

Generation:  14
Best root_mean_squared_error score: -30699.063024335213
Generation:  56%|█████▌    | 14/25 [1:41:28<1:14:49, 408.13s/it]Generation:  15
Best root_mean_squared_error score: -30699.063024335213
Generation:  60%|██████    | 15/25 [1:48:23<1:08:22, 410.25s/it]Generation:  16
Best root_mean_squared_error score: -30699.063024335213
Generation:  64%|██████▍   | 16/25 [1:49:12<45:13, 301.46s/it]  WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545d345120> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554678e7eb0> 

Generation:  17
Best root_mean_squared_error score: -30699.063024335213
Generation:  68%|██████▊   | 17/25 [1:59:22<52:33, 394.18s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155466b2c1f0> 

Generation:  18
Best root_mean_squared_error score: -30650.352343092694
Generation:  72%|███████▏  | 18/25 [2:09:30<53:29, 458.48s/it]Generation:  19
Best root_mean_squared_error score: -30650.352343092694
Generation:  76%|███████▌  | 19/25 [2:10:36<34:02, 340.49s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1553f0755cc0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545fe8ff40> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545c73e950> 

Generation:  20
Best root_mean_squared_error score: -30650.352343092694
Generation:  80%|████████  | 20/25 [2:20:45<35:05, 421.19s/it]Generation:  21
Best root_mean_squared_error score: -30650.352343092694
Generation:  84%|████████▍ | 21/25 [2:25:38<25:30, 382.73s/it]Generation:  22
Best root_mean_squared_error score: -30650.352343092694
Generation:  88%|████████▊ | 22/25 [2:33:07<20:07, 402.42s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546578bf40> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464fe4910> 

Generation:  23
Best root_mean_squared_error score: -30650.352343092694
Generation:  92%|█████████▏| 23/25 [2:43:15<15:28, 464.30s/it]Generation:  24
Best root_mean_squared_error score: -30606.75381791853
Generation:  96%|█████████▌| 24/25 [2:48:22<06:57, 417.12s/it]Generation:  25
Best root_mean_squared_error score: -30606.75381791853
Generation: 100%|██████████| 25/25 [2:49:14<00:00, 307.44s/it]Generation: 100%|██████████| 25/25 [2:49:14<00:00, 406.17s/it]
2024-09-25 21:47:06,832 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:41825' caused the cluster to lose scattered data, which can't be recovered: {'DataFrame-88c44b2494fda67cd813355a2735d618', 'DataFrame-4849a007d34cf0419f2cfa91df79b9dd'} (stimulus_id='handle-worker-cleanup-1727326026.8323429')
Fitted
Pipeline(steps=[('knnimputer', KNNImputer(n_neighbors=48)),
                ('xgbregressor',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=None, device=None,
                              early_stopping_rounds=None,
                              enable_categorical=False, eval_metric=None,
                              feature_types=None, gamma=9.6873002415153,
                              grow_policy=None, importance_type=None,
                              interaction_constraints=None,
                              learning_rate=0.0489505109365, max_bin=None,
                              max_cat_threshold=None, max_cat_to_onehot=None,
                              max_delta_step=None, max_depth=12,
                              max_leaves=None, min_child_weight=14, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=100, n_jobs=1, nthread=1,
                              num_parallel_tree=None, ...))])
transform worked
try transform
transform worked
score start
train score: {'explained_var': 0.8236344499111456, 'r2': 0.8236342668533325, 'rmse': 22189.329920851447}
test score: {'explained_var': 0.6867666802452173, 'r2': 0.6867485046386719, 'rmse': 29586.89165708256}
original test score: {'explained_var': 0.6929944302746571, 'r2': 0.6929927468299866, 'rmse': 29290.5203385256}
score end
218
lvl
0.1
type
MAR
num_run
2
reg_full
finished
all finished
full run takes
12.19757966697216
hours
DONE
