Run: 50
/cm/local/apps/slurm/var/spool/job987654/slurm_script: line 26: 
pip install -e tpot2
pip install -r tpot2/ImputerExperiments/requirements_.txt
: No such file or directory
RunStart
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
starting loops
../data/r/1200/1200.pkl
working on 
../data/r/1200/reg_full_MCAR_0.1_3
1.501220703125
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2024-10-03 22:34:11,448] A new study created in memory with name: no-name-5a9ab59c-ba08-48b4-8630-0411b6639ebe
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
[I 2024-10-03 22:34:11,979] Trial 6 finished with value: 0.5300969571533275 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 6 with value: 0.5300969571533275.
running
[I 2024-10-03 22:34:18,594] Trial 3 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 3, 'hint_rate': 0.2975465526873148, 'alpha': 11, 'iterations': 4, 'learning_rate': 0.0009479468734825514, 'p_miss': 0.024703348629318275}. Best is trial 6 with value: 0.5300969571533275.
running
[I 2024-10-03 22:34:21,269] Trial 16 finished with value: 0.4663973845126438 and parameters: {'model_name': 'GAIN', 'batch_size': 47, 'hint_rate': 0.010143912015777894, 'alpha': 59, 'iterations': 1, 'learning_rate': 0.0042027818102516185, 'p_miss': 0.024976413756138297}. Best is trial 16 with value: 0.4663973845126438.
running
[I 2024-10-03 22:34:21,952] Trial 0 finished with value: 0.21861889514270202 and parameters: {'model_name': 'VAE', 'batch_size': 5, 'iterations': 2, 'learning_rate': 0.000981957046509216, 'p_miss': 0.2340429788728828}. Best is trial 0 with value: 0.21861889514270202.
running
[I 2024-10-03 22:34:23,850] Trial 9 finished with value: 0.4366249319763623 and parameters: {'model_name': 'GAIN', 'batch_size': 37, 'hint_rate': 0.503062666286871, 'alpha': 20, 'iterations': 5, 'learning_rate': 0.026610308036665448, 'p_miss': 0.1993642483626851}. Best is trial 0 with value: 0.21861889514270202.
running
[I 2024-10-03 22:34:28,255] Trial 18 finished with value: 0.42634164585294465 and parameters: {'model_name': 'GAIN', 'batch_size': 142, 'hint_rate': 0.4483625451152193, 'alpha': 25, 'iterations': 7, 'learning_rate': 0.0009433080242541089, 'p_miss': 0.27267870023998}. Best is trial 0 with value: 0.21861889514270202.
running
[I 2024-10-03 22:34:28,622] Trial 21 finished with value: 0.5300969571533275 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 0 with value: 0.21861889514270202.
running
[I 2024-10-03 22:34:29,198] Trial 22 finished with value: 0.5300969571533275 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 0 with value: 0.21861889514270202.
running
[I 2024-10-03 22:34:48,161] Trial 10 finished with value: 0.2112181537316422 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 25, 'learning_rate': 0.00030793662845004214, 'p_miss': 0.24064380188794798}. Best is trial 10 with value: 0.2112181537316422.
running
[I 2024-10-03 22:34:58,822] Trial 24 finished with value: 0.2034754332329684 and parameters: {'model_name': 'VAE', 'batch_size': 174, 'iterations': 2, 'learning_rate': 0.009582442006585859, 'p_miss': 0.19568533112969172}. Best is trial 24 with value: 0.2034754332329684.
running
[I 2024-10-03 22:35:09,791] Trial 2 finished with value: 0.20222483287014917 and parameters: {'model_name': 'VAE', 'batch_size': 80, 'iterations': 41, 'learning_rate': 0.0018771158998533075, 'p_miss': 0.21768176933384037}. Best is trial 2 with value: 0.20222483287014917.
running
[I 2024-10-03 22:35:21,035] Trial 14 finished with value: 0.20613065914832066 and parameters: {'model_name': 'VAE', 'batch_size': 20, 'iterations': 75, 'learning_rate': 0.014105705204460646, 'p_miss': 0.23094914576677253}. Best is trial 2 with value: 0.20222483287014917.
running
[I 2024-10-03 22:35:35,894] Trial 4 finished with value: 0.16966085846390963 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 9512, 'weights': 'uniform'}. Best is trial 4 with value: 0.16966085846390963.
running
[I 2024-10-03 22:35:48,314] Trial 17 finished with value: 0.19639677813273373 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 43177, 'weights': 'uniform'}. Best is trial 4 with value: 0.16966085846390963.
running
[I 2024-10-03 22:35:50,808] Trial 12 finished with value: 0.17062974746159018 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 5, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 4 with value: 0.16966085846390963.
running
[I 2024-10-03 22:35:51,652] Trial 1 finished with value: 0.17896954706089105 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 18390, 'weights': 'uniform'}. Best is trial 4 with value: 0.16966085846390963.
running
[I 2024-10-03 22:35:55,982] Trial 13 finished with value: 0.1680162093558457 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 11032, 'weights': 'distance'}. Best is trial 13 with value: 0.1680162093558457.
running
[I 2024-10-03 22:36:20,119] Trial 27 finished with value: 0.17110467018451997 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'constant', 'n_nearest_features': 5, 'imputation_order': 'descending'}. Best is trial 13 with value: 0.1680162093558457.
running
[I 2024-10-03 22:36:20,736] Trial 7 finished with value: 0.4569015245539826 and parameters: {'model_name': 'GAIN', 'batch_size': 32, 'hint_rate': 0.12734520154918466, 'alpha': 49, 'iterations': 223, 'learning_rate': 0.00029290418317879925, 'p_miss': 0.08022529228691369}. Best is trial 13 with value: 0.1680162093558457.
running
[I 2024-10-03 22:36:27,258] Trial 19 finished with value: 0.18674206627624568 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 40092, 'weights': 'distance'}. Best is trial 13 with value: 0.1680162093558457.
running
[I 2024-10-03 22:36:36,095] Trial 15 finished with value: 0.2715514446188575 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 9, 'imputation_order': 'random', 'sample_posterior': True}. Best is trial 13 with value: 0.1680162093558457.
running
[I 2024-10-03 22:36:39,048] Trial 20 finished with value: 0.1804782860584791 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 26624, 'weights': 'distance'}. Best is trial 13 with value: 0.1680162093558457.
running
[I 2024-10-03 22:37:03,143] Trial 26 finished with value: 0.28472703579913966 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 2, 'imputation_order': 'arabic', 'sample_posterior': True}. Best is trial 13 with value: 0.1680162093558457.
running
[I 2024-10-03 22:37:03,825] Trial 8 finished with value: 0.4688116192809416 and parameters: {'model_name': 'GAIN', 'batch_size': 583, 'hint_rate': 0.38898363295473576, 'alpha': 70, 'iterations': 237, 'learning_rate': 0.009605271346922165, 'p_miss': 0.11910579341893687}. Best is trial 13 with value: 0.1680162093558457.
running
[I 2024-10-03 22:37:08,789] Trial 28 finished with value: 0.16749865282506465 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 7378, 'weights': 'uniform'}. Best is trial 28 with value: 0.16749865282506465.
running
[I 2024-10-03 22:37:17,363] Trial 25 finished with value: 0.17736822276842584 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 22624, 'weights': 'distance'}. Best is trial 28 with value: 0.16749865282506465.
running
[I 2024-10-03 22:37:25,335] Trial 29 finished with value: 0.17178985572715086 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 11604, 'weights': 'uniform'}. Best is trial 28 with value: 0.16749865282506465.
running
[I 2024-10-03 22:37:33,067] Trial 32 finished with value: 0.1608025735885467 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3891, 'weights': 'distance'}. Best is trial 32 with value: 0.1608025735885467.
running
[I 2024-10-03 22:37:39,444] Trial 33 finished with value: 0.14688075138118264 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 93, 'weights': 'distance'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:37:49,292] Trial 31 finished with value: 0.17062974746159018 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 5, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:37:54,582] Trial 35 finished with value: 0.1535964682462975 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 988, 'weights': 'distance'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:37:56,068] Trial 37 finished with value: 0.18675478149371155 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 1, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:38:01,933] Trial 34 finished with value: 0.16195521818847353 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4691, 'weights': 'distance'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:38:06,625] Trial 30 finished with value: 0.17062974746159018 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 5, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:38:11,894] Trial 36 finished with value: 0.15654052568481083 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1841, 'weights': 'distance'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:38:28,744] Trial 40 finished with value: 0.1516730079263385 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 468, 'weights': 'uniform'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:38:31,053] Trial 39 finished with value: 0.1560477303291944 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1671, 'weights': 'distance'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:38:33,427] Trial 38 finished with value: 0.15452850331981 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1214, 'weights': 'distance'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:38:36,513] Trial 41 finished with value: 0.1550963738866829 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1024, 'weights': 'uniform'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:38:50,941] Trial 43 finished with value: 0.15560496111721409 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1521, 'weights': 'distance'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:38:53,151] Trial 42 finished with value: 0.16452681145813125 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4902, 'weights': 'uniform'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:38:55,345] Trial 44 finished with value: 0.14964141494816835 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 343, 'weights': 'distance'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:39:05,220] Trial 47 finished with value: 0.1484004763984134 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 222, 'weights': 'distance'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:39:06,433] Trial 45 finished with value: 0.15526941459380764 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1419, 'weights': 'distance'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:39:07,753] Trial 46 finished with value: 0.15225931019099226 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 719, 'weights': 'distance'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:39:08,945] Trial 60 finished with value: 0.5300969571533275 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:39:14,950] Trial 48 finished with value: 0.15244732279987588 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 753, 'weights': 'distance'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:39:18,545] Trial 49 finished with value: 0.1519211711730533 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 662, 'weights': 'distance'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:39:20,412] Trial 50 finished with value: 0.14732365208847764 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 33, 'weights': 'distance'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:39:34,035] Trial 52 finished with value: 0.16019344557591922 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 7, 'weights': 'distance'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:39:36,628] Trial 51 finished with value: 0.1515816393840523 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 607, 'weights': 'distance'}. Best is trial 33 with value: 0.14688075138118264.
running
[I 2024-10-03 22:39:38,907] Trial 53 finished with value: 0.14672818532688742 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 78, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-03 22:39:39,365] Trial 54 finished with value: 0.15158925255648678 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 608, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-03 22:39:50,482] Trial 56 finished with value: 0.15291736304047945 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 636, 'weights': 'uniform'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-03 22:39:55,845] Trial 57 finished with value: 0.15391619901210665 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1064, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-03 22:40:00,420] Trial 58 finished with value: 0.15239415746837243 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 744, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-03 22:40:13,935] Trial 59 finished with value: 0.16473245903742548 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 7201, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-03 22:40:14,281] Trial 55 finished with value: 0.17146457591531933 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 15219, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-03 22:40:15,430] Trial 61 finished with value: 0.16488068703141007 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 7363, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 00:43:04,162] Trial 11 finished with value: 0.19193043780561453 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 2, 'imputation_order': 'random'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 01:09:01,008] Trial 5 finished with value: 0.17199583360322385 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 3, 'imputation_order': 'roman'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 01:24:27,539] Trial 23 finished with value: 0.46884603666993063 and parameters: {'model_name': 'GAIN', 'batch_size': 320, 'hint_rate': 0.2533300209237583, 'alpha': 88, 'iterations': 5291, 'learning_rate': 0.0009258663257876575, 'p_miss': 0.10146855524985343}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 03:14:45,958] Trial 71 finished with value: 0.20407589447705826 and parameters: {'model_name': 'VAE', 'batch_size': 511, 'iterations': 3557, 'learning_rate': 0.07546079252091246, 'p_miss': 0.29790159301631236}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 03:14:47,379] Trial 78 finished with value: 0.19639677813273373 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 03:50:48,779] Trial 74 finished with value: 0.20371392368511065 and parameters: {'model_name': 'VAE', 'batch_size': 481, 'iterations': 3566, 'learning_rate': 0.08971186507982143, 'p_miss': 0.13923569780649037}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 03:55:15,292] Trial 80 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 6, 'hint_rate': 0.9077413842465709, 'alpha': 91, 'iterations': 669, 'learning_rate': 0.00010783787420809547, 'p_miss': 0.06403201669349015}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 03:56:01,765] Trial 81 finished with value: 0.16200563900525983 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4728, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 03:56:48,246] Trial 82 finished with value: 0.1620595554757064 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4768, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 03:57:57,543] Trial 83 finished with value: 0.1852442489666898 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 33369, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 03:58:45,753] Trial 84 finished with value: 0.1615304404933473 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4380, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:06:12,860] Trial 85 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.9779379238991315, 'alpha': 41, 'iterations': 945, 'learning_rate': 0.03769513034708442, 'p_miss': 0.1695496323818061}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:06:56,432] Trial 86 finished with value: 0.16286212728247135 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3847, 'weights': 'uniform'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:07:48,087] Trial 87 finished with value: 0.16590519770970735 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 8515, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:08:43,811] Trial 88 finished with value: 0.16849921799057302 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 11617, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:09:32,429] Trial 89 finished with value: 0.16236440012333642 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3573, 'weights': 'uniform'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:09:34,322] Trial 90 finished with value: 0.19349404697212177 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:10:26,369] Trial 91 finished with value: 0.16379341144725262 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 6251, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:11:26,754] Trial 92 finished with value: 0.20560487459528587 and parameters: {'model_name': 'VAE', 'batch_size': 13, 'iterations': 10, 'learning_rate': 0.0037325058281447877, 'p_miss': 0.17116423141111378}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:12:25,473] Trial 93 finished with value: 0.16725941116138668 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 10121, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:13:08,097] Trial 94 finished with value: 0.16213458833763666 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3450, 'weights': 'uniform'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:14:18,538] Trial 95 finished with value: 0.18168723420391034 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 28239, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:15:07,169] Trial 96 finished with value: 0.15868115831186938 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2724, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:15:54,956] Trial 97 finished with value: 0.15943653282410905 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3098, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:16:46,072] Trial 98 finished with value: 0.16365009528424515 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 6117, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:17:33,533] Trial 99 finished with value: 0.1596247404945644 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3197, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:18:36,155] Trial 100 finished with value: 0.18674206627624568 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 45921, 'weights': 'distance'}. Best is trial 53 with value: 0.14672818532688742.
running
[I 2024-10-04 04:19:18,906] Trial 101 finished with value: 0.14663247430185566 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 70, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:20:03,944] Trial 102 finished with value: 0.16006897128671396 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2518, 'weights': 'uniform'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:20:49,122] Trial 103 finished with value: 0.15789808658212998 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2374, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:27:57,326] Trial 104 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 2, 'hint_rate': 0.6913214466300162, 'alpha': 100, 'iterations': 953, 'learning_rate': 0.00015873828948129257, 'p_miss': 0.06887729542378924}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:30:08,595] Trial 105 finished with value: 0.16737307277085936 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'ascending'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:30:47,772] Trial 106 finished with value: 0.14686108781741006 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 90, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:31:29,724] Trial 107 finished with value: 0.14727108822967408 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 128, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:32:08,694] Trial 108 finished with value: 0.16720597261359346 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:32:53,870] Trial 109 finished with value: 0.15832513411678575 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2559, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:34:00,405] Trial 110 finished with value: 0.17582027864002797 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 20665, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:34:49,923] Trial 111 finished with value: 0.1628015217037127 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5361, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:35:30,312] Trial 112 finished with value: 0.14732294933309625 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 133, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:36:17,746] Trial 113 finished with value: 0.15808083407627907 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2453, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:36:21,010] Trial 114 finished with value: 0.5300969571533275 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:44:58,707] Trial 77 finished with value: 0.21617011027768776 and parameters: {'model_name': 'VAE', 'batch_size': 11, 'iterations': 2270, 'learning_rate': 0.07784126647832569, 'p_miss': 0.2932023472631674}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:45:39,360] Trial 116 finished with value: 0.14802069416548855 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 189, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:46:16,732] Trial 117 finished with value: 0.15286176548104896 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 12, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:47:01,198] Trial 118 finished with value: 0.15641588915774035 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1798, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:47:47,588] Trial 119 finished with value: 0.1571865901001555 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2082, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:48:27,071] Trial 120 finished with value: 0.14777707831152312 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 168, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:49:06,249] Trial 121 finished with value: 0.1469526803178459 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 96, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:49:44,026] Trial 122 finished with value: 0.1498144430898143 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 18, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:50:28,430] Trial 123 finished with value: 0.1574287550829014 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2176, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:51:16,898] Trial 124 finished with value: 0.16107671602598925 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4070, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:52:40,881] Trial 115 finished with value: 0.2084584846153262 and parameters: {'model_name': 'VAE', 'batch_size': 10, 'iterations': 168, 'learning_rate': 0.00038135479195610934, 'p_miss': 0.011743120878946578}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:53:15,943] Trial 125 finished with value: 0.1675319141280727 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'median', 'n_nearest_features': 7, 'imputation_order': 'descending'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:53:27,992] Trial 126 finished with value: 0.15621707284711767 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1728, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:54:02,286] Trial 127 finished with value: 0.15606218634519559 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1676, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:54:07,728] Trial 128 finished with value: 0.14724934066756964 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 126, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:54:45,044] Trial 129 finished with value: 0.14782961840015393 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 172, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:54:56,417] Trial 130 finished with value: 0.1551600170482339 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1387, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:55:24,829] Trial 131 finished with value: 0.14810116202414494 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 26, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:55:48,880] Trial 132 finished with value: 0.16313065198813964 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5647, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:56:14,840] Trial 133 finished with value: 0.16038469282143475 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3636, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:56:38,393] Trial 134 finished with value: 0.16031172071999156 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3590, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:57:18,243] Trial 136 finished with value: 0.14764526515622153 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 158, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:57:20,217] Trial 135 finished with value: 0.42714746251970903 and parameters: {'model_name': 'GAIN', 'batch_size': 959, 'hint_rate': 0.6869901013411212, 'alpha': 72, 'iterations': 20, 'learning_rate': 0.0022053894381607545, 'p_miss': 0.2598009770898777}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:58:04,448] Trial 137 finished with value: 0.1558421878039634 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1601, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:58:06,405] Trial 138 finished with value: 0.15569396780731473 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1550, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:58:48,892] Trial 139 finished with value: 0.15494848463374608 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1327, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:58:50,041] Trial 140 finished with value: 0.14716323892423752 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 117, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:59:33,957] Trial 141 finished with value: 0.14961703998197198 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 340, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:59:35,348] Trial 143 finished with value: 0.19349404697212177 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 04:59:41,455] Trial 142 finished with value: 0.16198880003262323 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4716, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:00:24,345] Trial 144 finished with value: 0.15917532931183404 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2969, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:00:42,643] Trial 145 finished with value: 0.1702007316830817 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 13669, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:01:30,939] Trial 146 finished with value: 0.18674206627624568 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 36591, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:01:48,800] Trial 147 finished with value: 0.18674206627624568 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 36787, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:02:10,913] Trial 148 finished with value: 0.15028013789916722 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 17, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:02:33,990] Trial 149 finished with value: 0.15381738402904876 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1042, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:02:54,725] Trial 150 finished with value: 0.15360643095436832 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 990, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:03:17,809] Trial 151 finished with value: 0.15428689438066032 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1153, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:03:43,215] Trial 152 finished with value: 0.15788964021285445 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2370, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:04:08,877] Trial 153 finished with value: 0.1581454983409243 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2480, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:04:15,166] Trial 154 finished with value: 0.1677545673624742 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 8, 'imputation_order': 'arabic'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:04:48,918] Trial 155 finished with value: 0.14757117734072056 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 30, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:04:56,507] Trial 156 finished with value: 0.14688075138118264 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 93, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:05:29,057] Trial 157 finished with value: 0.14865058143908835 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 22, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:05:42,412] Trial 158 finished with value: 0.15433302330514623 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1164, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:06:20,163] Trial 159 finished with value: 0.15963441829127334 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3202, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:06:57,473] Trial 160 finished with value: 0.18129995645564106 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 27715, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:07:28,858] Trial 161 finished with value: 0.18104769897366546 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 27378, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:12:18,443] Trial 79 finished with value: 0.210723362148189 and parameters: {'model_name': 'VAE', 'batch_size': 9, 'iterations': 1304, 'learning_rate': 0.00014472500534501846, 'p_miss': 0.13364805118619288}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:13:47,580] Trial 162 finished with value: 0.23179118155451572 and parameters: {'model_name': 'VAE', 'batch_size': 2, 'iterations': 83, 'learning_rate': 0.028512343973099555, 'p_miss': 0.14497180273593338}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:14:02,178] Trial 165 finished with value: 0.4542173822350163 and parameters: {'model_name': 'GAIN', 'batch_size': 78, 'hint_rate': 0.7525925305458457, 'alpha': 34, 'iterations': 1, 'learning_rate': 0.005898222149234455, 'p_miss': 0.10819625914838057}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:14:45,140] Trial 166 finished with value: 0.15340289331202264 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 945, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:15:28,119] Trial 167 finished with value: 0.156724298431543 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1907, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:15:56,882] Trial 163 finished with value: 0.245472402086728 and parameters: {'model_name': 'VAE', 'batch_size': 2, 'iterations': 91, 'learning_rate': 0.031207556174800304, 'p_miss': 0.14383668897465574}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:16:11,508] Trial 168 finished with value: 0.15232522851947206 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 731, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:16:37,087] Trial 169 finished with value: 0.16720597261359346 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:16:58,975] Trial 170 finished with value: 0.15882056636639194 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2796, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:17:24,636] Trial 171 finished with value: 0.15874556776984367 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2758, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:17:45,606] Trial 172 finished with value: 0.15684386770506195 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1955, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:18:14,530] Trial 173 finished with value: 0.16114515892260234 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4115, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:18:15,742] Trial 175 finished with value: 0.19639677813273373 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:18:31,079] Trial 174 finished with value: 0.16324173257527294 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4066, 'weights': 'uniform'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:18:56,706] Trial 176 finished with value: 0.14688995272605881 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 89, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:19:10,184] Trial 177 finished with value: 0.14941517158525128 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 19, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:19:40,717] Trial 178 finished with value: 0.15433024880756802 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1163, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:19:53,976] Trial 179 finished with value: 0.15383759133769176 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1046, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:20:25,533] Trial 180 finished with value: 0.15280295987366949 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 819, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:21:02,704] Trial 181 finished with value: 0.1791198815981499 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 24858, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:21:12,442] Trial 182 finished with value: 0.15682268877081568 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1946, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:21:52,239] Trial 183 finished with value: 0.15706797357133798 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2038, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:21:53,442] Trial 184 finished with value: 0.14865058143908835 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 22, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:22:38,964] Trial 185 finished with value: 0.15274015795656323 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 805, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:22:40,454] Trial 186 finished with value: 0.1526908187336093 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 796, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:23:19,362] Trial 187 finished with value: 0.14663388301662067 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 50, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:23:21,081] Trial 188 finished with value: 0.1470111786504125 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 101, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:24:03,899] Trial 189 finished with value: 0.15618853057088203 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1719, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:24:05,247] Trial 190 finished with value: 0.15628146573583523 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1750, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:24:51,289] Trial 191 finished with value: 0.15941623964257143 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3088, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:26:01,527] Trial 192 finished with value: 0.1691462646290744 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'mean', 'n_nearest_features': 7, 'imputation_order': 'ascending'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:26:45,324] Trial 194 finished with value: 0.1536351391772309 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 998, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:26:49,589] Trial 193 finished with value: 0.16648494145267254 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'median', 'n_nearest_features': 7, 'imputation_order': 'ascending'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:27:26,258] Trial 195 finished with value: 0.146966444762863 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 38, 'weights': 'distance'}. Best is trial 101 with value: 0.14663247430185566.
running
[I 2024-10-04 05:27:30,440] Trial 196 finished with value: 0.1465810315747474 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 68, 'weights': 'distance'}. Best is trial 196 with value: 0.1465810315747474.
running
[I 2024-10-04 05:28:06,132] Trial 197 finished with value: 0.15224470265665566 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 13, 'weights': 'distance'}. Best is trial 196 with value: 0.1465810315747474.
running
[I 2024-10-04 05:28:11,610] Trial 198 finished with value: 0.14663740568181544 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 53, 'weights': 'distance'}. Best is trial 196 with value: 0.1465810315747474.
[I 2024-10-04 05:28:48,759] Trial 199 finished with value: 0.15556063094057945 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1505, 'weights': 'distance'}. Best is trial 196 with value: 0.1465810315747474.
[I 2024-10-04 06:10:07,431] Trial 164 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 2, 'hint_rate': 0.761345081633513, 'alpha': 0, 'iterations': 8792, 'learning_rate': 0.006004018270872612, 'p_miss': 0.09635101798633083}. Best is trial 196 with value: 0.1465810315747474.
[I 2024-10-04 06:32:06,258] Trial 65 finished with value: 0.20356675214000472 and parameters: {'model_name': 'VAE', 'batch_size': 547, 'iterations': 5789, 'learning_rate': 0.07964953609201679, 'p_miss': 0.2953386896477148}. Best is trial 196 with value: 0.1465810315747474.
[I 2024-10-04 07:53:40,468] Trial 67 finished with value: 0.2036384059037309 and parameters: {'model_name': 'VAE', 'batch_size': 992, 'iterations': 5834, 'learning_rate': 0.09393039376353525, 'p_miss': 0.29719075016274343}. Best is trial 196 with value: 0.1465810315747474.
[I 2024-10-04 08:02:33,508] Trial 64 finished with value: 0.21976860161996853 and parameters: {'model_name': 'VAE', 'batch_size': 7, 'iterations': 8977, 'learning_rate': 0.00010277675236053828, 'p_miss': 0.2959051484832862}. Best is trial 196 with value: 0.1465810315747474.
[I 2024-10-04 08:14:01,509] Trial 66 finished with value: 0.2034178001218312 and parameters: {'model_name': 'VAE', 'batch_size': 610, 'iterations': 7422, 'learning_rate': 0.08940716496956515, 'p_miss': 0.29815727897822886}. Best is trial 196 with value: 0.1465810315747474.
[I 2024-10-04 09:04:27,680] Trial 63 finished with value: 0.26122764756261363 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 9271, 'learning_rate': 0.07181659633640894, 'p_miss': 0.1424430252665947}. Best is trial 196 with value: 0.1465810315747474.
[I 2024-10-04 09:36:41,551] Trial 68 finished with value: 0.20295652720048554 and parameters: {'model_name': 'VAE', 'batch_size': 711, 'iterations': 8278, 'learning_rate': 0.08505716352746369, 'p_miss': 0.2976080933624754}. Best is trial 196 with value: 0.1465810315747474.
[I 2024-10-04 09:40:50,332] Trial 73 finished with value: 0.20350616474124364 and parameters: {'model_name': 'VAE', 'batch_size': 791, 'iterations': 8331, 'learning_rate': 0.08682160761702169, 'p_miss': 0.14431528158614704}. Best is trial 196 with value: 0.1465810315747474.
[I 2024-10-04 09:45:25,536] Trial 69 finished with value: 0.2036346096021393 and parameters: {'model_name': 'VAE', 'batch_size': 802, 'iterations': 8585, 'learning_rate': 0.056710090928872234, 'p_miss': 0.14657002269077074}. Best is trial 196 with value: 0.1465810315747474.
[I 2024-10-04 09:46:55,891] Trial 70 finished with value: 0.2032605266740842 and parameters: {'model_name': 'VAE', 'batch_size': 913, 'iterations': 8442, 'learning_rate': 0.05336028279422095, 'p_miss': 0.14185038912590758}. Best is trial 196 with value: 0.1465810315747474.
[I 2024-10-04 09:52:09,207] Trial 72 finished with value: 0.20403134018817037 and parameters: {'model_name': 'VAE', 'batch_size': 775, 'iterations': 9504, 'learning_rate': 0.08345695353721833, 'p_miss': 0.146579108245547}. Best is trial 196 with value: 0.1465810315747474.
[I 2024-10-04 10:05:35,737] Trial 75 finished with value: 0.203473314921282 and parameters: {'model_name': 'VAE', 'batch_size': 690, 'iterations': 9770, 'learning_rate': 0.09499681071402552, 'p_miss': 0.2920683923154499}. Best is trial 196 with value: 0.1465810315747474.
[I 2024-10-04 10:05:41,591] Trial 62 finished with value: 0.20375749166285334 and parameters: {'model_name': 'VAE', 'batch_size': 999, 'iterations': 9159, 'learning_rate': 0.06714281556141756, 'p_miss': 0.29879408230278826}. Best is trial 196 with value: 0.1465810315747474.
[I 2024-10-04 10:09:46,664] Trial 76 finished with value: 0.2035131078899369 and parameters: {'model_name': 'VAE', 'batch_size': 840, 'iterations': 9794, 'learning_rate': 0.06914068929796435, 'p_miss': 0.14749189347459507}. Best is trial 196 with value: 0.1465810315747474.
fit
auto fit
auto transform
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64
0.1465810315747474
{'model_name': 'KNNImputer', 'n_neighbors': 68, 'weights': 'distance'}
running experiment 2/3 - Does reconstruction give good automl predictions
Start est fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a55a0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a8f10> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a8dc0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  1
Best root_mean_squared_error score: -3.274989725656533
Generation:   4%|▍         | 1/25 [04:04<1:37:59, 244.97s/it]Generation:  2
Best root_mean_squared_error score: -3.1656055215272425
Generation:   8%|▊         | 2/25 [07:42<1:27:49, 229.09s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547472c4f0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  3
Best root_mean_squared_error score: -3.1656055215272425
Generation:  12%|█▏        | 3/25 [11:16<1:21:26, 222.10s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a63e0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546481b490> 

Generation:  4
Best root_mean_squared_error score: -3.132397676953908
Generation:  16%|█▌        | 4/25 [21:20<2:10:32, 372.97s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546727a4a0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  5
Best root_mean_squared_error score: -3.132397676953908
Generation:  20%|██        | 5/25 [22:34<1:28:17, 264.89s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554672e4a60> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467e2e2f0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  6
Best root_mean_squared_error score: -3.132397676953908
Generation:  24%|██▍       | 6/25 [24:05<1:05:13, 206.00s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a5570> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  7
Best root_mean_squared_error score: -3.132397676953908
Generation:  28%|██▊       | 7/25 [25:39<50:48, 169.38s/it]  WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467d74430> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  8
Best root_mean_squared_error score: -3.1078993377351805
Generation:  32%|███▏      | 8/25 [26:10<35:29, 125.28s/it]Generation:  9
Best root_mean_squared_error score: -3.1078993377351805
Generation:  36%|███▌      | 9/25 [27:51<31:20, 117.55s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f038e0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554747097b0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  10
Best root_mean_squared_error score: -3.1078993377351805
Generation:  40%|████      | 10/25 [29:26<27:37, 110.52s/it]Generation:  11
Best root_mean_squared_error score: -3.1078993377351805
Generation:  44%|████▍     | 11/25 [30:52<24:03, 103.11s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464854be0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  12
Best root_mean_squared_error score: -3.1078993377351805
Generation:  48%|████▊     | 12/25 [32:00<20:02, 92.47s/it] Generation:  13
Best root_mean_squared_error score: -3.0842346424617935
Generation:  52%|█████▏    | 13/25 [36:07<27:50, 139.17s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467c23520> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a6530> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467e18be0> 

Generation:  14
Best root_mean_squared_error score: -3.0842346424617935
Generation:  56%|█████▌    | 14/25 [46:14<51:24, 280.44s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547470f280> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  15
Best root_mean_squared_error score: -3.0842346424617935
Generation:  60%|██████    | 15/25 [52:09<50:29, 302.97s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f00910> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  16
Best root_mean_squared_error score: -3.0842346424617935
Generation:  64%|██████▍   | 16/25 [55:30<40:51, 272.44s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547470aaa0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467129630> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467540880> 

Generation:  17
Best root_mean_squared_error score: -3.0834055571144057
Generation:  68%|██████▊   | 17/25 [1:05:38<49:46, 373.27s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467247d90> 

Generation:  18
Best root_mean_squared_error score: -3.0834055571144057
Generation:  72%|███████▏  | 18/25 [1:15:46<51:46, 443.79s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467d4e1a0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  19
Best root_mean_squared_error score: -3.0834055571144057
Generation:  76%|███████▌  | 19/25 [1:17:53<34:51, 348.59s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474728b80> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  20
Best root_mean_squared_error score: -3.0834055571144057
Generation:  80%|████████  | 20/25 [1:21:35<25:52, 310.55s/it]Generation:  21
Best root_mean_squared_error score: -3.0834055571144057
Generation:  84%|████████▍ | 21/25 [1:23:03<16:15, 243.84s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467e9f4c0> 

Generation:  22
Best root_mean_squared_error score: -3.0834055571144057
Generation:  88%|████████▊ | 22/25 [1:33:14<17:42, 354.10s/it]Generation:  23
Best root_mean_squared_error score: -3.0834055571144057
Generation:  92%|█████████▏| 23/25 [1:40:43<12:44, 382.48s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547470c0d0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  24
Best root_mean_squared_error score: -3.0834055571144057
Generation:  96%|█████████▌| 24/25 [1:47:50<06:36, 396.01s/it]Generation:  25
Best root_mean_squared_error score: -3.0834055571144057
Generation: 100%|██████████| 25/25 [1:50:49<00:00, 330.82s/it]Generation: 100%|██████████| 25/25 [1:50:52<00:00, 266.10s/it]
2024-10-04 12:02:20,935 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:34971' caused the cluster to lose scattered data, which can't be recovered: {'ndarray-021bc46adab41d4648eeae64587450cc', 'DataFrame-edee9f7d9e8d9a17dcfe6b777e771f31'} (stimulus_id='handle-worker-cleanup-1728068540.9358351')
Fitted
Pipeline(steps=[('histgradientboostingregressor',
                 HistGradientBoostingRegressor(early_stopping=True,
                                               l2_regularization=1.2721e-09,
                                               learning_rate=0.0398138674324,
                                               max_features=0.1710023127433,
                                               max_leaf_nodes=839,
                                               min_samples_leaf=15, tol=0.0001,
                                               validation_fraction=None))])
score start
train score: {'explained_var': 0.9000878346836519, 'r2': 0.9000878346836519, 'rmse': 2.065012720708844}
original test score: {'explained_var': 0.8035311337602299, 'r2': 0.8035301616490684, 'rmse': 2.9035514298904244}
imputed test score: {'explained_var': 0.7701082182448514, 'r2': 0.7700997883725422, 'rmse': 3.140879424860683}
score end
check intended
EXP2 Finished
running experiment 3/3 - What is the best automl settings?
<tpot2.search_spaces.pipelines.sequential.SequentialPipeline object at 0x15538c3bd5a0>
Start tpot fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4ca0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554747110f0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4bb0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a8d30> 

Generation:  1
Best root_mean_squared_error score: -3.1077589427459973
Generation:   4%|▍         | 1/25 [10:02<4:01:08, 602.85s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746f2620> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746f7790> 

Generation:  2
Best root_mean_squared_error score: -3.1077589427459973
Generation:   8%|▊         | 2/25 [20:06<3:51:12, 603.17s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155466823c40> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a73a0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f04a30> 

Generation:  3
Best root_mean_squared_error score: -3.1077589427459973
Generation:  12%|█▏        | 3/25 [30:11<3:41:26, 603.92s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464330be0> 
 Input X contains NaN.
ExtraTreesRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/ensemble/_forest.py", line 377, in fit
    estimator._compute_missing_values_in_feature_mask(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/tree/_classes.py", line 214, in _compute_missing_values_in_feature_mask
    assert_all_finite(X, **common_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 213, in assert_all_finite
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
ExtraTreesRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464c83160> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f42d10> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554666cdcc0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f386a0> 

Generation:  4
Best root_mean_squared_error score: -3.1077589427459973
Generation:  16%|█▌        | 4/25 [40:14<3:31:19, 603.77s/it]Generation:  5
Best root_mean_squared_error score: -3.1077589427459973
Generation:  20%|██        | 5/25 [46:34<2:54:23, 523.17s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547472f430> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465fef820> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554517e7a00> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  6
Best root_mean_squared_error score: -3.1048117157655724
Generation:  24%|██▍       | 6/25 [52:54<2:30:10, 474.25s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464cbcd60> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464238310> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  7
Best root_mean_squared_error score: -3.1048117157655724
Generation:  28%|██▊       | 7/25 [58:52<2:10:52, 436.22s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746f4910> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554660e8070> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554641799c0> 

Generation:  8
Best root_mean_squared_error score: -3.1048117157655724
Generation:  32%|███▏      | 8/25 [1:08:56<2:18:45, 489.75s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547471f670> 

Generation:  9
Best root_mean_squared_error score: -3.100724986483723
Generation:  36%|███▌      | 9/25 [1:18:59<2:20:01, 525.12s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554747166b0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554677a8130> 

Generation:  10
Best root_mean_squared_error score: -3.100724986483723
Generation:  40%|████      | 10/25 [1:29:04<2:17:27, 549.83s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467d780a0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554646022f0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  11
Best root_mean_squared_error score: -3.100724986483723
Generation:  44%|████▍     | 11/25 [1:35:14<1:55:25, 494.70s/it]Generation:  12
Best root_mean_squared_error score: -3.100724986483723
Generation:  48%|████▊     | 12/25 [1:42:17<1:42:27, 472.86s/it]Generation:  13
Best root_mean_squared_error score: -3.100724986483723
Generation:  52%|█████▏    | 13/25 [1:48:58<1:30:15, 451.29s/it]Generation:  14
Best root_mean_squared_error score: -3.100724986483723
Generation:  56%|█████▌    | 14/25 [1:55:29<1:19:21, 432.87s/it]Generation:  15
Best root_mean_squared_error score: -3.100724986483723
Generation:  60%|██████    | 15/25 [2:01:32<1:08:39, 411.94s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554668233a0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155412302ef0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f20940> 

Generation:  16
Best root_mean_squared_error score: -3.100724986483723
Generation:  64%|██████▍   | 16/25 [2:11:36<1:10:27, 469.78s/it]Generation:  17
Best root_mean_squared_error score: -3.100724986483723
Generation:  68%|██████▊   | 17/25 [2:18:06<59:25, 445.75s/it]  Generation:  18
Best root_mean_squared_error score: -3.100724986483723
Generation:  72%|███████▏  | 18/25 [2:24:50<50:33, 433.32s/it]Generation:  19
Best root_mean_squared_error score: -3.100724986483723
Generation:  76%|███████▌  | 19/25 [2:31:15<41:51, 418.58s/it]Generation:  20
Best root_mean_squared_error score: -3.100724986483723
Generation:  80%|████████  | 20/25 [2:37:33<33:52, 406.54s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464eeb340> 

Generation:  21
Best root_mean_squared_error score: -3.100724986483723
Generation:  84%|████████▍ | 21/25 [2:47:39<31:05, 466.40s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464e3cac0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554517e7be0> 

Generation:  22
Best root_mean_squared_error score: -3.100724986483723
Generation:  88%|████████▊ | 22/25 [2:57:43<25:23, 507.81s/it]Generation:  23
Best root_mean_squared_error score: -3.100724986483723
Generation:  92%|█████████▏| 23/25 [3:04:20<15:48, 474.36s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464951090> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155452ba12a0> 

Generation:  24
Best root_mean_squared_error score: -3.100724986483723
Generation:  96%|█████████▌| 24/25 [3:14:24<08:33, 513.35s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474712380> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f20100> 

Generation:  25
Best root_mean_squared_error score: -3.100724986483723
Generation: 100%|██████████| 25/25 [3:24:29<00:00, 540.81s/it]Generation: 100%|██████████| 25/25 [3:24:29<00:00, 490.78s/it]
2024-10-04 15:28:15,618 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:42905' caused the cluster to lose scattered data, which can't be recovered: {'DataFrame-e30826a1b37cf21e477e41114aefff00', 'DataFrame-edee9f7d9e8d9a17dcfe6b777e771f31'} (stimulus_id='handle-worker-cleanup-1728080895.6188169')
Fitted
Pipeline(steps=[('knnimputer', KNNImputer(n_neighbors=43)),
                ('histgradientboostingregressor',
                 HistGradientBoostingRegressor(early_stopping=False,
                                               l2_regularization=3.0966774e-06,
                                               learning_rate=0.0351735005495,
                                               max_features=0.3869697026714,
                                               max_leaf_nodes=718,
                                               min_samples_leaf=68,
                                               tol=0.0001))])
transform worked
try transform
transform worked
score start
train score: {'explained_var': 0.837838384062751, 'r2': 0.837838384062751, 'rmse': 2.630798450711048}
test score: {'explained_var': 0.7690508310096195, 'r2': 0.769039722148173, 'rmse': 3.148112369273075}
original test score: {'explained_var': 0.8016785659457465, 'r2': 0.8016765605272795, 'rmse': 2.9172161011152267}
score end
1200
lvl
0.1
type
MCAR
num_run
3
reg_full
finished
all finished
full run takes
16.995142738686667
hours
DONE
