Run: 60
/cm/local/apps/slurm/var/spool/job968898/slurm_script: line 26: 
pip install -e tpot2
pip install -r tpot2/ImputerExperiments/requirements_.txt
: No such file or directory
RunStart
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 5 days ago.
starting loops
../data/r/215/215.pkl
working on 
../data/r/215/reg_full_MNAR_0.5_3
3.643634796142578
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2024-09-23 13:48:11,954] A new study created in memory with name: no-name-c90ccf86-2d86-4582-980c-4db5389f6433
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
[I 2024-09-23 13:48:13,107] Trial 6 finished with value: 0.4612467675575405 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 6 with value: 0.4612467675575405.
running
[I 2024-09-23 13:48:13,500] Trial 14 finished with value: 0.4612467675575405 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 6 with value: 0.4612467675575405.
running
[I 2024-09-23 13:48:13,757] Trial 15 finished with value: 0.4612467675575405 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 6 with value: 0.4612467675575405.
running
[I 2024-09-23 13:48:27,898] Trial 18 finished with value: 0.3596673567504632 and parameters: {'model_name': 'VAE', 'batch_size': 238, 'iterations': 1, 'learning_rate': 0.050365403982715905, 'p_miss': 0.29766455329827446}. Best is trial 18 with value: 0.3596673567504632.
running
[I 2024-09-23 13:48:28,604] Trial 19 finished with value: 0.4612467675575405 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 18 with value: 0.3596673567504632.
running
[I 2024-09-23 13:48:32,273] Trial 20 finished with value: 0.30279030839673193 and parameters: {'model_name': 'VAE', 'batch_size': 2, 'iterations': 1, 'learning_rate': 0.0006226675611758499, 'p_miss': 0.1564613972162826}. Best is trial 20 with value: 0.30279030839673193.
running
[I 2024-09-23 13:48:36,188] Trial 5 finished with value: 0.3524221237396511 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 51, 'weights': 'distance'}. Best is trial 20 with value: 0.30279030839673193.
running
[I 2024-09-23 13:48:42,945] Trial 11 finished with value: 0.34607165605380275 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 7674, 'weights': 'uniform'}. Best is trial 20 with value: 0.30279030839673193.
running
[I 2024-09-23 13:48:43,167] Trial 22 finished with value: 0.3045855184187148 and parameters: {'model_name': 'VAE', 'batch_size': 22, 'iterations': 1, 'learning_rate': 0.025192478250185776, 'p_miss': 0.0692650640900457}. Best is trial 20 with value: 0.30279030839673193.
running
[I 2024-09-23 13:48:43,747] Trial 3 finished with value: 0.3464060352183054 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 11319, 'weights': 'uniform'}. Best is trial 20 with value: 0.30279030839673193.
running
[I 2024-09-23 13:48:47,427] Trial 8 finished with value: 0.36132217633896707 and parameters: {'model_name': 'VAE', 'batch_size': 67, 'iterations': 7, 'learning_rate': 0.018478095759991636, 'p_miss': 0.19645170887877328}. Best is trial 20 with value: 0.30279030839673193.
running
[I 2024-09-23 13:48:48,543] Trial 0 finished with value: 0.34612542577976363 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 21038, 'weights': 'uniform'}. Best is trial 20 with value: 0.30279030839673193.
running
[I 2024-09-23 13:48:52,951] Trial 16 finished with value: 0.35205039278630246 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 28764, 'weights': 'distance'}. Best is trial 20 with value: 0.30279030839673193.
running
[I 2024-09-23 13:48:54,596] Trial 24 finished with value: 0.4611832401852391 and parameters: {'model_name': 'GAIN', 'batch_size': 244, 'hint_rate': 0.8961881598344967, 'alpha': 64, 'iterations': 4, 'learning_rate': 0.08602169842552822, 'p_miss': 0.0184722986675777}. Best is trial 20 with value: 0.30279030839673193.
running
[I 2024-09-23 13:49:00,995] Trial 21 finished with value: 0.3456388765606619 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 31406, 'weights': 'uniform'}. Best is trial 20 with value: 0.30279030839673193.
running
[I 2024-09-23 13:49:20,293] Trial 4 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 2, 'hint_rate': 0.27751348844498847, 'alpha': 70, 'iterations': 447, 'learning_rate': 0.00480225873817081, 'p_miss': 0.2561009339107458}. Best is trial 20 with value: 0.30279030839673193.
running
[I 2024-09-23 13:49:34,830] Trial 31 finished with value: 0.34101937003092686 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'constant', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 20 with value: 0.30279030839673193.
running
[I 2024-09-23 13:49:36,836] Trial 30 finished with value: 0.3410991281390791 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 8, 'imputation_order': 'roman'}. Best is trial 20 with value: 0.30279030839673193.
running
[I 2024-09-23 13:49:37,296] Trial 32 finished with value: 0.30495043410675277 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 1, 'learning_rate': 0.0002492031512409283, 'p_miss': 0.08345746260622972}. Best is trial 20 with value: 0.30279030839673193.
running
[I 2024-09-23 13:50:16,323] Trial 34 finished with value: 0.30182911969465265 and parameters: {'model_name': 'VAE', 'batch_size': 10, 'iterations': 41, 'learning_rate': 0.0005836286969507097, 'p_miss': 0.1244653774520027}. Best is trial 34 with value: 0.30182911969465265.
running
[I 2024-09-23 13:50:21,873] Trial 29 finished with value: 0.43669874177683443 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'median', 'n_nearest_features': 8, 'imputation_order': 'random', 'sample_posterior': True}. Best is trial 34 with value: 0.30182911969465265.
running
[I 2024-09-23 13:51:00,013] Trial 17 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 2, 'hint_rate': 0.641903202309228, 'alpha': 23, 'iterations': 1155, 'learning_rate': 0.0006925895900044155, 'p_miss': 0.20852430384768308}. Best is trial 34 with value: 0.30182911969465265.
running
[I 2024-09-23 13:54:09,648] Trial 37 finished with value: 0.30749869135230196 and parameters: {'model_name': 'VAE', 'batch_size': 18, 'iterations': 63, 'learning_rate': 0.0010760138746132794, 'p_miss': 0.11338562850674527}. Best is trial 34 with value: 0.30182911969465265.
running
[I 2024-09-23 13:55:02,453] Trial 38 finished with value: 0.3017240775213486 and parameters: {'model_name': 'VAE', 'batch_size': 13, 'iterations': 17, 'learning_rate': 0.0017619357731808816, 'p_miss': 0.12790677863469102}. Best is trial 38 with value: 0.3017240775213486.
running
[I 2024-09-23 13:57:19,064] Trial 39 finished with value: 0.305970538028559 and parameters: {'model_name': 'VAE', 'batch_size': 8, 'iterations': 49, 'learning_rate': 0.0013988292732344853, 'p_miss': 0.14691790135669244}. Best is trial 38 with value: 0.3017240775213486.
running
[I 2024-09-23 13:57:46,437] Trial 28 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.7803809114260929, 'alpha': 24, 'iterations': 2539, 'learning_rate': 0.00026834733245309673, 'p_miss': 0.027104471049124917}. Best is trial 38 with value: 0.3017240775213486.
running
[I 2024-09-23 13:58:17,849] Trial 41 finished with value: 0.3037679686293835 and parameters: {'model_name': 'VAE', 'batch_size': 7, 'iterations': 10, 'learning_rate': 0.004221496553954347, 'p_miss': 0.15118120541560184}. Best is trial 38 with value: 0.3017240775213486.
running
[I 2024-09-23 13:58:30,158] Trial 40 finished with value: 0.3023103015920564 and parameters: {'model_name': 'VAE', 'batch_size': 8, 'iterations': 21, 'learning_rate': 0.00013324965441267983, 'p_miss': 0.15409529470498917}. Best is trial 38 with value: 0.3017240775213486.
running
[I 2024-09-23 13:59:28,807] Trial 26 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.6302416513662485, 'alpha': 24, 'iterations': 2954, 'learning_rate': 0.00027540038934142344, 'p_miss': 0.025897923989035287}. Best is trial 38 with value: 0.3017240775213486.
running
[I 2024-09-23 13:59:33,124] Trial 10 finished with value: 0.4610527094651216 and parameters: {'model_name': 'GAIN', 'batch_size': 659, 'hint_rate': 0.6408666722779727, 'alpha': 69, 'iterations': 480, 'learning_rate': 0.00042341912869591815, 'p_miss': 0.24307727174357957}. Best is trial 38 with value: 0.3017240775213486.
running
[I 2024-09-23 13:59:47,682] Trial 43 finished with value: 0.3017887617838588 and parameters: {'model_name': 'VAE', 'batch_size': 60, 'iterations': 25, 'learning_rate': 0.00011679006726442306, 'p_miss': 0.11200732107273838}. Best is trial 38 with value: 0.3017240775213486.
running
[I 2024-09-23 14:00:19,326] Trial 45 finished with value: 0.3045836769376449 and parameters: {'model_name': 'VAE', 'batch_size': 8, 'iterations': 17, 'learning_rate': 0.00011143985912145673, 'p_miss': 0.1145931186058155}. Best is trial 38 with value: 0.3017240775213486.
running
[I 2024-09-23 14:00:47,996] Trial 44 finished with value: 0.30383707110322905 and parameters: {'model_name': 'VAE', 'batch_size': 81, 'iterations': 24, 'learning_rate': 0.00010702996928183215, 'p_miss': 0.1094116281148024}. Best is trial 38 with value: 0.3017240775213486.
running
[I 2024-09-23 14:01:17,843] Trial 46 finished with value: 0.30324762990664345 and parameters: {'model_name': 'VAE', 'batch_size': 55, 'iterations': 27, 'learning_rate': 0.00010212868448298488, 'p_miss': 0.11687582930616665}. Best is trial 38 with value: 0.3017240775213486.
running
[I 2024-09-23 14:01:37,491] Trial 13 finished with value: 0.34916221936925834 and parameters: {'model_name': 'VAE', 'batch_size': 122, 'iterations': 329, 'learning_rate': 0.002077151633341979, 'p_miss': 0.08610948101569607}. Best is trial 38 with value: 0.3017240775213486.
running
[I 2024-09-23 14:01:57,033] Trial 47 finished with value: 0.30312295093800706 and parameters: {'model_name': 'VAE', 'batch_size': 52, 'iterations': 29, 'learning_rate': 0.00011688509092634129, 'p_miss': 0.11215082752818953}. Best is trial 38 with value: 0.3017240775213486.
running
[I 2024-09-23 14:03:49,238] Trial 23 finished with value: 0.460931622202425 and parameters: {'model_name': 'GAIN', 'batch_size': 4, 'hint_rate': 0.9123621670943759, 'alpha': 13, 'iterations': 776, 'learning_rate': 0.028108626432298264, 'p_miss': 0.25254024744853976}. Best is trial 38 with value: 0.3017240775213486.
running
[I 2024-09-23 14:04:31,574] Trial 49 finished with value: 0.3083208614646193 and parameters: {'model_name': 'VAE', 'batch_size': 14, 'iterations': 61, 'learning_rate': 0.0014409038888550203, 'p_miss': 0.17848769226088376}. Best is trial 38 with value: 0.3017240775213486.
running
[I 2024-09-23 14:07:45,003] Trial 50 finished with value: 0.30365423966204985 and parameters: {'model_name': 'VAE', 'batch_size': 14, 'iterations': 136, 'learning_rate': 0.00019311360890272915, 'p_miss': 0.17599155851325327}. Best is trial 38 with value: 0.3017240775213486.
running
[I 2024-09-23 14:08:23,220] Trial 42 finished with value: 0.3005371537744183 and parameters: {'model_name': 'VAE', 'batch_size': 65, 'iterations': 228, 'learning_rate': 0.0001147771937734938, 'p_miss': 0.1184382217270188}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:08:39,967] Trial 51 finished with value: 0.3017054887616316 and parameters: {'model_name': 'VAE', 'batch_size': 13, 'iterations': 127, 'learning_rate': 0.0002016102498856369, 'p_miss': 0.1741537444819651}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:09:41,259] Trial 52 finished with value: 0.30270408095485535 and parameters: {'model_name': 'VAE', 'batch_size': 15, 'iterations': 101, 'learning_rate': 0.00021803030873527167, 'p_miss': 0.17997496452692174}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:10:09,259] Trial 48 finished with value: 0.3481997594953352 and parameters: {'model_name': 'VAE', 'batch_size': 54, 'iterations': 157, 'learning_rate': 0.0020940296864482635, 'p_miss': 0.17777683265845007}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:10:21,456] Trial 58 finished with value: 0.30260171855299256 and parameters: {'model_name': 'VAE', 'batch_size': 30, 'iterations': 3, 'learning_rate': 0.00040583197526113097, 'p_miss': 0.13622260402688102}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:12:59,320] Trial 53 finished with value: 0.3510017294081938 and parameters: {'model_name': 'VAE', 'batch_size': 35, 'iterations': 147, 'learning_rate': 0.007725459786746561, 'p_miss': 0.1397959164455044}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:13:36,503] Trial 60 finished with value: 0.35204445079652064 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 20572, 'weights': 'distance'}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:13:37,278] Trial 61 finished with value: 0.3456388765606619 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:14:30,460] Trial 54 finished with value: 0.30757862958328985 and parameters: {'model_name': 'VAE', 'batch_size': 29, 'iterations': 159, 'learning_rate': 0.00048272256169219963, 'p_miss': 0.13723454739292282}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:15:27,522] Trial 55 finished with value: 0.34903157767350146 and parameters: {'model_name': 'VAE', 'batch_size': 116, 'iterations': 138, 'learning_rate': 0.0075241328009002986, 'p_miss': 0.05829435271006193}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:16:54,577] Trial 64 finished with value: 0.37211634059216514 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'mean', 'n_nearest_features': 1, 'imputation_order': 'ascending'}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:16:55,597] Trial 65 finished with value: 0.4612467675575405 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:17:25,401] Trial 56 finished with value: 0.31057665643276133 and parameters: {'model_name': 'VAE', 'batch_size': 35, 'iterations': 151, 'learning_rate': 0.0004296347969469115, 'p_miss': 0.13232654062377303}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:17:31,262] Trial 66 finished with value: 0.3049453864593919 and parameters: {'model_name': 'VAE', 'batch_size': 5, 'iterations': 12, 'learning_rate': 0.00015457325433617647, 'p_miss': 0.09384024883334358}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:17:41,202] Trial 57 finished with value: 0.3101936445663544 and parameters: {'model_name': 'VAE', 'batch_size': 33, 'iterations': 135, 'learning_rate': 0.00044746465122449144, 'p_miss': 0.13025453666635636}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:18:07,058] Trial 67 finished with value: 0.3043269861175493 and parameters: {'model_name': 'VAE', 'batch_size': 5, 'iterations': 12, 'learning_rate': 0.00016513394847034356, 'p_miss': 0.09703179477671932}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:18:27,994] Trial 70 finished with value: 0.35204473066019615 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 162, 'weights': 'distance'}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:22:31,622] Trial 59 finished with value: 0.3270536248208994 and parameters: {'model_name': 'VAE', 'batch_size': 31, 'iterations': 251, 'learning_rate': 0.00056669174852423, 'p_miss': 0.06092404306211699}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:24:32,086] Trial 72 finished with value: 0.3069757852020155 and parameters: {'model_name': 'VAE', 'batch_size': 10, 'iterations': 38, 'learning_rate': 0.00015930233036334242, 'p_miss': 0.212225422599488}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:24:57,999] Trial 73 finished with value: 0.3024658581273239 and parameters: {'model_name': 'VAE', 'batch_size': 169, 'iterations': 6, 'learning_rate': 0.0008175657040132206, 'p_miss': 0.16087731504898128}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:26:12,433] Trial 62 finished with value: 0.33415795051335245 and parameters: {'model_name': 'VAE', 'batch_size': 113, 'iterations': 235, 'learning_rate': 0.0005148837549723513, 'p_miss': 0.05515242996571067}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:26:13,292] Trial 75 finished with value: 0.4612467675575405 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:26:31,630] Trial 76 finished with value: 0.305117025726256 and parameters: {'model_name': 'VAE', 'batch_size': 214, 'iterations': 5, 'learning_rate': 0.0008384610224701466, 'p_miss': 0.1649954955244997}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:26:57,889] Trial 77 finished with value: 0.304420899884971 and parameters: {'model_name': 'VAE', 'batch_size': 209, 'iterations': 7, 'learning_rate': 0.0003222872122146051, 'p_miss': 0.19969080601794892}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:27:18,105] Trial 78 finished with value: 0.3044423454004783 and parameters: {'model_name': 'VAE', 'batch_size': 603, 'iterations': 2, 'learning_rate': 0.0021875469217178117, 'p_miss': 0.15512953570536606}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:28:25,717] Trial 79 finished with value: 0.3038137413339762 and parameters: {'model_name': 'VAE', 'batch_size': 20, 'iterations': 18, 'learning_rate': 0.0008698024403499, 'p_miss': 0.22880058419848764}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:31:08,303] Trial 63 finished with value: 0.3069327058165287 and parameters: {'model_name': 'VAE', 'batch_size': 133, 'iterations': 305, 'learning_rate': 0.0001797657896759875, 'p_miss': 0.06296897113349179}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:32:39,510] Trial 68 finished with value: 0.3030136443257564 and parameters: {'model_name': 'VAE', 'batch_size': 10, 'iterations': 293, 'learning_rate': 0.00016518569905581498, 'p_miss': 0.20910614723837917}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:36:36,605] Trial 69 finished with value: 0.3060786960715054 and parameters: {'model_name': 'VAE', 'batch_size': 11, 'iterations': 350, 'learning_rate': 0.00015171069338654832, 'p_miss': 0.21285681128645226}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:38:12,370] Trial 80 finished with value: 0.4620627896151424 and parameters: {'model_name': 'GAIN', 'batch_size': 10, 'hint_rate': 0.01300152252781378, 'alpha': 97, 'iterations': 425, 'learning_rate': 0.00014851595940696782, 'p_miss': 0.16584406654086237}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:38:19,091] Trial 71 finished with value: 0.30368173424292 and parameters: {'model_name': 'VAE', 'batch_size': 10, 'iterations': 352, 'learning_rate': 0.0001604543530968469, 'p_miss': 0.162690902527976}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:38:47,812] Trial 84 finished with value: 0.3520503780615918 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 24789, 'weights': 'distance'}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:39:49,492] Trial 25 finished with value: 0.3481955680299632 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 8, 'imputation_order': 'arabic'}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:39:59,759] Trial 87 finished with value: 0.30260935029704783 and parameters: {'model_name': 'VAE', 'batch_size': 22, 'iterations': 3, 'learning_rate': 0.00031373851166602876, 'p_miss': 0.12385898338986998}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:40:07,022] Trial 88 finished with value: 0.30248972627223425 and parameters: {'model_name': 'VAE', 'batch_size': 91, 'iterations': 2, 'learning_rate': 0.0003486281852293924, 'p_miss': 0.14312631639638926}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:44:58,535] Trial 81 finished with value: 0.46117421266107506 and parameters: {'model_name': 'GAIN', 'batch_size': 11, 'hint_rate': 0.045507278318641986, 'alpha': 95, 'iterations': 590, 'learning_rate': 0.0003352242621291973, 'p_miss': 0.16341793186426562}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:47:45,149] Trial 90 finished with value: 0.30231025978513343 and parameters: {'model_name': 'VAE', 'batch_size': 388, 'iterations': 42, 'learning_rate': 0.00022597731671026672, 'p_miss': 0.14925281452393221}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:49:55,204] Trial 74 finished with value: 0.3234015005836825 and parameters: {'model_name': 'VAE', 'batch_size': 10, 'iterations': 491, 'learning_rate': 0.0002616418346229865, 'p_miss': 0.20074829436172295}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:50:54,697] Trial 92 finished with value: 0.36922795191786584 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'constant', 'n_nearest_features': 3, 'imputation_order': 'descending'}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:51:39,895] Trial 91 finished with value: 0.3196782419166224 and parameters: {'model_name': 'VAE', 'batch_size': 401, 'iterations': 41, 'learning_rate': 0.0013900148488546979, 'p_miss': 0.10150807843425913}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:53:54,446] Trial 82 finished with value: 0.4611252541375294 and parameters: {'model_name': 'GAIN', 'batch_size': 339, 'hint_rate': 0.08360161047363301, 'alpha': 97, 'iterations': 813, 'learning_rate': 0.0013031855233602652, 'p_miss': 0.16784343101356985}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:54:57,873] Trial 93 finished with value: 0.3216789354416845 and parameters: {'model_name': 'VAE', 'batch_size': 485, 'iterations': 47, 'learning_rate': 0.0016211398320903935, 'p_miss': 0.1034283434169137}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:57:22,983] Trial 83 finished with value: 0.4617713830393571 and parameters: {'model_name': 'GAIN', 'batch_size': 302, 'hint_rate': 0.047190790388376425, 'alpha': 91, 'iterations': 775, 'learning_rate': 0.00031915615683190794, 'p_miss': 0.16521444678739006}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:58:34,543] Trial 94 finished with value: 0.35005321478076956 and parameters: {'model_name': 'VAE', 'batch_size': 351, 'iterations': 84, 'learning_rate': 0.0031559545408864696, 'p_miss': 0.12372526673491675}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 14:59:27,160] Trial 97 finished with value: 0.3010899225586593 and parameters: {'model_name': 'VAE', 'batch_size': 858, 'iterations': 24, 'learning_rate': 0.0006669757086188758, 'p_miss': 0.148356522906561}. Best is trial 42 with value: 0.3005371537744183.
running
[I 2024-09-23 15:00:39,857] Trial 98 finished with value: 0.30036102385259983 and parameters: {'model_name': 'VAE', 'batch_size': 860, 'iterations': 26, 'learning_rate': 0.0002307120879241567, 'p_miss': 0.14438912052916816}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:01:26,682] Trial 99 finished with value: 0.30186956218133 and parameters: {'model_name': 'VAE', 'batch_size': 739, 'iterations': 19, 'learning_rate': 0.000747668454406429, 'p_miss': 0.18919413353080472}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:02:10,948] Trial 100 finished with value: 0.30287046618074537 and parameters: {'model_name': 'VAE', 'batch_size': 844, 'iterations': 20, 'learning_rate': 0.00021702968088993532, 'p_miss': 0.14988028023500516}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:02:47,428] Trial 85 finished with value: 0.3443611458225416 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 2, 'imputation_order': 'descending'}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:03:06,098] Trial 86 finished with value: 0.34389518963561444 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 2, 'imputation_order': 'arabic'}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:03:12,408] Trial 96 finished with value: 0.30083971810929366 and parameters: {'model_name': 'VAE', 'batch_size': 834, 'iterations': 79, 'learning_rate': 0.00024131632391487094, 'p_miss': 0.14929617818890975}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:04:15,030] Trial 101 finished with value: 0.30356715309076876 and parameters: {'model_name': 'VAE', 'batch_size': 950, 'iterations': 29, 'learning_rate': 0.00021279882810133223, 'p_miss': 0.29075663332108204}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:05:27,274] Trial 102 finished with value: 0.30124469266722703 and parameters: {'model_name': 'VAE', 'batch_size': 961, 'iterations': 29, 'learning_rate': 0.0006957059807049414, 'p_miss': 0.12299054646117655}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:06:15,165] Trial 105 finished with value: 0.30264502969303797 and parameters: {'model_name': 'VAE', 'batch_size': 822, 'iterations': 30, 'learning_rate': 0.0006576180585840502, 'p_miss': 0.29723149555807693}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:06:46,520] Trial 103 finished with value: 0.3018271374339007 and parameters: {'model_name': 'VAE', 'batch_size': 834, 'iterations': 34, 'learning_rate': 0.0006087003713093815, 'p_miss': 0.19091085300010713}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:07:06,074] Trial 104 finished with value: 0.30569421063578595 and parameters: {'model_name': 'VAE', 'batch_size': 931, 'iterations': 33, 'learning_rate': 0.0010656888643278365, 'p_miss': 0.12360333803070526}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:10:16,764] Trial 106 finished with value: 0.3063321041586634 and parameters: {'model_name': 'VAE', 'batch_size': 656, 'iterations': 67, 'learning_rate': 0.0006461771398198705, 'p_miss': 0.1909497393189442}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:10:17,526] Trial 111 finished with value: 0.3456388765606619 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:11:13,422] Trial 112 finished with value: 0.3022691496278798 and parameters: {'model_name': 'VAE', 'batch_size': 559, 'iterations': 13, 'learning_rate': 0.0001245186529459086, 'p_miss': 0.08057191814938333}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:11:41,247] Trial 113 finished with value: 0.3464641402389542 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 13587, 'weights': 'uniform'}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:11:51,001] Trial 107 finished with value: 0.3070255239054435 and parameters: {'model_name': 'VAE', 'batch_size': 711, 'iterations': 73, 'learning_rate': 0.0006432400966398285, 'p_miss': 0.18845147299356818}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:11:54,367] Trial 110 finished with value: 0.3038394674734261 and parameters: {'model_name': 'VAE', 'batch_size': 578, 'iterations': 62, 'learning_rate': 0.00011913179883252947, 'p_miss': 0.08057187079989872}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:11:56,277] Trial 108 finished with value: 0.3186608615093899 and parameters: {'model_name': 'VAE', 'batch_size': 658, 'iterations': 69, 'learning_rate': 0.00112830587969977, 'p_miss': 0.12504259578362664}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:13:35,158] Trial 117 finished with value: 0.3041661996628849 and parameters: {'model_name': 'VAE', 'batch_size': 729, 'iterations': 21, 'learning_rate': 0.0004321051669658194, 'p_miss': 0.1156850072220787}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:13:46,996] Trial 116 finished with value: 0.3027481092186103 and parameters: {'model_name': 'VAE', 'batch_size': 732, 'iterations': 22, 'learning_rate': 0.0010090250006143623, 'p_miss': 0.13107853103412548}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:13:51,382] Trial 109 finished with value: 0.3284755311265969 and parameters: {'model_name': 'VAE', 'batch_size': 560, 'iterations': 76, 'learning_rate': 0.0009767976954702202, 'p_miss': 0.12478902762389889}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:14:44,204] Trial 118 finished with value: 0.30339800354661495 and parameters: {'model_name': 'VAE', 'batch_size': 479, 'iterations': 15, 'learning_rate': 0.000515698744190883, 'p_miss': 0.14077435052308063}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:14:55,956] Trial 120 finished with value: 0.30366250546681156 and parameters: {'model_name': 'VAE', 'batch_size': 999, 'iterations': 9, 'learning_rate': 0.0007934230285618167, 'p_miss': 0.14151793928324005}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:15:15,629] Trial 121 finished with value: 0.3025958911977981 and parameters: {'model_name': 'VAE', 'batch_size': 16, 'iterations': 10, 'learning_rate': 0.00010207456205994709, 'p_miss': 0.18502871930915388}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:16:52,377] Trial 12 finished with value: 0.3505956853147977 and parameters: {'model_name': 'VAE', 'batch_size': 178, 'iterations': 1505, 'learning_rate': 0.0994942771860343, 'p_miss': 0.22054229268020906}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:19:23,833] Trial 114 finished with value: 0.3324891095801057 and parameters: {'model_name': 'VAE', 'batch_size': 467, 'iterations': 88, 'learning_rate': 0.0010134376074830782, 'p_miss': 0.12935571860786912}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:19:37,773] Trial 115 finished with value: 0.3024788633238287 and parameters: {'model_name': 'VAE', 'batch_size': 516, 'iterations': 105, 'learning_rate': 0.00010263819997085905, 'p_miss': 0.11673857980837499}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:19:59,735] Trial 119 finished with value: 0.3129455774470638 and parameters: {'model_name': 'VAE', 'batch_size': 473, 'iterations': 102, 'learning_rate': 0.000754515251284313, 'p_miss': 0.14152061422995907}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:20:13,173] Trial 2 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 18, 'hint_rate': 0.9325904590060171, 'alpha': 74, 'iterations': 9859, 'learning_rate': 0.0022380427931129356, 'p_miss': 0.04566492348364927}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:20:36,788] Trial 123 finished with value: 0.32911321114841136 and parameters: {'model_name': 'VAE', 'batch_size': 2, 'iterations': 99, 'learning_rate': 0.0018068681047951989, 'p_miss': 0.107824269227834}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:20:57,535] Trial 128 finished with value: 0.30383346285817514 and parameters: {'model_name': 'VAE', 'batch_size': 6, 'iterations': 15, 'learning_rate': 0.00012954081415316184, 'p_miss': 0.1723760301842626}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:21:49,362] Trial 122 finished with value: 0.30300622306156944 and parameters: {'model_name': 'VAE', 'batch_size': 14, 'iterations': 97, 'learning_rate': 0.00039149617220015037, 'p_miss': 0.18393736090885}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:22:01,476] Trial 127 finished with value: 0.30350581106486574 and parameters: {'model_name': 'VAE', 'batch_size': 789, 'iterations': 25, 'learning_rate': 0.00013556900111441736, 'p_miss': 0.10852488120586157}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:22:20,910] Trial 89 finished with value: 0.34456969214272404 and parameters: {'model_name': 'VAE', 'batch_size': 77, 'iterations': 652, 'learning_rate': 0.00024082881252928098, 'p_miss': 0.14562991178700146}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:22:22,155] Trial 133 finished with value: 0.4612467675575405 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:23:01,747] Trial 132 finished with value: 0.3019918498750441 and parameters: {'model_name': 'VAE', 'batch_size': 42, 'iterations': 13, 'learning_rate': 0.002690991165941652, 'p_miss': 0.09133927242687157}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:24:54,383] Trial 129 finished with value: 0.3024415421114063 and parameters: {'model_name': 'VAE', 'batch_size': 826, 'iterations': 54, 'learning_rate': 0.00014104181796743817, 'p_miss': 0.08896601714749695}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:25:03,990] Trial 134 finished with value: 0.30366319327898894 and parameters: {'model_name': 'VAE', 'batch_size': 46, 'iterations': 51, 'learning_rate': 0.0002841044882038098, 'p_miss': 0.15460954301699198}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:25:39,477] Trial 136 finished with value: 0.3031835279677879 and parameters: {'model_name': 'VAE', 'batch_size': 51, 'iterations': 13, 'learning_rate': 0.002527349219718614, 'p_miss': 0.08491798293034354}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:25:58,288] Trial 137 finished with value: 0.3035807677813334 and parameters: {'model_name': 'VAE', 'batch_size': 44, 'iterations': 15, 'learning_rate': 0.00312655974564538, 'p_miss': 0.07874503231343832}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:26:26,179] Trial 135 finished with value: 0.3488080047799459 and parameters: {'model_name': 'VAE', 'batch_size': 47, 'iterations': 55, 'learning_rate': 0.0036222819783373887, 'p_miss': 0.09024062055213411}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:27:55,625] Trial 138 finished with value: 0.3389709071708282 and parameters: {'model_name': 'VAE', 'batch_size': 63, 'iterations': 35, 'learning_rate': 0.004172880541843473, 'p_miss': 0.09180575341884474}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:28:08,226] Trial 139 finished with value: 0.3029858928176534 and parameters: {'model_name': 'VAE', 'batch_size': 65, 'iterations': 35, 'learning_rate': 0.00018085691880596384, 'p_miss': 0.0751723300057}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:28:25,729] Trial 141 finished with value: 0.35195713243160337 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 6519, 'weights': 'distance'}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:28:37,026] Trial 142 finished with value: 0.3519494117811736 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5740, 'weights': 'distance'}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:30:05,453] Trial 126 finished with value: 0.3015826884747278 and parameters: {'model_name': 'VAE', 'batch_size': 44, 'iterations': 209, 'learning_rate': 0.00018816205730772, 'p_miss': 0.04054276479988871}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:31:08,389] Trial 125 finished with value: 0.30603579964613015 and parameters: {'model_name': 'VAE', 'batch_size': 46, 'iterations': 203, 'learning_rate': 0.00027668866946170404, 'p_miss': 0.1774863955697362}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:32:03,101] Trial 146 finished with value: 0.30127226015804237 and parameters: {'model_name': 'VAE', 'batch_size': 26, 'iterations': 18, 'learning_rate': 0.00019059040918877857, 'p_miss': 0.06926044261376181}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:32:57,348] Trial 130 finished with value: 0.30235095690832153 and parameters: {'model_name': 'VAE', 'batch_size': 43, 'iterations': 198, 'learning_rate': 0.00013217629282951787, 'p_miss': 0.033374525161213656}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:34:24,595] Trial 148 finished with value: 0.302209989663373 and parameters: {'model_name': 'VAE', 'batch_size': 23, 'iterations': 24, 'learning_rate': 0.00019030523136079095, 'p_miss': 0.100973513792426}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:35:31,421] Trial 149 finished with value: 0.3026481882481418 and parameters: {'model_name': 'VAE', 'batch_size': 27, 'iterations': 18, 'learning_rate': 0.00053860574929461, 'p_miss': 0.050900747489903274}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:36:11,011] Trial 150 finished with value: 0.30219558621398046 and parameters: {'model_name': 'VAE', 'batch_size': 26, 'iterations': 9, 'learning_rate': 0.00251271108762058, 'p_miss': 0.06779007189089949}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:37:10,099] Trial 140 finished with value: 0.30278127114487374 and parameters: {'model_name': 'VAE', 'batch_size': 26, 'iterations': 209, 'learning_rate': 0.00018179390497775427, 'p_miss': 0.0701050495351397}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:37:41,096] Trial 151 finished with value: 0.303328723783815 and parameters: {'model_name': 'VAE', 'batch_size': 18, 'iterations': 28, 'learning_rate': 0.0003625358194103072, 'p_miss': 0.04291597535992156}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:38:54,778] Trial 152 finished with value: 0.3015177492886891 and parameters: {'model_name': 'VAE', 'batch_size': 36, 'iterations': 27, 'learning_rate': 0.0003861827691858694, 'p_miss': 0.04490914992989658}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:39:16,529] Trial 144 finished with value: 0.3484942596100895 and parameters: {'model_name': 'VAE', 'batch_size': 27, 'iterations': 196, 'learning_rate': 0.002680662574443953, 'p_miss': 0.0989840088538701}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:39:20,907] Trial 145 finished with value: 0.35030937900201536 and parameters: {'model_name': 'VAE', 'batch_size': 19, 'iterations': 172, 'learning_rate': 0.0024239447148319757, 'p_miss': 0.04088493561569453}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:39:28,495] Trial 153 finished with value: 0.301718632964651 and parameters: {'model_name': 'VAE', 'batch_size': 36, 'iterations': 40, 'learning_rate': 0.00058395744452502, 'p_miss': 0.19552337442588802}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:39:42,618] Trial 131 finished with value: 0.3029690334579961 and parameters: {'model_name': 'VAE', 'batch_size': 815, 'iterations': 202, 'learning_rate': 0.00012985836493133133, 'p_miss': 0.09063643490454809}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:39:43,579] Trial 143 finished with value: 0.34958556771423144 and parameters: {'model_name': 'VAE', 'batch_size': 25, 'iterations': 214, 'learning_rate': 0.0057709192187532, 'p_miss': 0.045420394138261586}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:39:49,866] Trial 147 finished with value: 0.30226119688203623 and parameters: {'model_name': 'VAE', 'batch_size': 26, 'iterations': 188, 'learning_rate': 0.00019338241483584864, 'p_miss': 0.0383668563885744}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:39:57,094] Trial 154 finished with value: 0.3022730413174427 and parameters: {'model_name': 'VAE', 'batch_size': 12, 'iterations': 43, 'learning_rate': 0.0004653088969474823, 'p_miss': 0.03805862583542185}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:39:58,169] Trial 156 finished with value: 0.3008548786395374 and parameters: {'model_name': 'VAE', 'batch_size': 39, 'iterations': 40, 'learning_rate': 0.0005544913549961417, 'p_miss': 0.029411383215296186}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:40:01,179] Trial 157 finished with value: 0.3024431987118012 and parameters: {'model_name': 'VAE', 'batch_size': 38, 'iterations': 40, 'learning_rate': 0.0005862265882710359, 'p_miss': 0.037178803787151375}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:40:02,284] Trial 155 finished with value: 0.3420706538207032 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 5, 'imputation_order': 'random', 'sample_posterior': False}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:40:03,015] Trial 164 finished with value: 0.4612467675575405 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:40:09,271] Trial 159 finished with value: 0.30253748971955385 and parameters: {'model_name': 'VAE', 'batch_size': 36, 'iterations': 25, 'learning_rate': 0.0005974965579062625, 'p_miss': 0.013935129920992866}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:40:14,109] Trial 165 finished with value: 0.4609813164045601 and parameters: {'model_name': 'GAIN', 'batch_size': 33, 'hint_rate': 0.363533469869055, 'alpha': 45, 'iterations': 26, 'learning_rate': 0.00024686424014866095, 'p_miss': 0.015195445546849172}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:40:14,854] Trial 162 finished with value: 0.46157961456549057 and parameters: {'model_name': 'GAIN', 'batch_size': 39, 'hint_rate': 0.3438442724051757, 'alpha': 41, 'iterations': 37, 'learning_rate': 0.0005831306779825508, 'p_miss': 0.01827626270638777}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:40:16,827] Trial 158 finished with value: 0.30257817951535915 and parameters: {'model_name': 'VAE', 'batch_size': 8, 'iterations': 41, 'learning_rate': 0.00048194085560684447, 'p_miss': 0.026644526164254976}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:40:33,440] Trial 160 finished with value: 0.3021033052400754 and parameters: {'model_name': 'VAE', 'batch_size': 37, 'iterations': 42, 'learning_rate': 0.00047013911095527736, 'p_miss': 0.020324634807256384}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:40:34,122] Trial 167 finished with value: 0.3025447698163798 and parameters: {'model_name': 'VAE', 'batch_size': 61, 'iterations': 18, 'learning_rate': 0.00050311265248741, 'p_miss': 0.024787718626463777}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:40:47,802] Trial 161 finished with value: 0.34180136549997353 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 5, 'imputation_order': 'ascending', 'sample_posterior': False}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:40:50,945] Trial 170 finished with value: 0.30271098769752897 and parameters: {'model_name': 'VAE', 'batch_size': 78, 'iterations': 20, 'learning_rate': 0.00077394969412322, 'p_miss': 0.20446296578054363}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:40:52,116] Trial 163 finished with value: 0.34180136549997353 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 5, 'imputation_order': 'ascending', 'sample_posterior': False}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:42:25,052] Trial 174 finished with value: 0.3035214030937067 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 31, 'learning_rate': 0.0003823294414689372, 'p_miss': 0.15940133345109722}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:44:26,557] Trial 166 finished with value: 0.31084708594563465 and parameters: {'model_name': 'VAE', 'batch_size': 8, 'iterations': 125, 'learning_rate': 0.0006925880773459892, 'p_miss': 0.025398984392273102}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:44:48,434] Trial 168 finished with value: 0.3136220052962445 and parameters: {'model_name': 'VAE', 'batch_size': 8, 'iterations': 119, 'learning_rate': 0.00074728736808094, 'p_miss': 0.023944446027932244}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:46:26,865] Trial 171 finished with value: 0.3205167800996931 and parameters: {'model_name': 'VAE', 'batch_size': 88, 'iterations': 121, 'learning_rate': 0.0007274542736424885, 'p_miss': 0.19886479218713837}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:46:27,887] Trial 176 finished with value: 0.35041519103109475 and parameters: {'model_name': 'VAE', 'batch_size': 888, 'iterations': 11, 'learning_rate': 0.011597819142647502, 'p_miss': 0.13384162532402277}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:47:13,644] Trial 173 finished with value: 0.3063305146515303 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 122, 'learning_rate': 0.0007293153608230472, 'p_miss': 0.1936040511791839}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:47:18,681] Trial 178 finished with value: 0.301120409187285 and parameters: {'model_name': 'VAE', 'batch_size': 57, 'iterations': 11, 'learning_rate': 0.0008702914303955038, 'p_miss': 0.13601482111891833}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:47:43,269] Trial 179 finished with value: 0.3033517688628808 and parameters: {'model_name': 'VAE', 'batch_size': 664, 'iterations': 16, 'learning_rate': 0.0008874828394302086, 'p_miss': 0.12043008146899196}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:48:00,982] Trial 172 finished with value: 0.3203163248472515 and parameters: {'model_name': 'VAE', 'batch_size': 79, 'iterations': 123, 'learning_rate': 0.0007139218333945031, 'p_miss': 0.20076558600623895}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:48:14,445] Trial 180 finished with value: 0.30133292182164534 and parameters: {'model_name': 'VAE', 'batch_size': 54, 'iterations': 16, 'learning_rate': 0.0009111509073496175, 'p_miss': 0.1708119896205761}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:49:11,509] Trial 181 finished with value: 0.3023321368676569 and parameters: {'model_name': 'VAE', 'batch_size': 55, 'iterations': 22, 'learning_rate': 0.0003015458921450339, 'p_miss': 0.11931186049548362}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:49:24,717] Trial 184 finished with value: 0.3024022200752735 and parameters: {'model_name': 'VAE', 'batch_size': 53, 'iterations': 22, 'learning_rate': 0.0012299081887347202, 'p_miss': 0.1482287310830513}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:49:47,327] Trial 183 finished with value: 0.3525227921314743 and parameters: {'model_name': 'VAE', 'batch_size': 16, 'iterations': 22, 'learning_rate': 0.03952915095630404, 'p_miss': 0.1471760243737179}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:50:58,620] Trial 186 finished with value: 0.3009057560116345 and parameters: {'model_name': 'VAE', 'batch_size': 16, 'iterations': 32, 'learning_rate': 0.0009100939171955583, 'p_miss': 0.12995804011713388}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:51:29,593] Trial 185 finished with value: 0.30286908015433667 and parameters: {'model_name': 'VAE', 'batch_size': 13, 'iterations': 29, 'learning_rate': 0.0011862431875474212, 'p_miss': 0.17122699850913345}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:52:06,043] Trial 187 finished with value: 0.30223542387675906 and parameters: {'model_name': 'VAE', 'batch_size': 105, 'iterations': 30, 'learning_rate': 0.0008887481477496255, 'p_miss': 0.17350005463494814}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:52:24,590] Trial 175 finished with value: 0.33789510144379575 and parameters: {'model_name': 'VAE', 'batch_size': 957, 'iterations': 122, 'learning_rate': 0.0009233052792283967, 'p_miss': 0.19478769004588106}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:54:04,323] Trial 189 finished with value: 0.3023544108147239 and parameters: {'model_name': 'VAE', 'batch_size': 990, 'iterations': 32, 'learning_rate': 0.00015706821617770527, 'p_miss': 0.13286564560784087}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:55:12,121] Trial 190 finished with value: 0.3018076890450913 and parameters: {'model_name': 'VAE', 'batch_size': 32, 'iterations': 51, 'learning_rate': 0.00025374122564341013, 'p_miss': 0.12843074848964098}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:55:48,871] Trial 191 finished with value: 0.3118988924989634 and parameters: {'model_name': 'VAE', 'batch_size': 18, 'iterations': 50, 'learning_rate': 0.001546403363909107, 'p_miss': 0.1367481894780973}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:56:16,819] Trial 188 finished with value: 0.3025406630592481 and parameters: {'model_name': 'VAE', 'batch_size': 985, 'iterations': 56, 'learning_rate': 0.00021526546683952076, 'p_miss': 0.13574979556997946}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:56:21,818] Trial 194 finished with value: 0.30216751214002274 and parameters: {'model_name': 'VAE', 'batch_size': 22, 'iterations': 8, 'learning_rate': 0.00022130432010441712, 'p_miss': 0.15354282521135054}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 15:56:43,259] Trial 192 finished with value: 0.31209777685418444 and parameters: {'model_name': 'VAE', 'batch_size': 31, 'iterations': 50, 'learning_rate': 0.0017429057344234963, 'p_miss': 0.13834991069277497}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 16:01:10,085] Trial 196 finished with value: 0.3027810521305763 and parameters: {'model_name': 'VAE', 'batch_size': 30, 'iterations': 77, 'learning_rate': 0.00025744235868809315, 'p_miss': 0.12769378782389684}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 16:09:00,370] Trial 177 finished with value: 0.3120453142802007 and parameters: {'model_name': 'VAE', 'batch_size': 990, 'iterations': 269, 'learning_rate': 0.00021830087054557824, 'p_miss': 0.13360564717318768}. Best is trial 98 with value: 0.30036102385259983.
running
[I 2024-09-23 16:09:28,634] Trial 193 finished with value: 0.3487575859438521 and parameters: {'model_name': 'VAE', 'batch_size': 33, 'iterations': 257, 'learning_rate': 0.0016165599837947853, 'p_miss': 0.1385238562352428}. Best is trial 98 with value: 0.30036102385259983.
[I 2024-09-23 16:10:56,266] Trial 199 finished with value: 0.3022476745114884 and parameters: {'model_name': 'VAE', 'batch_size': 12, 'iterations': 35, 'learning_rate': 0.0006408610819370205, 'p_miss': 0.05133130902572412}. Best is trial 98 with value: 0.30036102385259983.
[I 2024-09-23 16:11:07,828] Trial 27 finished with value: 0.39103701694687276 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 2967, 'learning_rate': 0.0003155160213074412, 'p_miss': 0.023954496516504407}. Best is trial 98 with value: 0.30036102385259983.
[I 2024-09-23 16:11:12,614] Trial 197 finished with value: 0.3074323666984343 and parameters: {'model_name': 'VAE', 'batch_size': 31, 'iterations': 260, 'learning_rate': 0.00026923707960554055, 'p_miss': 0.12867017894190252}. Best is trial 98 with value: 0.30036102385259983.
[I 2024-09-23 16:11:47,752] Trial 182 finished with value: 0.32078917742512364 and parameters: {'model_name': 'VAE', 'batch_size': 976, 'iterations': 278, 'learning_rate': 0.000285162415453151, 'p_miss': 0.14796830187975193}. Best is trial 98 with value: 0.30036102385259983.
[I 2024-09-23 16:16:03,719] Trial 198 finished with value: 0.34820229080970183 and parameters: {'model_name': 'VAE', 'batch_size': 149, 'iterations': 303, 'learning_rate': 0.0005656223575483592, 'p_miss': 0.054282140939623795}. Best is trial 98 with value: 0.30036102385259983.
[I 2024-09-23 16:19:14,407] Trial 1 finished with value: 0.37971282303219506 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 3621, 'learning_rate': 0.022314390653922597, 'p_miss': 0.283278521177706}. Best is trial 98 with value: 0.30036102385259983.
[I 2024-09-23 16:24:26,328] Trial 9 finished with value: 0.3513530456931483 and parameters: {'model_name': 'VAE', 'batch_size': 160, 'iterations': 3413, 'learning_rate': 0.010511543497918044, 'p_miss': 0.11260993230210975}. Best is trial 98 with value: 0.30036102385259983.
[I 2024-09-23 16:56:26,136] Trial 35 finished with value: 0.3573533870526525 and parameters: {'model_name': 'VAE', 'batch_size': 7, 'iterations': 4145, 'learning_rate': 0.00037330827937459137, 'p_miss': 0.1593308967887713}. Best is trial 98 with value: 0.30036102385259983.
[I 2024-09-23 17:42:08,765] Trial 7 finished with value: 0.3501029546945174 and parameters: {'model_name': 'VAE', 'batch_size': 995, 'iterations': 4409, 'learning_rate': 0.0003022328829338047, 'p_miss': 0.034899023080424446}. Best is trial 98 with value: 0.30036102385259983.
[I 2024-09-23 17:51:41,023] Trial 36 finished with value: 0.35057047108441786 and parameters: {'model_name': 'VAE', 'batch_size': 14, 'iterations': 7379, 'learning_rate': 0.00043738692891789004, 'p_miss': 0.12417526672131614}. Best is trial 98 with value: 0.30036102385259983.
[I 2024-09-23 17:52:32,055] Trial 169 finished with value: 0.350733865005591 and parameters: {'model_name': 'VAE', 'batch_size': 79, 'iterations': 5378, 'learning_rate': 0.0007151574681603758, 'p_miss': 0.204962661478403}. Best is trial 98 with value: 0.30036102385259983.
[I 2024-09-23 17:54:46,607] Trial 124 finished with value: 0.35887338231527205 and parameters: {'model_name': 'VAE', 'batch_size': 6, 'iterations': 6007, 'learning_rate': 0.00027127755599065786, 'p_miss': 0.17502721793673923}. Best is trial 98 with value: 0.30036102385259983.
[I 2024-09-23 17:54:49,954] Trial 33 finished with value: 0.3691730498680378 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 8557, 'learning_rate': 0.0002203090793194741, 'p_miss': 0.08319230590855131}. Best is trial 98 with value: 0.30036102385259983.
[I 2024-09-23 17:58:37,737] Trial 195 finished with value: 0.35009726928389806 and parameters: {'model_name': 'VAE', 'batch_size': 31, 'iterations': 8504, 'learning_rate': 0.00023682701392862537, 'p_miss': 0.1272920828189151}. Best is trial 98 with value: 0.30036102385259983.
[I 2024-09-23 18:05:33,807] Trial 95 finished with value: 0.34997907473658546 and parameters: {'model_name': 'VAE', 'batch_size': 827, 'iterations': 8893, 'learning_rate': 0.002973007641484387, 'p_miss': 0.08485243068932019}. Best is trial 98 with value: 0.30036102385259983.
fit
auto fit
auto transform
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64
0.30036102385259983
{'model_name': 'VAE', 'batch_size': 860, 'iterations': 26, 'learning_rate': 0.0002307120879241567, 'p_miss': 0.14438912052916816}
running experiment 2/3 - Does reconstruction give good automl predictions
Start est fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746e9000> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474704400> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a0f40> 

Generation:  1
Best root_mean_squared_error score: -4.3152986480146875
Generation:   4%|▍         | 1/25 [10:02<4:01:02, 602.62s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554747071f0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  2
Best root_mean_squared_error score: -4.3152986480146875
Generation:   8%|▊         | 2/25 [11:12<1:50:56, 289.39s/it]Generation:  3
Best root_mean_squared_error score: -4.3152986480146875
Generation:  12%|█▏        | 3/25 [14:06<1:26:43, 236.53s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467eda950> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467b45810> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546592e740> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  4
Best root_mean_squared_error score: -4.3152986480146875
Generation:  16%|█▌        | 4/25 [18:43<1:28:25, 252.63s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547472ba60> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467e63d00> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467ffa7d0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  5
Best root_mean_squared_error score: -4.3152986480146875
Generation:  20%|██        | 5/25 [19:13<57:24, 172.22s/it]  WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467839ed0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547472aa10> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547472bc40> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  6
Best root_mean_squared_error score: -4.3152986480146875
Generation:  24%|██▍       | 6/25 [20:31<44:26, 140.36s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554747274f0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546432c850> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546783b880> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467e1b0a0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  7
Best root_mean_squared_error score: -4.3152986480146875
Generation:  28%|██▊       | 7/25 [21:27<33:50, 112.81s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467fd8be0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546592ec20> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  8
Best root_mean_squared_error score: -4.3152986480146875
Generation:  32%|███▏      | 8/25 [23:24<32:18, 114.05s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546559c070> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a2fe0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465406680> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  9
Best root_mean_squared_error score: -4.3152986480146875
Generation:  36%|███▌      | 9/25 [23:59<23:49, 89.37s/it] WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474736d40> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  10
Best root_mean_squared_error score: -4.3152986480146875
Generation:  40%|████      | 10/25 [24:48<19:14, 76.97s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467973fd0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467fd8070> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467ef0850> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554747247c0> 

Generation:  11
Best root_mean_squared_error score: -4.3152986480146875
Generation:  44%|████▍     | 11/25 [35:09<56:44, 243.19s/it]Generation:  12
Best root_mean_squared_error score: -4.3152986480146875
Generation:  48%|████▊     | 12/25 [41:54<1:03:22, 292.52s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554747494b0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  13
Best root_mean_squared_error score: -4.3152986480146875
Generation:  52%|█████▏    | 13/25 [43:06<45:08, 225.72s/it]  WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746aad10> 

Generation:  14
Best root_mean_squared_error score: -4.3152986480146875
Generation:  56%|█████▌    | 14/25 [53:30<1:03:25, 345.97s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a1c00> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  15
Best root_mean_squared_error score: -4.3152986480146875
Generation:  60%|██████    | 15/25 [54:31<43:23, 260.31s/it]  Generation:  16
Best root_mean_squared_error score: -4.3152986480146875
Generation:  64%|██████▍   | 16/25 [55:38<30:18, 202.04s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a1450> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  17
Best root_mean_squared_error score: -4.3152986480146875
Generation:  68%|██████▊   | 17/25 [57:20<22:54, 171.85s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f9f850> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465404880> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  18
Best root_mean_squared_error score: -4.3152986480146875
Generation:  72%|███████▏  | 18/25 [58:13<15:53, 136.23s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554652a5d20> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  19
Best root_mean_squared_error score: -4.3152986480146875
Generation:  76%|███████▌  | 19/25 [1:00:49<14:12, 142.07s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467a2c4c0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  20
Best root_mean_squared_error score: -4.3152986480146875
Generation:  80%|████████  | 20/25 [1:04:28<13:46, 165.23s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554646336a0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  21
Best root_mean_squared_error score: -4.3152986480146875
Generation:  84%|████████▍ | 21/25 [1:05:29<08:56, 134.05s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554747498a0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  22
Best root_mean_squared_error score: -4.3152986480146875
Generation:  88%|████████▊ | 22/25 [1:06:41<05:45, 115.19s/it]Generation:  23
Best root_mean_squared_error score: -4.3152986480146875
Generation:  92%|█████████▏| 23/25 [1:08:56<04:02, 121.16s/it]Generation:  24
Best root_mean_squared_error score: -4.3152986480146875
Generation:  96%|█████████▌| 24/25 [1:10:14<01:48, 108.37s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554650fa260> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474725510> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  25
Best root_mean_squared_error score: -4.3151997672075435
Generation: 100%|██████████| 25/25 [1:11:22<00:00, 96.26s/it] Generation: 100%|██████████| 25/25 [1:11:25<00:00, 171.44s/it]
2024-09-23 19:17:11,335 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:36721' caused the cluster to lose scattered data, which can't be recovered: {'DataFrame-6dc4b2072bc5167c39418ceaedc62078', 'ndarray-dd968c4e7325128a31031a171dec9313'} (stimulus_id='handle-worker-cleanup-1727144231.3349297')
Fitted
Pipeline(steps=[('xgbregressor',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=None, device=None,
                              early_stopping_rounds=None,
                              enable_categorical=False, eval_metric=None,
                              feature_types=None, gamma=0.6384949822888,
                              grow_policy=None, importance_type=None,
                              interaction_constraints=None,
                              learning_rate=0.0457022473021, max_bin=None,
                              max_cat_threshold=None, max_cat_to_onehot=None,
                              max_delta_step=None, max_depth=3, max_leaves=None,
                              min_child_weight=9, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=100, n_jobs=1, nthread=1,
                              num_parallel_tree=None, ...))])
score start
train score: {'explained_var': 0.04701292316345129, 'r2': 0.04701298475265503, 'rmse': 4.28867197611387}
original test score: {'explained_var': 0.09749027776773156, 'r2': 0.09582430124282837, 'rmse': 4.174417355246701}
imputed test score: {'explained_var': 0.006267458362299472, 'r2': 0.006263792514801025, 'rmse': 4.376279134395548}
score end
check intended
EXP2 Finished
running experiment 3/3 - What is the best automl settings?
<tpot2.search_spaces.pipelines.sequential.SequentialPipeline object at 0x155434f4d810>
Start tpot fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a95d0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a5000> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a09a0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554747101f0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a0220> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546685ba60> 

Generation:  1
Best root_mean_squared_error score: -3.560174679219736
Generation:   4%|▍         | 1/25 [10:03<4:01:18, 603.25s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a1c30> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746f34c0> 

Generation:  2
Best root_mean_squared_error score: -3.5522712915315786
Generation:   8%|▊         | 2/25 [20:06<3:51:15, 603.30s/it]Generation:  3
Best root_mean_squared_error score: -3.507292113730337
Generation:  12%|█▏        | 3/25 [27:53<3:18:22, 541.04s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465321cf0> 

Generation:  4
Best root_mean_squared_error score: -3.507292113730337
Generation:  16%|█▌        | 4/25 [37:57<3:18:00, 565.72s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f1e620> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474653fa0> 

Generation:  5
Best root_mean_squared_error score: -3.507292113730337
Generation:  20%|██        | 5/25 [48:00<3:13:06, 579.33s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467d48bb0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  6
Best root_mean_squared_error score: -3.507292113730337
Generation:  24%|██▍       | 6/25 [55:03<2:46:40, 526.33s/it]Generation:  7
Best root_mean_squared_error score: -3.507292113730337
Generation:  28%|██▊       | 7/25 [1:02:33<2:30:19, 501.10s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467777040> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467d38a90> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546551ab60> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f077f0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467c92440> 

Generation:  8
Best root_mean_squared_error score: -3.507292113730337
Generation:  32%|███▏      | 8/25 [1:12:38<2:31:20, 534.15s/it]Generation:  9
Best root_mean_squared_error score: -3.49995425124449
Generation:  36%|███▌      | 9/25 [1:20:12<2:15:47, 509.20s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467ee4c70> 

Generation:  10
Best root_mean_squared_error score: -3.49995425124449
Generation:  40%|████      | 10/25 [1:30:17<2:14:40, 538.71s/it]Generation:  11
Best root_mean_squared_error score: -3.49995425124449
Generation:  44%|████▍     | 11/25 [1:38:12<2:01:10, 519.30s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f1cdc0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  12
Best root_mean_squared_error score: -3.49995425124449
Generation:  48%|████▊     | 12/25 [1:45:29<1:47:05, 494.27s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f1c130> 

Generation:  13
Best root_mean_squared_error score: -3.49995425124449
Generation:  52%|█████▏    | 13/25 [1:55:34<1:45:32, 527.71s/it]Generation:  14
Best root_mean_squared_error score: -3.49995425124449
Generation:  56%|█████▌    | 14/25 [2:03:33<1:34:04, 513.10s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464ecd1b0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  15
Best root_mean_squared_error score: -3.49995425124449
Generation:  60%|██████    | 15/25 [2:10:43<1:21:21, 488.16s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a2f50> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554672872b0> 

Generation:  16
Best root_mean_squared_error score: -3.49995425124449
Generation:  64%|██████▍   | 16/25 [2:20:48<1:18:28, 523.18s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467ebaf50> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  17
Best root_mean_squared_error score: -3.49666233209523
Generation:  68%|██████▊   | 17/25 [2:27:36<1:05:09, 488.67s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1553761f2770> 

Generation:  18
Best root_mean_squared_error score: -3.49666233209523
Generation:  72%|███████▏  | 18/25 [2:37:40<1:01:02, 523.19s/it]Generation:  19
Best root_mean_squared_error score: -3.49666233209523
Generation:  76%|███████▌  | 19/25 [2:40:43<42:07, 421.18s/it]  Generation:  20
Best root_mean_squared_error score: -3.49666233209523
Generation:  80%|████████  | 20/25 [2:47:39<34:57, 419.55s/it]Generation:  21
Best root_mean_squared_error score: -3.496016556342485
Generation:  84%|████████▍ | 21/25 [2:56:40<30:24, 456.07s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467e49ea0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  22
Best root_mean_squared_error score: -3.496016556342485
Generation:  88%|████████▊ | 22/25 [3:03:30<22:06, 442.03s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746f2290> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155451baf460> 

Generation:  23
Best root_mean_squared_error score: -3.496016556342485
Generation:  92%|█████████▏| 23/25 [3:13:33<16:20, 490.50s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467734610> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  24
Best root_mean_squared_error score: -3.496016556342485
Generation:  96%|█████████▌| 24/25 [3:19:41<07:33, 453.77s/it]Generation:  25
Best root_mean_squared_error score: -3.496016556342485
Generation: 100%|██████████| 25/25 [3:26:43<00:00, 444.17s/it]Generation: 100%|██████████| 25/25 [3:26:43<00:00, 496.14s/it]
2024-09-23 22:44:06,393 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:33541' caused the cluster to lose scattered data, which can't be recovered: {'DataFrame-6dc4b2072bc5167c39418ceaedc62078', 'DataFrame-8fd6a4ef8d7952fcec5c3411a7c42db2'} (stimulus_id='handle-worker-cleanup-1727156646.3931148')
Fitted
Pipeline(steps=[('simpleimputer', SimpleImputer()),
                ('lgbmregressor',
                 LGBMRegressor(max_depth=4, n_estimators=89, n_jobs=1,
                               num_leaves=195, verbose=-1))])
transform worked
try transform
transform worked
score start
train score: {'explained_var': 0.37700573618188293, 'r2': 0.37700573618188293, 'rmse': 3.467538949406254}
test score: {'explained_var': 0.43124565136255677, 'r2': 0.43124535897637395, 'rmse': 3.3107923960889516}
original test score: {'explained_var': 0.9342070797098583, 'r2': 0.9308503161631706, 'rmse': 1.1544219392291213}
score end
215
lvl
0.5
type
MNAR
num_run
3
reg_full
finished
all finished
full run takes
8.936176760461596
hours
DONE
