Run: 49
/cm/local/apps/slurm/var/spool/job957956/slurm_script: line 26: 
pip install -e tpot2
pip install -r tpot2/ImputerExperiments/requirements_.txt
: No such file or directory
RunStart
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
starting loops
../data/r/189/189.pkl
working on 
../data/r/189/reg_full_MCAR_0.01_3
2.0213463306427
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2024-09-19 21:58:57,846] A new study created in memory with name: no-name-ff95dcda-c76b-4ab0-8a7d-20fd6be0dc96
running
running
running
running
running
running
running
running
running
running
running
running
running
running
[I 2024-09-19 21:58:58,036] Trial 5 finished with value: 0.2924772774195784 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 5 with value: 0.2924772774195784.
running
running
running
[I 2024-09-19 21:58:58,215] Trial 6 finished with value: 0.5786131990922567 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 5 with value: 0.2924772774195784.
running
[I 2024-09-19 21:58:58,380] Trial 2 finished with value: 0.5786131990922567 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 5 with value: 0.2924772774195784.
running
[I 2024-09-19 21:59:00,272] Trial 7 finished with value: 0.2924275227730392 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4531, 'weights': 'uniform'}. Best is trial 7 with value: 0.2924275227730392.
running
[I 2024-09-19 21:59:00,494] Trial 0 finished with value: 0.29240984777089835 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4255, 'weights': 'uniform'}. Best is trial 0 with value: 0.29240984777089835.
running
[I 2024-09-19 21:59:00,856] Trial 8 finished with value: 0.29238449928276034 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3064, 'weights': 'distance'}. Best is trial 8 with value: 0.29238449928276034.
running
[I 2024-09-19 21:59:01,106] Trial 11 finished with value: 0.2923579308986436 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3235, 'weights': 'distance'}. Best is trial 11 with value: 0.2923579308986436.
running
[I 2024-09-19 21:59:01,295] Trial 22 finished with value: 0.5786131990922567 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 11 with value: 0.2923579308986436.
running
[I 2024-09-19 21:59:02,333] Trial 19 finished with value: 0.29247727741957835 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5233, 'weights': 'uniform'}. Best is trial 11 with value: 0.2923579308986436.
running
[I 2024-09-19 21:59:02,620] Trial 1 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.18015525184695907, 'alpha': 25, 'iterations': 1, 'learning_rate': 0.0018816321517266428, 'p_miss': 0.21257834449661306}. Best is trial 11 with value: 0.2923579308986436.
running
[I 2024-09-19 21:59:04,083] Trial 18 finished with value: 0.29543695703359435 and parameters: {'model_name': 'VAE', 'batch_size': 163, 'iterations': 1, 'learning_rate': 0.0005433149127950787, 'p_miss': 0.13620682490799788}. Best is trial 11 with value: 0.2923579308986436.
running
[I 2024-09-19 21:59:04,554] Trial 17 finished with value: 0.4749568379458193 and parameters: {'model_name': 'GAIN', 'batch_size': 127, 'hint_rate': 0.39790971540438885, 'alpha': 48, 'iterations': 4, 'learning_rate': 0.04784907109851021, 'p_miss': 0.11418586671191508}. Best is trial 11 with value: 0.2923579308986436.
running
[I 2024-09-19 21:59:05,153] Trial 3 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 4, 'hint_rate': 0.7951842996972598, 'alpha': 13, 'iterations': 33, 'learning_rate': 0.05304052819254665, 'p_miss': 0.09619720963413478}. Best is trial 11 with value: 0.2923579308986436.
running
[I 2024-09-19 21:59:07,283] Trial 24 finished with value: 0.29244217626029334 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5232, 'weights': 'distance'}. Best is trial 11 with value: 0.2923579308986436.
running
[I 2024-09-19 21:59:08,434] Trial 10 finished with value: 0.47552174169327327 and parameters: {'model_name': 'GAIN', 'batch_size': 69, 'hint_rate': 0.36767731050758623, 'alpha': 42, 'iterations': 11, 'learning_rate': 0.00015035751845262146, 'p_miss': 0.12270061794325125}. Best is trial 11 with value: 0.2923579308986436.
running
[I 2024-09-19 21:59:11,698] Trial 30 finished with value: 0.2924546147191832 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'median', 'n_nearest_features': 8, 'imputation_order': 'random'}. Best is trial 11 with value: 0.2923579308986436.
running
[I 2024-09-19 21:59:15,861] Trial 31 finished with value: 0.29234446653938456 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1486, 'weights': 'distance'}. Best is trial 31 with value: 0.29234446653938456.
running
[I 2024-09-19 21:59:18,126] Trial 15 finished with value: 0.2990565252587985 and parameters: {'model_name': 'VAE', 'batch_size': 13, 'iterations': 20, 'learning_rate': 0.00022642230111479957, 'p_miss': 0.0391591485679342}. Best is trial 31 with value: 0.29234446653938456.
running
[I 2024-09-19 21:59:18,749] Trial 9 finished with value: 0.29693486706644584 and parameters: {'model_name': 'VAE', 'batch_size': 2, 'iterations': 23, 'learning_rate': 0.00148614603855868, 'p_miss': 0.2676587666621056}. Best is trial 31 with value: 0.29234446653938456.
running
[I 2024-09-19 21:59:23,479] Trial 4 finished with value: 0.29644932647812766 and parameters: {'model_name': 'VAE', 'batch_size': 28, 'iterations': 31, 'learning_rate': 0.0024630794968464463, 'p_miss': 0.18697134261429127}. Best is trial 31 with value: 0.29234446653938456.
running
[I 2024-09-19 21:59:29,237] Trial 26 finished with value: 0.3201760367945701 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'constant', 'n_nearest_features': 5, 'imputation_order': 'arabic'}. Best is trial 31 with value: 0.29234446653938456.
running
[I 2024-09-19 21:59:33,596] Trial 21 finished with value: 0.2971230607392236 and parameters: {'model_name': 'VAE', 'batch_size': 786, 'iterations': 9, 'learning_rate': 0.00012092481605171562, 'p_miss': 0.027408059904304283}. Best is trial 31 with value: 0.29234446653938456.
running
[I 2024-09-19 21:59:33,839] Trial 33 finished with value: 0.3157811795101418 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'mean', 'n_nearest_features': 1, 'imputation_order': 'roman'}. Best is trial 31 with value: 0.29234446653938456.
running
[I 2024-09-19 21:59:34,489] Trial 36 finished with value: 0.2922576954292414 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1191, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:37,939] Trial 34 finished with value: 0.40620664743535234 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 1, 'imputation_order': 'arabic', 'sample_posterior': True}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:38,904] Trial 37 finished with value: 0.29232061070162435 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1465, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:39,183] Trial 39 finished with value: 0.2926441813992723 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 451, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:39,566] Trial 38 finished with value: 0.2923482031864782 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1371, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:43,064] Trial 40 finished with value: 0.29236287135016664 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 702, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:43,562] Trial 41 finished with value: 0.29255481439847536 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 594, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:44,591] Trial 42 finished with value: 0.29227928746887766 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1167, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:45,528] Trial 43 finished with value: 0.2923171470246403 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1654, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:46,980] Trial 16 finished with value: 0.40805544794495513 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'median', 'n_nearest_features': 6, 'imputation_order': 'random', 'sample_posterior': True}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:49,341] Trial 44 finished with value: 0.2923527578734154 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1950, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:50,254] Trial 45 finished with value: 0.29235245983097613 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2169, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:51,062] Trial 46 finished with value: 0.29233062873729676 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1732, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:51,645] Trial 27 finished with value: 0.29245833114142145 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 3, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:51,829] Trial 47 finished with value: 0.29234999515679777 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2063, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:53,616] Trial 48 finished with value: 0.2923807301297911 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1994, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:55,062] Trial 49 finished with value: 0.2923213745805744 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2287, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:55,579] Trial 55 finished with value: 0.2924954160442465 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:55,823] Trial 50 finished with value: 0.2923167513754436 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2333, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:56,169] Trial 52 finished with value: 0.295556296172666 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 46, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:57,124] Trial 51 finished with value: 0.29233574231162873 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2492, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 21:59:57,489] Trial 53 finished with value: 0.2922952561768153 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1218, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 22:00:00,045] Trial 57 finished with value: 0.29228021161059164 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1055, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 22:00:00,432] Trial 56 finished with value: 0.29229406567437943 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1107, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 22:00:01,730] Trial 29 finished with value: 0.4117917220886097 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 3, 'imputation_order': 'arabic', 'sample_posterior': True}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 22:00:40,346] Trial 13 finished with value: 0.47687113221156574 and parameters: {'model_name': 'GAIN', 'batch_size': 872, 'hint_rate': 0.9229433607802539, 'alpha': 36, 'iterations': 108, 'learning_rate': 0.0015103881968759893, 'p_miss': 0.19279398245125615}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 22:05:25,292] Trial 20 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.37682632402945326, 'alpha': 18, 'iterations': 1930, 'learning_rate': 0.020103803105711582, 'p_miss': 0.1432903618107599}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 22:05:25,684] Trial 65 finished with value: 0.2924772774195784 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 22:05:29,663] Trial 66 finished with value: 0.29227163904242326 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1003, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 22:05:33,663] Trial 67 finished with value: 0.29227963291083087 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 990, 'weights': 'distance'}. Best is trial 36 with value: 0.2922576954292414.
running
[I 2024-09-19 22:05:37,194] Trial 68 finished with value: 0.29223570945255306 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 952, 'weights': 'distance'}. Best is trial 68 with value: 0.29223570945255306.
running
[I 2024-09-19 22:05:40,238] Trial 69 finished with value: 0.29216378916385005 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 890, 'weights': 'uniform'}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:20:33,506] Trial 32 finished with value: 0.34512591353620864 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 1, 'imputation_order': 'roman'}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:20:51,395] Trial 35 finished with value: 0.35162037276012537 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 1, 'imputation_order': 'descending'}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:30:28,174] Trial 23 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.165748730380979, 'alpha': 19, 'iterations': 7908, 'learning_rate': 0.038412321591927444, 'p_miss': 0.03355091331908689}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:31:23,038] Trial 28 finished with value: 0.30141292217441257 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 4, 'imputation_order': 'random'}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:39:06,641] Trial 74 finished with value: 0.3149270450607574 and parameters: {'model_name': 'VAE', 'batch_size': 6, 'iterations': 215, 'learning_rate': 0.013838899185827612, 'p_miss': 0.29356934095546927}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:39:09,723] Trial 75 finished with value: 0.29297399600236085 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 256, 'weights': 'uniform'}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:39:13,545] Trial 76 finished with value: 0.29224440221531583 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 857, 'weights': 'uniform'}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:39:17,503] Trial 77 finished with value: 0.29227974189500305 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 794, 'weights': 'uniform'}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:39:21,423] Trial 78 finished with value: 0.29222139253315527 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 836, 'weights': 'uniform'}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:43:30,124] Trial 73 finished with value: 0.307264776456985 and parameters: {'model_name': 'VAE', 'batch_size': 7, 'iterations': 306, 'learning_rate': 0.01014192515174478, 'p_miss': 0.28912163882475883}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:44:57,841] Trial 12 finished with value: 0.2947929850712911 and parameters: {'model_name': 'VAE', 'batch_size': 128, 'iterations': 972, 'learning_rate': 0.0033185344883923146, 'p_miss': 0.11286741004574462}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:53:14,457] Trial 79 finished with value: 0.48901986852128587 and parameters: {'model_name': 'GAIN', 'batch_size': 282, 'hint_rate': 0.6630191756662832, 'alpha': 100, 'iterations': 581, 'learning_rate': 0.0065058612954269485, 'p_miss': 0.07143985518162159}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:53:17,157] Trial 82 finished with value: 0.2924461988352574 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 607, 'weights': 'uniform'}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:53:21,050] Trial 83 finished with value: 0.2924108831823824 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3990, 'weights': 'uniform'}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:53:23,661] Trial 84 finished with value: 0.29221169786064555 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 876, 'weights': 'uniform'}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:53:24,386] Trial 85 finished with value: 0.5786131990922567 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:53:27,323] Trial 86 finished with value: 0.29247727741957835 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 6504, 'weights': 'uniform'}. Best is trial 69 with value: 0.29216378916385005.
running
[I 2024-09-19 22:53:30,591] Trial 87 finished with value: 0.2921282059701883 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 924, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 22:53:33,135] Trial 88 finished with value: 0.2930390625366851 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 282, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 22:53:36,097] Trial 89 finished with value: 0.2922309035250685 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 849, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 22:53:38,755] Trial 90 finished with value: 0.29226501437198327 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 735, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 22:53:41,012] Trial 91 finished with value: 0.29433263690454675 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 73, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:03:42,164] Trial 80 finished with value: 0.49752086500820863 and parameters: {'model_name': 'GAIN', 'batch_size': 355, 'hint_rate': 0.7151170399472258, 'alpha': 100, 'iterations': 863, 'learning_rate': 0.005716450658915956, 'p_miss': 0.07718978894585149}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:03:45,354] Trial 93 finished with value: 0.2923235905336232 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1418, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:03:48,035] Trial 94 finished with value: 0.29225081987070317 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 827, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:03:50,382] Trial 95 finished with value: 0.2924907079574216 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 458, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:03:53,116] Trial 96 finished with value: 0.29214563676894617 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 915, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:03:56,015] Trial 97 finished with value: 0.2921282059701883 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 924, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:03:58,795] Trial 98 finished with value: 0.29223634407876997 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 861, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:04:01,669] Trial 99 finished with value: 0.2923035601996416 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1335, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:04:04,253] Trial 100 finished with value: 0.2928089827062629 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 377, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:04:07,186] Trial 101 finished with value: 0.2922844514135187 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1690, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:04:10,232] Trial 102 finished with value: 0.2924988865353195 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 493, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:20:48,066] Trial 14 finished with value: 0.46567449017744994 and parameters: {'model_name': 'GAIN', 'batch_size': 23, 'hint_rate': 0.8622863802303095, 'alpha': 52, 'iterations': 4162, 'learning_rate': 0.03513617666363352, 'p_miss': 0.24381097571007995}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:20:55,422] Trial 104 finished with value: 0.3076779298268583 and parameters: {'model_name': 'VAE', 'batch_size': 47, 'iterations': 3, 'learning_rate': 0.0005396535084527344, 'p_miss': 0.16918679809828757}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:20:58,428] Trial 105 finished with value: 0.2922287427039894 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 872, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:21:01,052] Trial 106 finished with value: 0.2922307074709023 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 862, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:21:03,945] Trial 107 finished with value: 0.2922364402188673 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1260, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:21:06,213] Trial 108 finished with value: 0.29240287697681366 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 643, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:21:09,335] Trial 109 finished with value: 0.2922876895497857 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1543, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:21:12,028] Trial 110 finished with value: 0.2922001075835944 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1001, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:21:12,574] Trial 111 finished with value: 0.2924954160442465 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:21:15,481] Trial 112 finished with value: 0.29222520381424955 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1206, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:21:18,904] Trial 113 finished with value: 0.29235019836448445 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2707, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:21:21,846] Trial 114 finished with value: 0.29221012758368703 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1197, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:22:39,751] Trial 115 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 3, 'hint_rate': 0.044836134136159, 'alpha': 72, 'iterations': 117, 'learning_rate': 0.09051303352021314, 'p_miss': 0.2347004984286608}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:22:42,613] Trial 116 finished with value: 0.2921824524156683 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1189, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:22:45,128] Trial 117 finished with value: 0.2921920286699085 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1161, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:22:48,112] Trial 118 finished with value: 0.2923194469479299 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1791, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:22:50,656] Trial 119 finished with value: 0.29222207348862805 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1205, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:22:53,360] Trial 120 finished with value: 0.2922812572021578 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1452, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:22:56,105] Trial 121 finished with value: 0.2922078537965741 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1141, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:22:58,758] Trial 122 finished with value: 0.29221165075510164 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1118, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:01,411] Trial 123 finished with value: 0.29223426746207953 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1112, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:04,212] Trial 124 finished with value: 0.2923218759180545 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1478, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:12,168] Trial 125 finished with value: 0.3018104690817919 and parameters: {'model_name': 'VAE', 'batch_size': 12, 'iterations': 3, 'learning_rate': 0.0005847964759512954, 'p_miss': 0.014017053774308758}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:14,663] Trial 126 finished with value: 0.29243588317683883 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 630, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:17,535] Trial 127 finished with value: 0.2922153016602591 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1080, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:20,398] Trial 128 finished with value: 0.2922323001513796 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1091, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:22,963] Trial 129 finished with value: 0.29226620338464765 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1298, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:25,839] Trial 130 finished with value: 0.2922166591402543 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1116, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:28,985] Trial 131 finished with value: 0.292454610228069 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'median', 'n_nearest_features': 8, 'imputation_order': 'ascending'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:32,369] Trial 132 finished with value: 0.2924449561071934 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3564, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:35,526] Trial 133 finished with value: 0.29232589383956253 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1868, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:36,122] Trial 134 finished with value: 0.5786131990922567 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:38,791] Trial 135 finished with value: 0.29220217324917586 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 991, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:41,434] Trial 136 finished with value: 0.29219136450073324 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1004, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:43,832] Trial 137 finished with value: 0.2924837126781994 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 594, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:47,005] Trial 138 finished with value: 0.29227044758756915 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1527, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:49,677] Trial 139 finished with value: 0.2921963767440602 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 994, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:53,371] Trial 140 finished with value: 0.29246492628565995 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4794, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:23:56,177] Trial 141 finished with value: 0.2922694272234246 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1309, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:36:38,387] Trial 63 finished with value: 0.5141504563046475 and parameters: {'model_name': 'GAIN', 'batch_size': 952, 'hint_rate': 0.9590853657198305, 'alpha': 100, 'iterations': 3936, 'learning_rate': 0.011488216536210807, 'p_miss': 0.29897668134231214}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:36:42,274] Trial 143 finished with value: 0.2922001075835944 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1001, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:36:45,565] Trial 144 finished with value: 0.29218550302349483 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1006, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:36:49,117] Trial 145 finished with value: 0.2921417936789009 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 965, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:36:52,214] Trial 146 finished with value: 0.2922002039460148 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 993, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:36:55,595] Trial 147 finished with value: 0.29218830827915776 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 983, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:36:59,040] Trial 148 finished with value: 0.29224345522992945 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 725, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:37:02,282] Trial 149 finished with value: 0.29214368571801563 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 947, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:37:05,548] Trial 150 finished with value: 0.29226066850033977 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 702, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:37:09,008] Trial 151 finished with value: 0.292513411695535 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 511, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:37:12,386] Trial 152 finished with value: 0.29214964671834204 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 957, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:37:15,684] Trial 153 finished with value: 0.29272824250190166 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 387, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:37:18,834] Trial 154 finished with value: 0.29223023748784244 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 714, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:37:26,978] Trial 142 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 2, 'hint_rate': 0.5603654008180972, 'alpha': 73, 'iterations': 3622, 'learning_rate': 0.00030270824088341077, 'p_miss': 0.05878337471431806}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:37:30,329] Trial 156 finished with value: 0.29218040449975774 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 981, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:37:31,092] Trial 155 finished with value: 0.2924898787071251 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 6, 'imputation_order': 'ascending'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:37:33,658] Trial 158 finished with value: 0.2930390783683766 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 203, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:37:34,140] Trial 157 finished with value: 0.2921707516445912 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 898, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:37:36,343] Trial 159 finished with value: 0.2921482015093929 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 931, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:37:37,345] Trial 160 finished with value: 0.2921821756223079 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 901, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:37:40,039] Trial 161 finished with value: 0.2922887273927874 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 773, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:40:23,021] Trial 163 finished with value: 0.29529070197950924 and parameters: {'model_name': 'VAE', 'batch_size': 51, 'iterations': 66, 'learning_rate': 0.0008086486814630173, 'p_miss': 0.17067789599184766}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:40:25,614] Trial 164 finished with value: 0.2925137611968197 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 554, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:40:26,148] Trial 165 finished with value: 0.2924954160442465 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:40:28,761] Trial 166 finished with value: 0.2922465069918757 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 858, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:40:31,878] Trial 167 finished with value: 0.2923095453483765 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1360, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:40:34,492] Trial 168 finished with value: 0.2921457393598126 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 895, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:40:37,221] Trial 169 finished with value: 0.29216332782082244 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 889, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:40:40,122] Trial 170 finished with value: 0.29229472018755165 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 745, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:40:43,140] Trial 171 finished with value: 0.2921335922464018 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 936, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:40:45,992] Trial 172 finished with value: 0.29223467758639127 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 865, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:40:48,352] Trial 173 finished with value: 0.2930103650614556 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 366, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:40:51,031] Trial 174 finished with value: 0.29245256807510633 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 613, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:40:53,965] Trial 175 finished with value: 0.2922556283178387 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1291, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:40:56,633] Trial 176 finished with value: 0.2921496936778914 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 913, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:40:59,860] Trial 177 finished with value: 0.29215225646912457 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 918, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:41:02,553] Trial 178 finished with value: 0.2921546932415128 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 893, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:41:05,377] Trial 179 finished with value: 0.29230210920161165 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 771, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:41:08,210] Trial 180 finished with value: 0.292177990495075 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 900, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:41:10,947] Trial 181 finished with value: 0.2923765053019613 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 655, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:41:13,481] Trial 182 finished with value: 0.29217750880620047 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 911, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:41:16,162] Trial 183 finished with value: 0.2925393273123828 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 518, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:41:19,616] Trial 184 finished with value: 0.29247727741957835 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 6522, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:41:22,436] Trial 185 finished with value: 0.29227228823388535 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 783, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:41:25,233] Trial 186 finished with value: 0.29217980427384044 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 885, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:41:28,074] Trial 187 finished with value: 0.29247727741957835 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5979, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:41:30,704] Trial 188 finished with value: 0.2922656752166287 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 823, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:41:33,573] Trial 189 finished with value: 0.2921897272590389 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 904, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:41:36,428] Trial 190 finished with value: 0.29219687848163456 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1121, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:49:12,447] Trial 70 finished with value: 0.4723252426633099 and parameters: {'model_name': 'GAIN', 'batch_size': 7, 'hint_rate': 0.054551904843905985, 'alpha': 98, 'iterations': 5040, 'learning_rate': 0.010041803461887745, 'p_miss': 0.29709031256110235}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:49:15,300] Trial 192 finished with value: 0.2923620846290781 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 652, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:49:18,282] Trial 193 finished with value: 0.29223708826620937 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1245, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:49:36,465] Trial 194 finished with value: 0.3255761295094365 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'most_frequent', 'n_nearest_features': 7, 'imputation_order': 'descending'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:49:39,252] Trial 195 finished with value: 0.2921496936778914 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 913, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:49:42,059] Trial 196 finished with value: 0.29215169708672306 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 955, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:49:45,237] Trial 197 finished with value: 0.29223019266568684 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1094, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-19 23:49:47,975] Trial 198 finished with value: 0.2921551730140116 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 929, 'weights': 'uniform'}. Best is trial 87 with value: 0.2921282059701883.
running
[I 2024-09-20 00:10:28,033] Trial 54 finished with value: 0.5140597881408773 and parameters: {'model_name': 'GAIN', 'batch_size': 838, 'hint_rate': 0.8607147639719019, 'alpha': 100, 'iterations': 5100, 'learning_rate': 0.011925754576271602, 'p_miss': 0.2979141975143316}. Best is trial 87 with value: 0.2921282059701883.
[I 2024-09-20 00:14:05,461] Trial 64 finished with value: 0.47682826723362304 and parameters: {'model_name': 'GAIN', 'batch_size': 8, 'hint_rate': 0.0311082031913828, 'alpha': 100, 'iterations': 6529, 'learning_rate': 0.013077657555752818, 'p_miss': 0.2820420105922512}. Best is trial 87 with value: 0.2921282059701883.
[I 2024-09-20 00:24:23,123] Trial 92 finished with value: 0.4938572275440071 and parameters: {'model_name': 'GAIN', 'batch_size': 33, 'hint_rate': 0.040385275785996766, 'alpha': 75, 'iterations': 4451, 'learning_rate': 0.0005261761301716447, 'p_miss': 0.23952693607707393}. Best is trial 87 with value: 0.2921282059701883.
[I 2024-09-20 00:27:26,855] Trial 60 finished with value: 0.5004489323725664 and parameters: {'model_name': 'GAIN', 'batch_size': 638, 'hint_rate': 0.9562463229139899, 'alpha': 98, 'iterations': 6078, 'learning_rate': 0.012341808132003501, 'p_miss': 0.29989516781434933}. Best is trial 87 with value: 0.2921282059701883.
[I 2024-09-20 00:40:39,002] Trial 72 finished with value: 0.4774400093130022 and parameters: {'model_name': 'GAIN', 'batch_size': 9, 'hint_rate': 0.014874152617627423, 'alpha': 100, 'iterations': 6961, 'learning_rate': 0.01048191759545411, 'p_miss': 0.29884497622220557}. Best is trial 87 with value: 0.2921282059701883.
[I 2024-09-20 01:07:46,742] Trial 25 finished with value: 0.29422990649837977 and parameters: {'model_name': 'VAE', 'batch_size': 855, 'iterations': 3837, 'learning_rate': 0.08738589271046798, 'p_miss': 0.028490880061924934}. Best is trial 87 with value: 0.2921282059701883.
[I 2024-09-20 01:16:30,048] Trial 59 finished with value: 0.496326939840608 and parameters: {'model_name': 'GAIN', 'batch_size': 805, 'hint_rate': 0.9741660753228991, 'alpha': 98, 'iterations': 8821, 'learning_rate': 0.010071115262545081, 'p_miss': 0.29689214286072935}. Best is trial 87 with value: 0.2921282059701883.
[I 2024-09-20 01:16:42,483] Trial 71 finished with value: 0.4761949032732219 and parameters: {'model_name': 'GAIN', 'batch_size': 8, 'hint_rate': 0.6522555737741285, 'alpha': 95, 'iterations': 9835, 'learning_rate': 0.010604100174365515, 'p_miss': 0.2829242714867331}. Best is trial 87 with value: 0.2921282059701883.
[I 2024-09-20 01:16:50,263] Trial 81 finished with value: 0.5095291852285662 and parameters: {'model_name': 'GAIN', 'batch_size': 328, 'hint_rate': 0.6706382852528925, 'alpha': 97, 'iterations': 7713, 'learning_rate': 0.005810787149337112, 'p_miss': 0.24308273170499178}. Best is trial 87 with value: 0.2921282059701883.
[I 2024-09-20 01:19:05,047] Trial 58 finished with value: 0.5022981221533828 and parameters: {'model_name': 'GAIN', 'batch_size': 937, 'hint_rate': 0.8808158293206264, 'alpha': 97, 'iterations': 9262, 'learning_rate': 0.01300024904374937, 'p_miss': 0.2874490534951102}. Best is trial 87 with value: 0.2921282059701883.
[I 2024-09-20 01:19:12,579] Trial 62 finished with value: 0.4991272190197392 and parameters: {'model_name': 'GAIN', 'batch_size': 942, 'hint_rate': 0.9318550252341988, 'alpha': 97, 'iterations': 9280, 'learning_rate': 0.011560416973148335, 'p_miss': 0.28976183850697784}. Best is trial 87 with value: 0.2921282059701883.
[I 2024-09-20 01:20:23,472] Trial 61 finished with value: 0.49527233967403167 and parameters: {'model_name': 'GAIN', 'batch_size': 515, 'hint_rate': 0.8964812250981883, 'alpha': 96, 'iterations': 9837, 'learning_rate': 0.00964091882033999, 'p_miss': 0.2916618019875551}. Best is trial 87 with value: 0.2921282059701883.
[I 2024-09-20 01:20:31,792] Trial 103 finished with value: 0.2975469279120661 and parameters: {'model_name': 'VAE', 'batch_size': 35, 'iterations': 4025, 'learning_rate': 0.08189675157230723, 'p_miss': 0.2286532073457936}. Best is trial 87 with value: 0.2921282059701883.
[I 2024-09-20 01:24:44,270] Trial 191 finished with value: 0.4919723299523085 and parameters: {'model_name': 'GAIN', 'batch_size': 413, 'hint_rate': 0.5356102941093284, 'alpha': 68, 'iterations': 8846, 'learning_rate': 0.09938289574583815, 'p_miss': 0.22168680238499194}. Best is trial 87 with value: 0.2921282059701883.
[I 2024-09-20 01:33:21,178] Trial 162 finished with value: 0.296031549517359 and parameters: {'model_name': 'VAE', 'batch_size': 46, 'iterations': 9217, 'learning_rate': 0.0009726270116882997, 'p_miss': 0.2559195679634497}. Best is trial 87 with value: 0.2921282059701883.
[I 2024-09-20 01:37:29,719] Trial 199 finished with value: 0.2944251105051285 and parameters: {'model_name': 'VAE', 'batch_size': 411, 'iterations': 9934, 'learning_rate': 0.004171973749227269, 'p_miss': 0.24749638317733783}. Best is trial 87 with value: 0.2921282059701883.
fit
auto fit
auto transform
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64
0.2921282059701883
{'model_name': 'KNNImputer', 'n_neighbors': 924, 'weights': 'uniform'}
running experiment 2/3 - Does reconstruction give good automl predictions
Start est fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474733ac0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474708be0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  1
Best root_mean_squared_error score: -0.09094435807892495
Generation:   4%|▍         | 1/25 [00:22<08:54, 22.26s/it]Generation:  2
Best root_mean_squared_error score: -0.08713980925032401
Generation:   8%|▊         | 2/25 [01:41<21:16, 55.52s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746ff5b0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465abb310> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746f33d0> 

Generation:  3
Best root_mean_squared_error score: -0.08713980925032401
Generation:  12%|█▏        | 3/25 [11:53<1:53:33, 309.68s/it]Generation:  4
Best root_mean_squared_error score: -0.08302272334980629
Generation:  16%|█▌        | 4/25 [14:24<1:26:33, 247.33s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547473ae30> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547472aa10> 

Generation:  5
Best root_mean_squared_error score: -0.0804767704540942
Generation:  20%|██        | 5/25 [24:42<2:06:59, 380.99s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467fb02b0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467941ab0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467ffa140> 

Generation:  6
Best root_mean_squared_error score: -0.0804767704540942
Generation:  24%|██▍       | 6/25 [35:06<2:26:42, 463.30s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a5e40> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746faa70> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554658ea110> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  7
Best root_mean_squared_error score: -0.0804767704540942
Generation:  28%|██▊       | 7/25 [38:35<1:54:06, 380.35s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554658d8be0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  8
Best root_mean_squared_error score: -0.0804767704540942
Generation:  32%|███▏      | 8/25 [48:49<2:08:52, 454.83s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554747099c0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f18970> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  9
Best root_mean_squared_error score: -0.0804767704540942
Generation:  36%|███▌      | 9/25 [54:33<1:51:58, 419.91s/it]Generation:  10
Best root_mean_squared_error score: -0.0804767704540942
Generation:  40%|████      | 10/25 [1:03:17<1:53:04, 452.31s/it]Generation:  11
Best root_mean_squared_error score: -0.0804767704540942
Generation:  44%|████▍     | 11/25 [1:10:16<1:43:08, 442.07s/it]Generation:  12
Best root_mean_squared_error score: -0.0804767704540942
Generation:  48%|████▊     | 12/25 [1:13:39<1:20:00, 369.25s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746fc580> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746fe290> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467932950> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  13
Best root_mean_squared_error score: -0.0804767704540942
Generation:  52%|█████▏    | 13/25 [1:15:44<59:04, 295.39s/it]  WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155459a9a9e0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  14
Best root_mean_squared_error score: -0.0804767704540942
Generation:  56%|█████▌    | 14/25 [1:23:33<1:03:44, 347.66s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155459bbe290> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4eb0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545b5e91b0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  15
Best root_mean_squared_error score: -0.0804767704540942
Generation:  60%|██████    | 15/25 [1:28:52<56:31, 339.13s/it]  Generation:  16
Best root_mean_squared_error score: -0.0804767704540942
Generation:  64%|██████▍   | 16/25 [1:37:32<59:02, 393.58s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465a2a1d0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  17
Best root_mean_squared_error score: -0.0804767704540942
Generation:  68%|██████▊   | 17/25 [1:44:24<53:12, 399.01s/it]Generation:  18
Best root_mean_squared_error score: -0.0804767704540942
Generation:  72%|███████▏  | 18/25 [1:47:40<39:26, 338.10s/it]Generation:  19
Best root_mean_squared_error score: -0.0804767704540942
Generation:  76%|███████▌  | 19/25 [1:56:35<39:42, 397.10s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155459c3ab90> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467940910> 

Generation:  20
Best root_mean_squared_error score: -0.0804767704540942
Generation:  80%|████████  | 20/25 [2:07:24<39:23, 472.69s/it]Generation:  21
Best root_mean_squared_error score: -0.0804767704540942
Generation:  84%|████████▍ | 21/25 [2:12:18<27:56, 419.21s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547473f280> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  22
Best root_mean_squared_error score: -0.0804767704540942
Generation:  88%|████████▊ | 22/25 [2:22:48<24:06, 482.31s/it]Generation:  23
Best root_mean_squared_error score: -0.0804767704540942
Generation:  92%|█████████▏| 23/25 [2:28:58<14:57, 448.68s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464b3de40> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467bbfb20> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  24
Best root_mean_squared_error score: -0.0804767704540942
Generation:  96%|█████████▌| 24/25 [2:33:35<06:37, 397.37s/it]Generation:  25
Best root_mean_squared_error score: -0.0804767704540942
Generation: 100%|██████████| 25/25 [2:41:38<00:00, 422.94s/it]Generation: 100%|██████████| 25/25 [2:41:41<00:00, 388.05s/it]
2024-09-20 04:19:41,498 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:43185' caused the cluster to lose scattered data, which can't be recovered: {'ndarray-c1449d147947fbde59264f664650c30a', 'DataFrame-199f3c31ceebfff04409bf1345a44d8c'} (stimulus_id='handle-worker-cleanup-1726831181.4985077')
Fitted
Pipeline(steps=[('mlpregressor',
                 MLPRegressor(alpha=8.171728e-07, early_stopping=True,
                              hidden_layer_sizes=[414, 414, 414],
                              learning_rate_init=0.0003893134893,
                              n_iter_no_change=32))])
score start
train score: {'explained_var': 0.947911522185294, 'r2': 0.9476560617365457, 'rmse': 0.06055683365339399}
original test score: {'explained_var': 0.9286941013786516, 'r2': 0.9282507465364604, 'rmse': 0.06941460720364025}
imputed test score: {'explained_var': 0.9073608064992424, 'r2': 0.90692777611038, 'rmse': 0.07905916492101998}
score end
check intended
EXP2 Finished
running experiment 3/3 - What is the best automl settings?
<tpot2.search_spaces.pipelines.sequential.SequentialPipeline object at 0x15543132b760>
Start tpot fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474738790> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4a00> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4b50> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4f10> 
 Input X contains NaN.
ExtraTreesRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/ensemble/_forest.py", line 377, in fit
    estimator._compute_missing_values_in_feature_mask(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/tree/_classes.py", line 214, in _compute_missing_values_in_feature_mask
    assert_all_finite(X, **common_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 213, in assert_all_finite
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
ExtraTreesRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4af0> 

Generation:  1
Best root_mean_squared_error score: -0.14409412097473745
Generation:   4%|▍         | 1/25 [10:02<4:01:04, 602.69s/it]Generation:  2
Best root_mean_squared_error score: -0.14409412097473745
Generation:   8%|▊         | 2/25 [10:25<1:40:14, 261.48s/it]Generation:  3
Best root_mean_squared_error score: -0.13781884164065178
Generation:  12%|█▏        | 3/25 [10:34<53:39, 146.34s/it]  WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474712da0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  4
Best root_mean_squared_error score: -0.08729122960531935
Generation:  16%|█▌        | 4/25 [12:02<43:05, 123.11s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746afe20> 

Generation:  5
Best root_mean_squared_error score: -0.08729122960531935
Generation:  20%|██        | 5/25 [22:06<1:38:50, 296.54s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746afd90> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465419db0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  6
Best root_mean_squared_error score: -0.08729122960531935
Generation:  24%|██▍       | 6/25 [25:02<1:21:00, 255.81s/it]Generation:  7
Best root_mean_squared_error score: -0.08729122960531935
Generation:  28%|██▊       | 7/25 [26:47<1:01:53, 206.29s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554677ff1f0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a6d10> 
 Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 751, in fit
    return self._fit(X, y, incremental=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 441, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1621, in _validate_input
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465787610> 

Generation:  8
Best root_mean_squared_error score: -0.08537914235407268
Generation:  32%|███▏      | 8/25 [36:52<1:34:23, 333.14s/it]Generation:  9
Best root_mean_squared_error score: -0.08358646057959536
Generation:  36%|███▌      | 9/25 [41:51<1:25:59, 322.49s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465ed0250> 
 Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 751, in fit
    return self._fit(X, y, incremental=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 441, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1621, in _validate_input
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  10
Best root_mean_squared_error score: -0.08288064082726436
Generation:  40%|████      | 10/25 [47:29<1:21:52, 327.52s/it]Generation:  11
Best root_mean_squared_error score: -0.08288064082726436
Generation:  44%|████▍     | 11/25 [53:55<1:20:32, 345.18s/it]Generation:  12
Best root_mean_squared_error score: -0.08269709985319859
Generation:  48%|████▊     | 12/25 [59:13<1:13:03, 337.16s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155452b31030> 
 Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 751, in fit
    return self._fit(X, y, incremental=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 441, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1621, in _validate_input
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  13
Best root_mean_squared_error score: -0.08084684102254638
Generation:  52%|█████▏    | 13/25 [1:05:13<1:08:49, 344.09s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465e49060> 

Generation:  14
Best root_mean_squared_error score: -0.08084684102254638
Generation:  56%|█████▌    | 14/25 [1:15:20<1:17:35, 423.25s/it]Generation:  15
Best root_mean_squared_error score: -0.07970767917451857
Generation:  60%|██████    | 15/25 [1:23:27<1:13:45, 442.57s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155454268520> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465b5fee0> 

Generation:  16
Best root_mean_squared_error score: -0.07970767917451857
Generation:  64%|██████▍   | 16/25 [1:33:32<1:13:42, 491.43s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155454a28670> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467076980> 
 Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 751, in fit
    return self._fit(X, y, incremental=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 441, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1621, in _validate_input
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465c6a200> 

Generation:  17
Best root_mean_squared_error score: -0.07970767917451857
Generation:  68%|██████▊   | 17/25 [1:43:37<1:10:04, 525.52s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467b10fa0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467b60dc0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1553d128f8b0> 

Generation:  18
Best root_mean_squared_error score: -0.0794563997231137
Generation:  72%|███████▏  | 18/25 [1:53:43<1:04:08, 549.73s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465418b50> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155454b2bbb0> 
 Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 751, in fit
    return self._fit(X, y, incremental=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 441, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1621, in _validate_input
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155451d8da20> 

Generation:  19
Best root_mean_squared_error score: -0.0794563997231137
Generation:  76%|███████▌  | 19/25 [2:03:47<56:35, 565.99s/it]  Generation:  20
Best root_mean_squared_error score: -0.0794563997231137
Generation:  80%|████████  | 20/25 [2:10:36<43:15, 519.03s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155450c42950> 

Generation:  21
Best root_mean_squared_error score: -0.0794563997231137
Generation:  84%|████████▍ | 21/25 [2:20:39<36:17, 544.30s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465e158a0> 
 Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 751, in fit
    return self._fit(X, y, incremental=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 441, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1621, in _validate_input
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  22
Best root_mean_squared_error score: -0.0794563997231137
Generation:  88%|████████▊ | 22/25 [2:29:32<27:01, 540.65s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465d58760> 

Generation:  23
Best root_mean_squared_error score: -0.0794563997231137
Generation:  92%|█████████▏| 23/25 [2:39:35<18:39, 559.53s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547472feb0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467a6b820> 
 Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 751, in fit
    return self._fit(X, y, incremental=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 441, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1621, in _validate_input
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545173a7a0> 

Generation:  24
Best root_mean_squared_error score: -0.0794563997231137
Generation:  96%|█████████▌| 24/25 [2:49:38<09:32, 572.61s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464c28d30> 
 Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 751, in fit
    return self._fit(X, y, incremental=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 441, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1621, in _validate_input
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155452bc8490> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554659a9780> 

Generation:  25
Best root_mean_squared_error score: -0.0794563997231137
Generation: 100%|██████████| 25/25 [2:59:45<00:00, 582.81s/it]Generation: 100%|██████████| 25/25 [2:59:45<00:00, 431.41s/it]
2024-09-20 07:20:07,447 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:34199' caused the cluster to lose scattered data, which can't be recovered: {'DataFrame-1ed3db9e4f2e3b8130e5039c0283c6a2', 'DataFrame-199f3c31ceebfff04409bf1345a44d8c'} (stimulus_id='handle-worker-cleanup-1726842007.4474077')
Fitted
Pipeline(steps=[('iterativeimputer',
                 IterativeImputer(estimator=BayesianRidge(),
                                  imputation_order='arabic',
                                  initial_strategy='constant',
                                  n_nearest_features=35)),
                ('mlpregressor',
                 MLPRegressor(alpha=7.499565e-07, early_stopping=True,
                              hidden_layer_sizes=[479, 479, 479],
                              learning_rate_init=0.0008949168731,
                              n_iter_no_change=32))])
transform worked
try transform
transform worked
score start
train score: {'explained_var': 0.9603212416069046, 'r2': 0.9602508269110991, 'rmse': 0.052770840414857245}
test score: {'explained_var': 0.9081118448651377, 'r2': 0.90811169516818, 'rmse': 0.07855472216939892}
original test score: {'explained_var': 0.9287614207661228, 'r2': 0.9287610688460114, 'rmse': 0.06916730820990724}
score end
189
lvl
0.01
type
MCAR
num_run
3
reg_full
finished
all finished
full run takes
9.356214074161318
hours
DONE
