Run: 60
/cm/local/apps/slurm/var/spool/job993786/slurm_script: line 26: 
pip install -e tpot2
pip install -r tpot2/ImputerExperiments/requirements_.txt
: No such file or directory
RunStart
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
starting loops
../data/r/23515/23515.pkl
working on 
../data/r/23515/reg_full_MNAR_0.5_3
3.4374496936798096
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2024-10-08 15:22:49,109] A new study created in memory with name: no-name-31cbea0c-56a7-4818-a56f-183287eea93c
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
[I 2024-10-08 15:22:49,475] Trial 1 finished with value: 0.38887001252795184 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 1 with value: 0.38887001252795184.
[I 2024-10-08 15:22:49,482] Trial 6 finished with value: 0.38887001252795184 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 1 with value: 0.38887001252795184.
running
running
[I 2024-10-08 15:22:49,822] Trial 3 finished with value: 0.38887001252795184 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 1 with value: 0.38887001252795184.
running
[I 2024-10-08 15:22:50,064] Trial 11 finished with value: 0.38887001252795184 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 1 with value: 0.38887001252795184.
running
[I 2024-10-08 15:22:50,332] Trial 4 finished with value: 0.38887001252795184 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 1 with value: 0.38887001252795184.
running
[I 2024-10-08 15:22:53,151] Trial 9 finished with value: 0.20578600711973566 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 84, 'weights': 'uniform'}. Best is trial 9 with value: 0.20578600711973566.
running
[I 2024-10-08 15:22:54,712] Trial 18 finished with value: 0.2358270876993558 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5197, 'weights': 'uniform'}. Best is trial 9 with value: 0.20578600711973566.
running
[I 2024-10-08 15:22:54,896] Trial 16 finished with value: 0.2331448983877503 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1936, 'weights': 'uniform'}. Best is trial 9 with value: 0.20578600711973566.
running
[I 2024-10-08 15:22:55,252] Trial 15 finished with value: 0.2358729982231908 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5157, 'weights': 'uniform'}. Best is trial 9 with value: 0.20578600711973566.
running
[I 2024-10-08 15:22:55,846] Trial 14 finished with value: 0.24541232142813457 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4551, 'weights': 'distance'}. Best is trial 9 with value: 0.20578600711973566.
running
[I 2024-10-08 15:22:56,631] Trial 19 finished with value: 0.2453357988186607 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4437, 'weights': 'distance'}. Best is trial 9 with value: 0.20578600711973566.
running
[I 2024-10-08 15:22:57,813] Trial 21 finished with value: 0.23517196752703 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5540, 'weights': 'uniform'}. Best is trial 9 with value: 0.20578600711973566.
running
[I 2024-10-08 15:22:58,023] Trial 17 finished with value: 0.3038289189481545 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 1, 'imputation_order': 'roman', 'sample_posterior': True}. Best is trial 9 with value: 0.20578600711973566.
running
[I 2024-10-08 15:23:00,435] Trial 2 finished with value: 0.18445758575164461 and parameters: {'model_name': 'VAE', 'batch_size': 10, 'iterations': 1, 'learning_rate': 0.0010533440710651812, 'p_miss': 0.13163513551008438}. Best is trial 2 with value: 0.18445758575164461.
running
[I 2024-10-08 15:23:01,775] Trial 20 finished with value: 0.36551829141854697 and parameters: {'model_name': 'GAIN', 'batch_size': 9, 'hint_rate': 0.9841326274301949, 'alpha': 73, 'iterations': 4, 'learning_rate': 0.0329598457600749, 'p_miss': 0.208269980990155}. Best is trial 2 with value: 0.18445758575164461.
running
[I 2024-10-08 15:23:01,934] Trial 29 finished with value: 0.18000251842208803 and parameters: {'model_name': 'VAE', 'batch_size': 10, 'iterations': 1, 'learning_rate': 0.0007589628086984844, 'p_miss': 0.11905947489548926}. Best is trial 29 with value: 0.18000251842208803.
running
[I 2024-10-08 15:23:04,031] Trial 31 finished with value: 0.18505553858262358 and parameters: {'model_name': 'VAE', 'batch_size': 11, 'iterations': 1, 'learning_rate': 0.00043429191469047365, 'p_miss': 0.09419908340201688}. Best is trial 29 with value: 0.18000251842208803.
running
[I 2024-10-08 15:23:06,657] Trial 30 finished with value: 0.18058253156569726 and parameters: {'model_name': 'VAE', 'batch_size': 487, 'iterations': 1, 'learning_rate': 0.0002471002145999877, 'p_miss': 0.030899779491416188}. Best is trial 29 with value: 0.18000251842208803.
running
[I 2024-10-08 15:23:11,730] Trial 10 finished with value: 0.3038557314913577 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 4, 'imputation_order': 'descending', 'sample_posterior': True}. Best is trial 29 with value: 0.18000251842208803.
running
[I 2024-10-08 15:23:19,303] Trial 0 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 11, 'hint_rate': 0.12787894291091467, 'alpha': 90, 'iterations': 78, 'learning_rate': 0.0009748543915895993, 'p_miss': 0.05898648437605279}. Best is trial 29 with value: 0.18000251842208803.
running
[I 2024-10-08 15:24:06,112] Trial 25 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 4, 'hint_rate': 0.7603405151754868, 'alpha': 70, 'iterations': 310, 'learning_rate': 0.026046826054442633, 'p_miss': 0.20516735074861225}. Best is trial 29 with value: 0.18000251842208803.
running
[I 2024-10-08 15:24:13,959] Trial 36 finished with value: 0.17831377978757793 and parameters: {'model_name': 'VAE', 'batch_size': 728, 'iterations': 1, 'learning_rate': 0.0001515161099050999, 'p_miss': 0.12114181173081696}. Best is trial 36 with value: 0.17831377978757793.
running
[I 2024-10-08 15:24:39,827] Trial 22 finished with value: 0.18191158820912218 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 40, 'learning_rate': 0.0017259717897428967, 'p_miss': 0.1245357091031568}. Best is trial 36 with value: 0.17831377978757793.
running
[I 2024-10-08 15:24:55,156] Trial 37 finished with value: 0.19367885169882068 and parameters: {'model_name': 'VAE', 'batch_size': 721, 'iterations': 8, 'learning_rate': 0.0001313274756806382, 'p_miss': 0.038250332790622586}. Best is trial 36 with value: 0.17831377978757793.
running
[I 2024-10-08 15:24:55,380] Trial 28 finished with value: 0.3632863415595171 and parameters: {'model_name': 'GAIN', 'batch_size': 4, 'hint_rate': 0.5649590324499209, 'alpha': 52, 'iterations': 91, 'learning_rate': 0.02585685304665785, 'p_miss': 0.287682654847301}. Best is trial 36 with value: 0.17831377978757793.
running
[I 2024-10-08 15:24:57,220] Trial 38 finished with value: 0.19286103307085747 and parameters: {'model_name': 'VAE', 'batch_size': 453, 'iterations': 4, 'learning_rate': 0.0001602526432543061, 'p_miss': 0.05522072782720956}. Best is trial 36 with value: 0.17831377978757793.
running
[I 2024-10-08 15:24:59,158] Trial 26 finished with value: 0.2493671027222275 and parameters: {'model_name': 'VAE', 'batch_size': 14, 'iterations': 42, 'learning_rate': 0.04399338815703009, 'p_miss': 0.16243470902843282}. Best is trial 36 with value: 0.17831377978757793.
running
[I 2024-10-08 15:25:01,567] Trial 41 finished with value: 0.1826363921500613 and parameters: {'model_name': 'VAE', 'batch_size': 89, 'iterations': 1, 'learning_rate': 0.00034397148750694013, 'p_miss': 0.18413054100694717}. Best is trial 36 with value: 0.17831377978757793.
running
[I 2024-10-08 15:25:02,193] Trial 40 finished with value: 0.17661152831783689 and parameters: {'model_name': 'VAE', 'batch_size': 751, 'iterations': 1, 'learning_rate': 0.00012675344208682834, 'p_miss': 0.026735139496225552}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 15:25:45,339] Trial 23 finished with value: 0.17872557471298212 and parameters: {'model_name': 'VAE', 'batch_size': 793, 'iterations': 29, 'learning_rate': 0.0007932971450008556, 'p_miss': 0.017949343646833028}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 15:26:01,872] Trial 24 finished with value: 0.2426291854558516 and parameters: {'model_name': 'VAE', 'batch_size': 12, 'iterations': 68, 'learning_rate': 0.04401228341827004, 'p_miss': 0.2818149045741233}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 15:41:11,101] Trial 8 finished with value: 0.24050364918771555 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 2, 'imputation_order': 'descending'}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 15:42:41,849] Trial 5 finished with value: 0.22703860831655862 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 3, 'imputation_order': 'descending'}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 15:46:42,574] Trial 12 finished with value: 0.21748203479074082 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 6, 'imputation_order': 'roman'}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 15:47:00,895] Trial 13 finished with value: 0.216696816725583 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 5, 'imputation_order': 'arabic'}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 16:06:41,231] Trial 7 finished with value: 0.20232985531453904 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 742, 'learning_rate': 0.00020573639814137172, 'p_miss': 0.2951148544175464}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 16:07:25,744] Trial 51 finished with value: 0.2077129200594993 and parameters: {'model_name': 'VAE', 'batch_size': 110, 'iterations': 8, 'learning_rate': 0.008587665816502483, 'p_miss': 0.08763594458104082}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 16:07:49,740] Trial 52 finished with value: 0.17788413951869833 and parameters: {'model_name': 'VAE', 'batch_size': 194, 'iterations': 3, 'learning_rate': 0.004421729845287811, 'p_miss': 0.019027334423522963}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 16:31:13,796] Trial 34 finished with value: 0.19349406753455844 and parameters: {'model_name': 'VAE', 'batch_size': 926, 'iterations': 790, 'learning_rate': 0.0001065237492016926, 'p_miss': 0.015076503558452952}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 16:55:04,352] Trial 27 finished with value: 0.23427180261227995 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 1802, 'learning_rate': 0.00017629908642274473, 'p_miss': 0.058125086468765005}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 16:58:04,644] Trial 50 finished with value: 0.20863917965696074 and parameters: {'model_name': 'VAE', 'batch_size': 145, 'iterations': 1157, 'learning_rate': 0.0001155001069901844, 'p_miss': 0.010728552115786633}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 16:58:29,155] Trial 56 finished with value: 0.1774207770163761 and parameters: {'model_name': 'VAE', 'batch_size': 231, 'iterations': 3, 'learning_rate': 0.005164513507850051, 'p_miss': 0.09222998075926482}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 16:58:51,311] Trial 57 finished with value: 0.17687849480465018 and parameters: {'model_name': 'VAE', 'batch_size': 265, 'iterations': 3, 'learning_rate': 0.004697946213812835, 'p_miss': 0.03890724096177914}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 16:59:16,409] Trial 58 finished with value: 0.17748855090350935 and parameters: {'model_name': 'VAE', 'batch_size': 233, 'iterations': 3, 'learning_rate': 0.005187544368801722, 'p_miss': 0.0872985495807088}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 16:59:16,862] Trial 59 finished with value: 0.23318359740516623 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 16:59:45,030] Trial 60 finished with value: 0.1807885251837696 and parameters: {'model_name': 'VAE', 'batch_size': 218, 'iterations': 3, 'learning_rate': 0.0070317672315945694, 'p_miss': 0.0894882838946805}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 17:00:24,654] Trial 61 finished with value: 0.1810845609038107 and parameters: {'model_name': 'VAE', 'batch_size': 47, 'iterations': 10, 'learning_rate': 0.0041474703298320465, 'p_miss': 0.048491884410492854}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 17:00:35,863] Trial 62 finished with value: 0.17849398719830437 and parameters: {'model_name': 'VAE', 'batch_size': 267, 'iterations': 2, 'learning_rate': 0.003542403113928534, 'p_miss': 0.07511998299031744}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 17:00:36,406] Trial 63 finished with value: 0.38290000280283676 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 17:02:00,621] Trial 64 finished with value: 0.24619716399918187 and parameters: {'model_name': 'VAE', 'batch_size': 294, 'iterations': 14, 'learning_rate': 0.010613305492026583, 'p_miss': 0.03511029410490882}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:04:15,476] Trial 32 finished with value: 0.23996996088073233 and parameters: {'model_name': 'VAE', 'batch_size': 53, 'iterations': 3016, 'learning_rate': 0.000819465179731596, 'p_miss': 0.11942896906058045}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:04:31,064] Trial 66 finished with value: 0.17950826016600696 and parameters: {'model_name': 'VAE', 'batch_size': 418, 'iterations': 2, 'learning_rate': 0.0022306376873859252, 'p_miss': 0.07651084182656546}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:04:41,803] Trial 67 finished with value: 0.1807927923639007 and parameters: {'model_name': 'VAE', 'batch_size': 167, 'iterations': 2, 'learning_rate': 0.005534706687287429, 'p_miss': 0.10462036802667167}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:05:24,611] Trial 68 finished with value: 0.21717269170596562 and parameters: {'model_name': 'VAE', 'batch_size': 340, 'iterations': 5, 'learning_rate': 0.013587812024778158, 'p_miss': 0.06487019718457929}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:05:31,160] Trial 69 finished with value: 0.37210472050991195 and parameters: {'model_name': 'GAIN', 'batch_size': 571, 'hint_rate': 0.04272883223675045, 'alpha': 0, 'iterations': 2, 'learning_rate': 0.0028432373515055835, 'p_miss': 0.1460337740210225}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:05:45,061] Trial 70 finished with value: 0.2449236891300039 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'constant', 'n_nearest_features': 1, 'imputation_order': 'ascending'}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:05:54,928] Trial 71 finished with value: 0.1832414493787128 and parameters: {'model_name': 'VAE', 'batch_size': 78, 'iterations': 2, 'learning_rate': 0.0015047996451977423, 'p_miss': 0.032785163705110476}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:07:57,291] Trial 72 finished with value: 0.20901015194992584 and parameters: {'model_name': 'VAE', 'batch_size': 979, 'iterations': 17, 'learning_rate': 0.0055294637222280535, 'p_miss': 0.10074513264444195}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:07:57,760] Trial 73 finished with value: 0.23318359740516623 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:08:18,605] Trial 74 finished with value: 0.1798946528096646 and parameters: {'model_name': 'VAE', 'batch_size': 195, 'iterations': 3, 'learning_rate': 0.004667273589934082, 'p_miss': 0.0704100449367594}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:09:15,332] Trial 75 finished with value: 0.24198410905235765 and parameters: {'model_name': 'VAE', 'batch_size': 314, 'iterations': 5, 'learning_rate': 0.011901728051102596, 'p_miss': 0.1457941123261487}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:09:26,000] Trial 76 finished with value: 0.18395980432727926 and parameters: {'model_name': 'VAE', 'batch_size': 258, 'iterations': 2, 'learning_rate': 0.003170960863372115, 'p_miss': 0.08047542989852527}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:09:37,678] Trial 77 finished with value: 0.18295953037409576 and parameters: {'model_name': 'VAE', 'batch_size': 560, 'iterations': 1, 'learning_rate': 0.0035554982112217777, 'p_miss': 0.04486043351670251}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:09:50,707] Trial 78 finished with value: 0.1796406569055602 and parameters: {'model_name': 'VAE', 'batch_size': 131, 'iterations': 3, 'learning_rate': 0.0022783787882411574, 'p_miss': 0.10583726960336703}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:09:55,320] Trial 79 finished with value: 0.22262595455447523 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'median', 'n_nearest_features': 6, 'imputation_order': 'random'}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:10:39,915] Trial 80 finished with value: 0.1816746029442887 and parameters: {'model_name': 'VAE', 'batch_size': 220, 'iterations': 6, 'learning_rate': 0.006650469851320555, 'p_miss': 0.06593662281205577}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:10:46,425] Trial 81 finished with value: 0.38539448442786106 and parameters: {'model_name': 'GAIN', 'batch_size': 662, 'hint_rate': 0.33247926861873844, 'alpha': 1, 'iterations': 2, 'learning_rate': 0.00138166922828592, 'p_miss': 0.023939291206123137}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:17:58,716] Trial 48 finished with value: 0.2419254217359718 and parameters: {'model_name': 'VAE', 'batch_size': 158, 'iterations': 2282, 'learning_rate': 0.004148136193966144, 'p_miss': 0.013130278319009585}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:18:03,784] Trial 83 finished with value: 0.24586109763084468 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 7604, 'weights': 'distance'}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:20:23,048] Trial 49 finished with value: 0.24064803809144303 and parameters: {'model_name': 'VAE', 'batch_size': 178, 'iterations': 2114, 'learning_rate': 0.004607886169712747, 'p_miss': 0.09670300616748272}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:34:12,414] Trial 43 finished with value: 0.23971296584189422 and parameters: {'model_name': 'VAE', 'batch_size': 167, 'iterations': 2643, 'learning_rate': 0.004897922070741163, 'p_miss': 0.09214891067941007}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:34:53,182] Trial 85 finished with value: 0.24102338255119965 and parameters: {'model_name': 'VAE', 'batch_size': 370, 'iterations': 234, 'learning_rate': 0.01790208844550319, 'p_miss': 0.2527362674808038}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:36:18,619] Trial 86 finished with value: 0.17912495517198457 and parameters: {'model_name': 'VAE', 'batch_size': 417, 'iterations': 26, 'learning_rate': 0.00026721664837264894, 'p_miss': 0.047013728973871356}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:36:28,926] Trial 88 finished with value: 0.17929308020723583 and parameters: {'model_name': 'VAE', 'batch_size': 743, 'iterations': 1, 'learning_rate': 0.0022541424424615533, 'p_miss': 0.026630847440338338}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:37:18,909] Trial 33 finished with value: 0.23812398262410475 and parameters: {'model_name': 'VAE', 'batch_size': 905, 'iterations': 2071, 'learning_rate': 0.00011571597723203114, 'p_miss': 0.01285496339932575}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:38:22,109] Trial 42 finished with value: 0.24163140127517604 and parameters: {'model_name': 'VAE', 'batch_size': 137, 'iterations': 2686, 'learning_rate': 0.00033624911032251816, 'p_miss': 0.022381815739027033}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:43:42,207] Trial 90 finished with value: 0.1796509396688241 and parameters: {'model_name': 'VAE', 'batch_size': 22, 'iterations': 95, 'learning_rate': 0.0005734387340985697, 'p_miss': 0.11818194224514172}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:43:54,303] Trial 89 finished with value: 0.1854170862841295 and parameters: {'model_name': 'VAE', 'batch_size': 23, 'iterations': 111, 'learning_rate': 0.0005336554092121429, 'p_miss': 0.02038719839750113}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:44:02,796] Trial 93 finished with value: 0.2232714679402814 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 4, 'imputation_order': 'random'}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:44:04,342] Trial 92 finished with value: 0.17958375990792358 and parameters: {'model_name': 'VAE', 'batch_size': 276, 'iterations': 3, 'learning_rate': 0.008410500319477961, 'p_miss': 0.06120764712700326}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:44:10,434] Trial 95 finished with value: 0.24586109763084468 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 7882, 'weights': 'distance'}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:44:19,285] Trial 94 finished with value: 0.1778361350064453 and parameters: {'model_name': 'VAE', 'batch_size': 527, 'iterations': 3, 'learning_rate': 0.00016377659486396042, 'p_miss': 0.059208805065064804}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:44:42,722] Trial 97 finished with value: 0.2683883070378837 and parameters: {'model_name': 'VAE', 'batch_size': 566, 'iterations': 4, 'learning_rate': 0.09873617228024002, 'p_miss': 0.05562228097305785}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:44:49,321] Trial 98 finished with value: 0.1773794274863148 and parameters: {'model_name': 'VAE', 'batch_size': 751, 'iterations': 1, 'learning_rate': 0.00015297267448447998, 'p_miss': 0.04207716604464272}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:44:54,604] Trial 99 finished with value: 0.18207451155918822 and parameters: {'model_name': 'VAE', 'batch_size': 491, 'iterations': 1, 'learning_rate': 0.00020918869045196534, 'p_miss': 0.07909437726975005}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:45:14,848] Trial 100 finished with value: 0.1816172171965448 and parameters: {'model_name': 'VAE', 'batch_size': 698, 'iterations': 3, 'learning_rate': 0.00017095803345022338, 'p_miss': 0.04425199370240119}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:45:15,459] Trial 101 finished with value: 0.38290000280283676 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:45:20,751] Trial 102 finished with value: 0.18090189680711108 and parameters: {'model_name': 'VAE', 'batch_size': 359, 'iterations': 1, 'learning_rate': 0.00015847281524240497, 'p_miss': 0.03674720978501704}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:45:21,753] Trial 91 finished with value: 0.24036609790446964 and parameters: {'model_name': 'VAE', 'batch_size': 266, 'iterations': 93, 'learning_rate': 0.008221703839294972, 'p_miss': 0.1341209328657928}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:45:36,513] Trial 104 finished with value: 0.3814208455295186 and parameters: {'model_name': 'GAIN', 'batch_size': 982, 'hint_rate': 0.44483018250336936, 'alpha': 28, 'iterations': 7, 'learning_rate': 0.00020390912015650131, 'p_miss': 0.07300750508747253}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:47:40,599] Trial 96 finished with value: 0.17718306669068346 and parameters: {'model_name': 'VAE', 'batch_size': 529, 'iterations': 34, 'learning_rate': 0.0002321376838096586, 'p_miss': 0.045972914298519414}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:47:51,008] Trial 106 finished with value: 0.18057776834393863 and parameters: {'model_name': 'VAE', 'batch_size': 479, 'iterations': 2, 'learning_rate': 0.00010067813228401499, 'p_miss': 0.0549006259350452}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:48:10,690] Trial 107 finished with value: 0.1793084599220177 and parameters: {'model_name': 'VAE', 'batch_size': 756, 'iterations': 4, 'learning_rate': 0.00013422047604497633, 'p_miss': 0.05177740272805915}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 18:48:24,420] Trial 108 finished with value: 0.17745911754921467 and parameters: {'model_name': 'VAE', 'batch_size': 604, 'iterations': 3, 'learning_rate': 0.0002705193693272008, 'p_miss': 0.038204470265339935}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 19:35:16,681] Trial 44 finished with value: 0.24015206961360408 and parameters: {'model_name': 'VAE', 'batch_size': 79, 'iterations': 4022, 'learning_rate': 0.005591657123389527, 'p_miss': 0.09871812130215323}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 19:36:17,553] Trial 110 finished with value: 0.18085364574687351 and parameters: {'model_name': 'VAE', 'batch_size': 642, 'iterations': 12, 'learning_rate': 0.0002642687640320336, 'p_miss': 0.038975828076898485}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 19:36:42,206] Trial 111 finished with value: 0.19095494515047018 and parameters: {'model_name': 'VAE', 'batch_size': 452, 'iterations': 5, 'learning_rate': 0.00021005280135644836, 'p_miss': 0.033656776878916016}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 19:40:34,463] Trial 112 finished with value: 0.18308758521527368 and parameters: {'model_name': 'VAE', 'batch_size': 840, 'iterations': 41, 'learning_rate': 0.0001417441553393786, 'p_miss': 0.026319847138938632}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 19:41:31,450] Trial 113 finished with value: 0.17989834800555843 and parameters: {'model_name': 'VAE', 'batch_size': 6, 'iterations': 19, 'learning_rate': 0.00012794481035613043, 'p_miss': 0.041712696557756834}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 19:41:51,671] Trial 114 finished with value: 0.18157023767839497 and parameters: {'model_name': 'VAE', 'batch_size': 538, 'iterations': 4, 'learning_rate': 0.0003286139999192753, 'p_miss': 0.018543622584255032}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 19:56:16,856] Trial 115 finished with value: 0.17894717606305915 and parameters: {'model_name': 'VAE', 'batch_size': 2, 'iterations': 269, 'learning_rate': 0.00018447484415030945, 'p_miss': 0.11058406877836023}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 19:56:32,346] Trial 116 finished with value: 0.17718547751378272 and parameters: {'model_name': 'VAE', 'batch_size': 214, 'iterations': 3, 'learning_rate': 0.0036788033286081967, 'p_miss': 0.08553457407646795}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 19:57:22,968] Trial 117 finished with value: 0.19201840795251307 and parameters: {'model_name': 'VAE', 'batch_size': 227, 'iterations': 9, 'learning_rate': 0.006543024402773382, 'p_miss': 0.08492899661170361}. Best is trial 40 with value: 0.17661152831783689.
running
[I 2024-10-08 19:57:40,416] Trial 118 finished with value: 0.17585601394166234 and parameters: {'model_name': 'VAE', 'batch_size': 387, 'iterations': 3, 'learning_rate': 0.002732068971575648, 'p_miss': 0.05900000498211951}. Best is trial 118 with value: 0.17585601394166234.
running
[I 2024-10-08 19:58:11,025] Trial 119 finished with value: 0.174612844692086 and parameters: {'model_name': 'VAE', 'batch_size': 414, 'iterations': 3, 'learning_rate': 0.0037162898703052174, 'p_miss': 0.061954579111708624}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 19:58:48,552] Trial 120 finished with value: 0.176788031576327 and parameters: {'model_name': 'VAE', 'batch_size': 369, 'iterations': 6, 'learning_rate': 0.0003778378139768769, 'p_miss': 0.06311082145731554}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 19:58:54,023] Trial 121 finished with value: 0.24252642467450797 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2378, 'weights': 'distance'}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 19:59:23,666] Trial 122 finished with value: 0.1785924805705057 and parameters: {'model_name': 'VAE', 'batch_size': 388, 'iterations': 6, 'learning_rate': 0.00035845237399505, 'p_miss': 0.06658693472864002}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 19:59:24,045] Trial 123 finished with value: 0.38887001252795184 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 19:59:38,250] Trial 124 finished with value: 0.22635316125342791 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'constant', 'n_nearest_features': 3, 'imputation_order': 'ascending'}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:04:13,298] Trial 125 finished with value: 0.23600118458104902 and parameters: {'model_name': 'VAE', 'batch_size': 321, 'iterations': 57, 'learning_rate': 0.002986905538916459, 'p_miss': 0.060699072030656796}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:04:32,615] Trial 126 finished with value: 0.18211364352448398 and parameters: {'model_name': 'VAE', 'batch_size': 406, 'iterations': 4, 'learning_rate': 0.00024252697767154755, 'p_miss': 0.05203873265346633}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:04:47,846] Trial 127 finished with value: 0.17835754373232854 and parameters: {'model_name': 'VAE', 'batch_size': 622, 'iterations': 3, 'learning_rate': 0.00029665997719141774, 'p_miss': 0.059352731377872704}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:05:18,668] Trial 128 finished with value: 0.17645600972217299 and parameters: {'model_name': 'VAE', 'batch_size': 323, 'iterations': 6, 'learning_rate': 0.000454909431246113, 'p_miss': 0.0686898136864911}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:05:54,801] Trial 129 finished with value: 0.17686605482074974 and parameters: {'model_name': 'VAE', 'batch_size': 324, 'iterations': 6, 'learning_rate': 0.00045786745052492546, 'p_miss': 0.07110459823375981}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:06:39,721] Trial 130 finished with value: 0.1775159220192802 and parameters: {'model_name': 'VAE', 'batch_size': 322, 'iterations': 7, 'learning_rate': 0.0004922701263419727, 'p_miss': 0.04445828002954631}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:07:06,543] Trial 131 finished with value: 0.3801924791276371 and parameters: {'model_name': 'GAIN', 'batch_size': 445, 'hint_rate': 0.9259103337356154, 'alpha': 98, 'iterations': 14, 'learning_rate': 0.0006664571553755281, 'p_miss': 0.07242281215837923}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:07:45,537] Trial 132 finished with value: 0.17624971991083654 and parameters: {'model_name': 'VAE', 'batch_size': 326, 'iterations': 10, 'learning_rate': 0.0009912495940055765, 'p_miss': 0.16910762054649892}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:47:38,497] Trial 54 finished with value: 0.24105164071694576 and parameters: {'model_name': 'VAE', 'batch_size': 208, 'iterations': 4151, 'learning_rate': 0.0037424451603773503, 'p_miss': 0.011694407759320437}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:49:10,389] Trial 134 finished with value: 0.17870941926942055 and parameters: {'model_name': 'VAE', 'batch_size': 281, 'iterations': 24, 'learning_rate': 0.0010507836865263995, 'p_miss': 0.18651411788716704}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:49:51,193] Trial 135 finished with value: 0.17810111409428528 and parameters: {'model_name': 'VAE', 'batch_size': 125, 'iterations': 11, 'learning_rate': 0.0018617024373851088, 'p_miss': 0.16427579251536917}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:50:16,248] Trial 136 finished with value: 0.18274195591576883 and parameters: {'model_name': 'VAE', 'batch_size': 357, 'iterations': 6, 'learning_rate': 0.0003999675789436097, 'p_miss': 0.16843666181119124}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:50:39,841] Trial 137 finished with value: 0.17591503487033544 and parameters: {'model_name': 'VAE', 'batch_size': 188, 'iterations': 5, 'learning_rate': 0.00046711906632129725, 'p_miss': 0.08264076284948858}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:51:19,570] Trial 138 finished with value: 0.17783813557279907 and parameters: {'model_name': 'VAE', 'batch_size': 189, 'iterations': 8, 'learning_rate': 0.0008826034546400089, 'p_miss': 0.08180318132221562}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:51:42,947] Trial 139 finished with value: 0.17688556047340925 and parameters: {'model_name': 'VAE', 'batch_size': 245, 'iterations': 5, 'learning_rate': 0.001158851332987236, 'p_miss': 0.09375307780230505}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:52:01,015] Trial 140 finished with value: 0.18025305325259533 and parameters: {'model_name': 'VAE', 'batch_size': 101, 'iterations': 5, 'learning_rate': 0.0012302369090141745, 'p_miss': 0.06673775502610144}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:52:41,818] Trial 141 finished with value: 0.1815997173483871 and parameters: {'model_name': 'VAE', 'batch_size': 251, 'iterations': 9, 'learning_rate': 0.0006601571210015561, 'p_miss': 0.17285006737273487}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:53:03,895] Trial 142 finished with value: 0.1825755129967716 and parameters: {'model_name': 'VAE', 'batch_size': 317, 'iterations': 4, 'learning_rate': 0.0004375874094103977, 'p_miss': 0.09246469535521255}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 20:53:24,893] Trial 143 finished with value: 0.18171793981378764 and parameters: {'model_name': 'VAE', 'batch_size': 151, 'iterations': 6, 'learning_rate': 0.000632771956467559, 'p_miss': 0.050328879120516916}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 21:08:27,809] Trial 53 finished with value: 0.2409417868324534 and parameters: {'model_name': 'VAE', 'batch_size': 218, 'iterations': 4041, 'learning_rate': 0.003119868429048492, 'p_miss': 0.012256515130072393}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 21:11:03,860] Trial 39 finished with value: 0.24023324236527852 and parameters: {'model_name': 'VAE', 'batch_size': 542, 'iterations': 4690, 'learning_rate': 0.00011764636338973197, 'p_miss': 0.2890693401159607}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 21:11:33,769] Trial 146 finished with value: 0.1807158051159758 and parameters: {'model_name': 'VAE', 'batch_size': 402, 'iterations': 5, 'learning_rate': 0.0038514482627625096, 'p_miss': 0.07732496021991786}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 21:12:05,282] Trial 147 finished with value: 0.17847485189769907 and parameters: {'model_name': 'VAE', 'batch_size': 169, 'iterations': 7, 'learning_rate': 0.0007989410417985106, 'p_miss': 0.08812230656464365}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 21:12:29,328] Trial 148 finished with value: 0.17842503586785724 and parameters: {'model_name': 'VAE', 'batch_size': 241, 'iterations': 4, 'learning_rate': 0.00045939091542648657, 'p_miss': 0.06820174831285941}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 21:29:20,764] Trial 45 finished with value: 0.24084170306596167 and parameters: {'model_name': 'VAE', 'batch_size': 184, 'iterations': 4896, 'learning_rate': 0.009634671810095951, 'p_miss': 0.01678536194769935}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 21:30:58,094] Trial 150 finished with value: 0.17546822674918763 and parameters: {'model_name': 'VAE', 'batch_size': 836, 'iterations': 12, 'learning_rate': 0.0023870899996329014, 'p_miss': 0.028226628794685592}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 21:32:26,192] Trial 151 finished with value: 0.17583465659840763 and parameters: {'model_name': 'VAE', 'batch_size': 769, 'iterations': 13, 'learning_rate': 0.0018461569447262057, 'p_miss': 0.033182488117579324}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 21:34:13,981] Trial 152 finished with value: 0.1784556005850161 and parameters: {'model_name': 'VAE', 'batch_size': 856, 'iterations': 15, 'learning_rate': 0.0026370755958821826, 'p_miss': 0.03120261578760679}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 21:34:17,022] Trial 153 finished with value: 0.21045634675838637 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 240, 'weights': 'uniform'}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 21:36:13,723] Trial 154 finished with value: 0.18000698703529444 and parameters: {'model_name': 'VAE', 'batch_size': 524, 'iterations': 20, 'learning_rate': 0.0017907245952520172, 'p_miss': 0.027693178089642723}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 21:36:32,563] Trial 155 finished with value: 0.22749044458526377 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 2, 'imputation_order': 'arabic', 'sample_posterior': False}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 21:37:46,541] Trial 156 finished with value: 0.17942598799410647 and parameters: {'model_name': 'VAE', 'batch_size': 783, 'iterations': 11, 'learning_rate': 0.002424189825932614, 'p_miss': 0.18701536525039225}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:21:34,735] Trial 65 finished with value: 0.24096234489701135 and parameters: {'model_name': 'VAE', 'batch_size': 43, 'iterations': 5315, 'learning_rate': 0.005328999899255795, 'p_miss': 0.07300342338184403}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:22:01,189] Trial 46 finished with value: 0.24114939750728656 and parameters: {'model_name': 'VAE', 'batch_size': 165, 'iterations': 5528, 'learning_rate': 0.0033240161762002588, 'p_miss': 0.010629572129121696}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:23:16,307] Trial 158 finished with value: 0.17788273872706722 and parameters: {'model_name': 'VAE', 'batch_size': 711, 'iterations': 14, 'learning_rate': 0.002114290883621274, 'p_miss': 0.06199494842064737}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:23:55,520] Trial 160 finished with value: 0.1789891644173721 and parameters: {'model_name': 'VAE', 'batch_size': 476, 'iterations': 8, 'learning_rate': 0.0015675762757391082, 'p_miss': 0.15533577143200192}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:25:28,048] Trial 159 finished with value: 0.17734514483950503 and parameters: {'model_name': 'VAE', 'batch_size': 692, 'iterations': 32, 'learning_rate': 0.0012042841083146462, 'p_miss': 0.04852354731186252}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:28:12,173] Trial 162 finished with value: 0.17955636836329752 and parameters: {'model_name': 'VAE', 'batch_size': 343, 'iterations': 32, 'learning_rate': 0.0013387347594728998, 'p_miss': 0.1764340621683183}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:28:12,995] Trial 163 finished with value: 0.38290000280283676 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:29:10,664] Trial 103 finished with value: 0.38067320282410216 and parameters: {'model_name': 'GAIN', 'batch_size': 993, 'hint_rate': 0.4380708046989925, 'alpha': 22, 'iterations': 7414, 'learning_rate': 0.0001375219420997997, 'p_miss': 0.12949670497234456}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:29:26,765] Trial 164 finished with value: 0.1785353004527483 and parameters: {'model_name': 'VAE', 'batch_size': 612, 'iterations': 10, 'learning_rate': 0.0010021001167120804, 'p_miss': 0.048631848094675655}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:31:53,094] Trial 165 finished with value: 0.18147082938512696 and parameters: {'model_name': 'VAE', 'batch_size': 294, 'iterations': 34, 'learning_rate': 0.0011613136716163873, 'p_miss': 0.048498362691276525}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:34:43,653] Trial 167 finished with value: 0.17618551349883563 and parameters: {'model_name': 'VAE', 'batch_size': 835, 'iterations': 22, 'learning_rate': 0.0009022207652826937, 'p_miss': 0.05632536896089651}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:36:13,717] Trial 168 finished with value: 0.1799134732370986 and parameters: {'model_name': 'VAE', 'batch_size': 415, 'iterations': 20, 'learning_rate': 0.0008804259606683818, 'p_miss': 0.05654003602321744}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:37:50,112] Trial 166 finished with value: 0.2045298799686372 and parameters: {'model_name': 'VAE', 'batch_size': 885, 'iterations': 65, 'learning_rate': 0.001131470008509232, 'p_miss': 0.05632170924092651}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:42:36,400] Trial 170 finished with value: 0.18020468061734451 and parameters: {'model_name': 'VAE', 'batch_size': 669, 'iterations': 43, 'learning_rate': 0.00039741009230636216, 'p_miss': 0.03147484963038554}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:43:18,064] Trial 169 finished with value: 0.2168433300648629 and parameters: {'model_name': 'VAE', 'batch_size': 868, 'iterations': 55, 'learning_rate': 0.0019263856166046626, 'p_miss': 0.03304855862821306}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:45:15,283] Trial 172 finished with value: 0.17723403161123222 and parameters: {'model_name': 'VAE', 'batch_size': 483, 'iterations': 22, 'learning_rate': 0.0005593157446824716, 'p_miss': 0.06880729278782191}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:45:50,169] Trial 171 finished with value: 0.2002730717173792 and parameters: {'model_name': 'VAE', 'batch_size': 493, 'iterations': 26, 'learning_rate': 0.002690305626640929, 'p_miss': 0.07236003096701919}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:47:12,329] Trial 173 finished with value: 0.17857800773539179 and parameters: {'model_name': 'VAE', 'batch_size': 360, 'iterations': 25, 'learning_rate': 0.0005725034059507936, 'p_miss': 0.08089791700475635}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:47:33,232] Trial 174 finished with value: 0.1772799920632413 and parameters: {'model_name': 'VAE', 'batch_size': 385, 'iterations': 17, 'learning_rate': 0.0005611874628796019, 'p_miss': 0.08265151495429887}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:48:21,158] Trial 175 finished with value: 0.18450401172946798 and parameters: {'model_name': 'VAE', 'batch_size': 293, 'iterations': 17, 'learning_rate': 0.0007250413793059053, 'p_miss': 0.22811912984669833}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:48:43,222] Trial 176 finished with value: 0.1791740750516575 and parameters: {'model_name': 'VAE', 'batch_size': 442, 'iterations': 12, 'learning_rate': 0.0005323653651263592, 'p_miss': 0.06414707147297952}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:49:22,087] Trial 177 finished with value: 0.18299053591928316 and parameters: {'model_name': 'VAE', 'batch_size': 203, 'iterations': 12, 'learning_rate': 0.0005122325108737304, 'p_miss': 0.09674465949829789}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:49:50,851] Trial 178 finished with value: 0.18721741350363208 and parameters: {'model_name': 'VAE', 'batch_size': 587, 'iterations': 13, 'learning_rate': 0.0003337517683560545, 'p_miss': 0.07519132949997975}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:51:20,385] Trial 179 finished with value: 0.1854954391066377 and parameters: {'model_name': 'VAE', 'batch_size': 569, 'iterations': 20, 'learning_rate': 0.00037586151837650027, 'p_miss': 0.0858133203899407}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:51:32,869] Trial 180 finished with value: 0.20186289615699357 and parameters: {'model_name': 'VAE', 'batch_size': 263, 'iterations': 17, 'learning_rate': 0.004260782114226119, 'p_miss': 0.08346953883611173}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:52:32,096] Trial 181 finished with value: 0.18076150104027283 and parameters: {'model_name': 'VAE', 'batch_size': 264, 'iterations': 9, 'learning_rate': 0.003287400177672537, 'p_miss': 0.06765684327983765}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:52:34,890] Trial 182 finished with value: 0.17770512771542282 and parameters: {'model_name': 'VAE', 'batch_size': 353, 'iterations': 7, 'learning_rate': 0.0033262992857256896, 'p_miss': 0.06823585109191761}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:53:03,551] Trial 184 finished with value: 0.18215667637503496 and parameters: {'model_name': 'VAE', 'batch_size': 391, 'iterations': 6, 'learning_rate': 0.0007229024944890722, 'p_miss': 0.03964208053967421}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:53:10,063] Trial 183 finished with value: 0.1852874310981522 and parameters: {'model_name': 'VAE', 'batch_size': 379, 'iterations': 7, 'learning_rate': 0.0005916867479509922, 'p_miss': 0.03985841658964196}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:53:11,569] Trial 185 finished with value: 0.24342559743944348 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2850, 'weights': 'distance'}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:56:51,026] Trial 187 finished with value: 0.18608327350987533 and parameters: {'model_name': 'VAE', 'batch_size': 724, 'iterations': 31, 'learning_rate': 0.001543196994685071, 'p_miss': 0.05377853969374868}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:57:05,182] Trial 186 finished with value: 0.18401774184111422 and parameters: {'model_name': 'VAE', 'batch_size': 692, 'iterations': 31, 'learning_rate': 0.0014628409765548875, 'p_miss': 0.022313835603196025}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:57:23,408] Trial 188 finished with value: 0.17914494198211234 and parameters: {'model_name': 'VAE', 'batch_size': 452, 'iterations': 5, 'learning_rate': 0.0004483233831416081, 'p_miss': 0.07670825568500836}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:57:33,144] Trial 189 finished with value: 0.18382667100309436 and parameters: {'model_name': 'VAE', 'batch_size': 438, 'iterations': 5, 'learning_rate': 0.00044592174645286025, 'p_miss': 0.06120831760571101}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:58:20,088] Trial 191 finished with value: 0.3844826933616628 and parameters: {'model_name': 'GAIN', 'batch_size': 313, 'hint_rate': 0.6783769842862137, 'alpha': 42, 'iterations': 24, 'learning_rate': 0.0008319895907929557, 'p_miss': 0.045584860210883565}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 22:58:36,204] Trial 190 finished with value: 0.1774043526372026 and parameters: {'model_name': 'VAE', 'batch_size': 304, 'iterations': 16, 'learning_rate': 0.0007839540513847551, 'p_miss': 0.058280622248207944}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 23:01:15,625] Trial 192 finished with value: 0.17976373245714675 and parameters: {'model_name': 'VAE', 'batch_size': 534, 'iterations': 37, 'learning_rate': 0.0009690148782005076, 'p_miss': 0.052120607545503975}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 23:01:20,107] Trial 194 finished with value: 0.22262575464880646 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'median', 'n_nearest_features': 5, 'imputation_order': 'arabic'}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 23:03:03,224] Trial 193 finished with value: 0.1780115858161339 and parameters: {'model_name': 'VAE', 'batch_size': 813, 'iterations': 39, 'learning_rate': 0.001004709244666704, 'p_miss': 0.05214036559039088}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 23:03:28,941] Trial 196 finished with value: 0.17988234635062642 and parameters: {'model_name': 'VAE', 'batch_size': 766, 'iterations': 4, 'learning_rate': 0.0002971533540452511, 'p_miss': 0.03933187433227968}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 23:03:32,127] Trial 195 finished with value: 0.17925992029722074 and parameters: {'model_name': 'VAE', 'batch_size': 623, 'iterations': 22, 'learning_rate': 0.000306373358716846, 'p_miss': 0.10199870223481108}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 23:04:27,123] Trial 197 finished with value: 0.17808956832478598 and parameters: {'model_name': 'VAE', 'batch_size': 639, 'iterations': 10, 'learning_rate': 0.00023450004003244736, 'p_miss': 0.02548273324993242}. Best is trial 119 with value: 0.174612844692086.
running
[I 2024-10-08 23:04:31,733] Trial 198 finished with value: 0.17866081460965777 and parameters: {'model_name': 'VAE', 'batch_size': 234, 'iterations': 10, 'learning_rate': 0.0012622402390903861, 'p_miss': 0.044253828104779125}. Best is trial 119 with value: 0.174612844692086.
[I 2024-10-08 23:07:53,395] Trial 199 finished with value: 0.17792312649716627 and parameters: {'model_name': 'VAE', 'batch_size': 886, 'iterations': 46, 'learning_rate': 0.00011610952644041026, 'p_miss': 0.044085457499526526}. Best is trial 119 with value: 0.174612844692086.
[I 2024-10-08 23:58:41,597] Trial 109 finished with value: 0.24067003911044588 and parameters: {'model_name': 'VAE', 'batch_size': 615, 'iterations': 4319, 'learning_rate': 0.00026834121695005987, 'p_miss': 0.03981007847262119}. Best is trial 119 with value: 0.174612844692086.
[I 2024-10-09 00:37:40,880] Trial 47 finished with value: 0.24131468444246776 and parameters: {'model_name': 'VAE', 'batch_size': 152, 'iterations': 6822, 'learning_rate': 0.005061119752635042, 'p_miss': 0.011820755519877723}. Best is trial 119 with value: 0.174612844692086.
[I 2024-10-09 01:21:24,405] Trial 82 finished with value: 0.24099036384583136 and parameters: {'model_name': 'VAE', 'batch_size': 393, 'iterations': 8120, 'learning_rate': 0.019701025223705655, 'p_miss': 0.05000523877887756}. Best is trial 119 with value: 0.174612844692086.
[I 2024-10-09 01:53:08,607] Trial 55 finished with value: 0.24139504694884262 and parameters: {'model_name': 'VAE', 'batch_size': 199, 'iterations': 8619, 'learning_rate': 0.0032938890829943995, 'p_miss': 0.014011150241120608}. Best is trial 119 with value: 0.174612844692086.
[I 2024-10-09 02:37:24,580] Trial 105 finished with value: 0.2401734458719008 and parameters: {'model_name': 'VAE', 'batch_size': 487, 'iterations': 6739, 'learning_rate': 0.0001390751923449652, 'p_miss': 0.05521378567084407}. Best is trial 119 with value: 0.174612844692086.
[I 2024-10-09 02:55:22,480] Trial 35 finished with value: 0.23990613287928206 and parameters: {'model_name': 'VAE', 'batch_size': 843, 'iterations': 9849, 'learning_rate': 0.00010614549768894093, 'p_miss': 0.015904034412386275}. Best is trial 119 with value: 0.174612844692086.
[I 2024-10-09 03:04:20,126] Trial 133 finished with value: 0.2407562977510776 and parameters: {'model_name': 'VAE', 'batch_size': 107, 'iterations': 7147, 'learning_rate': 0.0009654383077378106, 'p_miss': 0.18612085990988203}. Best is trial 119 with value: 0.174612844692086.
[I 2024-10-09 03:14:46,693] Trial 84 finished with value: 0.24047945116854544 and parameters: {'model_name': 'VAE', 'batch_size': 368, 'iterations': 9912, 'learning_rate': 0.016784441938747906, 'p_miss': 0.05112341208403643}. Best is trial 119 with value: 0.174612844692086.
[I 2024-10-09 03:40:59,169] Trial 87 finished with value: 0.24009615312394805 and parameters: {'model_name': 'VAE', 'batch_size': 739, 'iterations': 8187, 'learning_rate': 0.0005758076229253866, 'p_miss': 0.04928603422107675}. Best is trial 119 with value: 0.174612844692086.
[I 2024-10-09 03:43:47,562] Trial 145 finished with value: 0.24048108444972321 and parameters: {'model_name': 'VAE', 'batch_size': 383, 'iterations': 8533, 'learning_rate': 0.0007896947842544628, 'p_miss': 0.06988856646072214}. Best is trial 119 with value: 0.174612844692086.
[I 2024-10-09 03:47:06,510] Trial 157 finished with value: 0.24074651785574516 and parameters: {'model_name': 'VAE', 'batch_size': 653, 'iterations': 8511, 'learning_rate': 0.00151681876076836, 'p_miss': 0.04821516640595699}. Best is trial 119 with value: 0.174612844692086.
[I 2024-10-09 04:04:54,840] Trial 144 finished with value: 0.2398104981738987 and parameters: {'model_name': 'VAE', 'batch_size': 827, 'iterations': 8593, 'learning_rate': 0.0025930651615286714, 'p_miss': 0.19462212277382301}. Best is trial 119 with value: 0.174612844692086.
[I 2024-10-09 04:04:59,249] Trial 149 finished with value: 0.24018558250409203 and parameters: {'model_name': 'VAE', 'batch_size': 816, 'iterations': 8064, 'learning_rate': 0.0003753810796083416, 'p_miss': 0.18890116946454674}. Best is trial 119 with value: 0.174612844692086.
[I 2024-10-09 04:09:33,535] Trial 161 finished with value: 0.23983523424928882 and parameters: {'model_name': 'VAE', 'batch_size': 895, 'iterations': 8595, 'learning_rate': 0.001200293323025096, 'p_miss': 0.041342329895173106}. Best is trial 119 with value: 0.174612844692086.
fit
auto fit
auto transform
0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64
0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64
0.174612844692086
{'model_name': 'VAE', 'batch_size': 414, 'iterations': 3, 'learning_rate': 0.0037162898703052174, 'p_miss': 0.061954579111708624}
running experiment 2/3 - Does reconstruction give good automl predictions
Start est fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a5030> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  1
Best root_mean_squared_error score: -0.052780779725782656
Generation:   4%|▍         | 1/25 [00:15<06:01, 15.08s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547472f520> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547470bcd0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a7190> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4a30> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  2
Best root_mean_squared_error score: -0.052780779725782656
Generation:   8%|▊         | 2/25 [01:30<19:27, 50.78s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f01330> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a67d0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  3
Best root_mean_squared_error score: -0.052780779725782656
Generation:  12%|█▏        | 3/25 [02:15<17:30, 47.76s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a6e90> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547470b130> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  4
Best root_mean_squared_error score: -0.052780779725782656
Generation:  16%|█▌        | 4/25 [02:24<11:29, 32.84s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a72b0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  5
Best root_mean_squared_error score: -0.052780779725782656
Generation:  20%|██        | 5/25 [02:32<07:53, 23.69s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547472e3e0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  6
Best root_mean_squared_error score: -0.052780620670779634
Generation:  24%|██▍       | 6/25 [02:45<06:19, 19.95s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554659264d0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  7
Best root_mean_squared_error score: -0.052780620670779634
Generation:  28%|██▊       | 7/25 [03:00<05:30, 18.38s/it]Generation:  8
Best root_mean_squared_error score: -0.052780620670779634
Generation:  32%|███▏      | 8/25 [03:15<04:55, 17.35s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547470b5e0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  9
Best root_mean_squared_error score: -0.052780620670779634
Generation:  36%|███▌      | 9/25 [04:05<07:20, 27.51s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467c64130> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467e03f10> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  10
Best root_mean_squared_error score: -0.052780620670779634
Generation:  40%|████      | 10/25 [04:20<05:54, 23.64s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554747089d0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  11
Best root_mean_squared_error score: -0.052780620670779634
Generation:  44%|████▍     | 11/25 [04:53<06:12, 26.63s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547472eb00> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  12
Best root_mean_squared_error score: -0.052780620670779634
Generation:  48%|████▊     | 12/25 [06:20<09:42, 44.81s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465762830> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  13
Best root_mean_squared_error score: -0.052780620670779634
Generation:  52%|█████▏    | 13/25 [06:40<07:28, 37.37s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465b6f5b0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  14
Best root_mean_squared_error score: -0.052780620670779634
Generation:  56%|█████▌    | 14/25 [07:11<06:31, 35.55s/it]Generation:  15
Best root_mean_squared_error score: -0.052780620670779634
Generation:  60%|██████    | 15/25 [07:39<05:32, 33.28s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f03eb0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  16
Best root_mean_squared_error score: -0.052777905861913374
Generation:  64%|██████▍   | 16/25 [08:22<05:25, 36.13s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465b56470> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  17
Best root_mean_squared_error score: -0.052777905861913374
Generation:  68%|██████▊   | 17/25 [10:01<07:21, 55.15s/it]Generation:  18
Best root_mean_squared_error score: -0.052777905861913374
Generation:  72%|███████▏  | 18/25 [10:32<05:34, 47.77s/it]Generation:  19
Best root_mean_squared_error score: -0.052777905861913374
Generation:  76%|███████▌  | 19/25 [11:15<04:38, 46.46s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746efbb0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  20
Best root_mean_squared_error score: -0.052777905861913374
Generation:  80%|████████  | 20/25 [11:59<03:47, 45.60s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465749c60> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546567ebc0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  21
Best root_mean_squared_error score: -0.052777905861913374
Generation:  84%|████████▍ | 21/25 [12:35<02:51, 42.89s/it]Generation:  22
Best root_mean_squared_error score: -0.052777905861913374
Generation:  88%|████████▊ | 22/25 [13:03<01:55, 38.41s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a6d40> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467cf3760> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  23
Best root_mean_squared_error score: -0.052777905861913374
Generation:  92%|█████████▏| 23/25 [13:32<01:10, 35.38s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746ef070> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464d1bc10> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465ac8a00> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  24
Best root_mean_squared_error score: -0.052777905861913374
Generation:  96%|█████████▌| 24/25 [14:21<00:39, 39.41s/it]Generation:  25
Best root_mean_squared_error score: -0.052777905861913374
Generation: 100%|██████████| 25/25 [14:47<00:00, 35.61s/it]Generation: 100%|██████████| 25/25 [14:56<00:00, 35.86s/it]
2024-10-09 04:24:41,255 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:37483' caused the cluster to lose scattered data, which can't be recovered: {'DataFrame-9f575405dd824ee444b27dd6207c87af', 'ndarray-92cb275fb854a6c3ca61d53ff1cef383'} (stimulus_id='handle-worker-cleanup-1728473081.2554102')
Fitted
Pipeline(steps=[('histgradientboostingregressor',
                 HistGradientBoostingRegressor(early_stopping=True,
                                               l2_regularization=3.56679927e-05,
                                               learning_rate=0.0021582756671,
                                               max_features=0.1729685331757,
                                               max_leaf_nodes=895,
                                               min_samples_leaf=16,
                                               n_iter_no_change=15, tol=0.0001,
                                               validation_fraction=0.3403761406619))])
score start
train score: {'explained_var': 0.0050226311148428016, 'r2': 0.005021732514195909, 'rmse': 0.052755940095691754}
original test score: {'explained_var': 0.0015420096634967129, 'r2': 0.0015419842422385033, 'rmse': 0.05332757268346694}
imputed test score: {'explained_var': 1.512738488285148e-05, 'r2': 1.0600201219679306e-05, 'rmse': 0.05336845257178174}
score end
check intended
EXP2 Finished
running experiment 3/3 - What is the best automl settings?
<tpot2.search_spaces.pipelines.sequential.SequentialPipeline object at 0x1554081b31f0>
Start tpot fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474cd4730> 
 Input X contains NaN.
KNeighborsRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 31, in cross_val_score_objective
    this_fold_scores = [sklearn.metrics.get_scorer(scorer)(this_fold_pipeline, X_test, y_test) for scorer in scorers]
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 31, in <listcomp>
    this_fold_scores = [sklearn.metrics.get_scorer(scorer)(this_fold_pipeline, X_test, y_test) for scorer in scorers]
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 279, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 371, in _score
    y_pred = method_caller(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 239, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 601, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neighbors/_regression.py", line 242, in predict
    neigh_ind = self.kneighbors(X, return_distance=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neighbors/_base.py", line 825, in kneighbors
    X = self._validate_data(X, accept_sparse="csr", reset=False, order="C")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 633, in _validate_data
    out = check_array(X, input_name="X", **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
KNeighborsRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474cd4af0> 
 Input X contains NaN.
ARDRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 31, in cross_val_score_objective
    this_fold_scores = [sklearn.metrics.get_scorer(scorer)(this_fold_pipeline, X_test, y_test) for scorer in scorers]
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 31, in <listcomp>
    this_fold_scores = [sklearn.metrics.get_scorer(scorer)(this_fold_pipeline, X_test, y_test) for scorer in scorers]
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 279, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 371, in _score
    y_pred = method_caller(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 239, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 601, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/linear_model/_bayes.py", line 783, in predict
    y_mean = self._decision_function(X)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/linear_model/_base.py", line 285, in _decision_function
    X = self._validate_data(X, accept_sparse=["csr", "csc", "coo"], reset=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 633, in _validate_data
    out = check_array(X, input_name="X", **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
ARDRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  1
Best root_mean_squared_error score: -0.041392377713393345
Generation:   4%|▍         | 1/25 [10:00<4:00:03, 600.15s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474cd7790> 
 Input X contains NaN.
LinearSVR does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 31, in cross_val_score_objective
    this_fold_scores = [sklearn.metrics.get_scorer(scorer)(this_fold_pipeline, X_test, y_test) for scorer in scorers]
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 31, in <listcomp>
    this_fold_scores = [sklearn.metrics.get_scorer(scorer)(this_fold_pipeline, X_test, y_test) for scorer in scorers]
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 279, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 371, in _score
    y_pred = method_caller(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 239, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 601, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/linear_model/_base.py", line 306, in predict
    return self._decision_function(X)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/linear_model/_base.py", line 285, in _decision_function
    X = self._validate_data(X, accept_sparse=["csr", "csc", "coo"], reset=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 633, in _validate_data
    out = check_array(X, input_name="X", **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
LinearSVR does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474584f70> 
 Input X contains NaN.
LinearSVR does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/svm/_classes.py", line 569, in fit
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
LinearSVR does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  2
Best root_mean_squared_error score: -0.041392377713393345
Generation:   8%|▊         | 2/25 [13:27<2:21:34, 369.31s/it]Generation:  3
Best root_mean_squared_error score: -0.041392377713393345
Generation:  12%|█▏        | 3/25 [18:22<2:02:52, 335.12s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545711fa90> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d4d030> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  4
Best root_mean_squared_error score: -0.041392377713393345
Generation:  16%|█▌        | 4/25 [26:04<2:14:48, 385.19s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d14cd0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554571839d0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155403dbc220> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d70730> 
 Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 31, in cross_val_score_objective
    this_fold_scores = [sklearn.metrics.get_scorer(scorer)(this_fold_pipeline, X_test, y_test) for scorer in scorers]
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 31, in <listcomp>
    this_fold_scores = [sklearn.metrics.get_scorer(scorer)(this_fold_pipeline, X_test, y_test) for scorer in scorers]
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 279, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 371, in _score
    y_pred = method_caller(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 239, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 601, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1605, in predict
    return self._predict(X)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1609, in _predict
    y_pred = self._forward_pass_fast(X, check_input=check_input)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 206, in _forward_pass_fast
    X = self._validate_data(X, accept_sparse=["csr", "csc"], reset=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 633, in _validate_data
    out = check_array(X, input_name="X", **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  5
Best root_mean_squared_error score: -0.04060677281751762
Generation:  20%|██        | 5/25 [33:44<2:17:22, 412.14s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547458e560> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  6
Best root_mean_squared_error score: -0.04025023342473779
Generation:  24%|██▍       | 6/25 [41:25<2:15:49, 428.92s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d17ca0> 
 Input X contains NaN.
ExtraTreesRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 31, in cross_val_score_objective
    this_fold_scores = [sklearn.metrics.get_scorer(scorer)(this_fold_pipeline, X_test, y_test) for scorer in scorers]
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 31, in <listcomp>
    this_fold_scores = [sklearn.metrics.get_scorer(scorer)(this_fold_pipeline, X_test, y_test) for scorer in scorers]
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 279, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 371, in _score
    y_pred = method_caller(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 239, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 601, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/ensemble/_forest.py", line 1063, in predict
    X = self._validate_X_predict(X)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/ensemble/_forest.py", line 641, in _validate_X_predict
    X = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 633, in _validate_data
    out = check_array(X, input_name="X", **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
ExtraTreesRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  7
Best root_mean_squared_error score: -0.04025023342473779
Generation:  28%|██▊       | 7/25 [49:05<2:11:44, 439.12s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545711e590> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545ddec040> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d6eb30> 
 Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 31, in cross_val_score_objective
    this_fold_scores = [sklearn.metrics.get_scorer(scorer)(this_fold_pipeline, X_test, y_test) for scorer in scorers]
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 31, in <listcomp>
    this_fold_scores = [sklearn.metrics.get_scorer(scorer)(this_fold_pipeline, X_test, y_test) for scorer in scorers]
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 279, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 371, in _score
    y_pred = method_caller(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 239, in _get_response_values
    y_pred, pos_label = prediction_method(X), None
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 601, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1605, in predict
    return self._predict(X)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1609, in _predict
    y_pred = self._forward_pass_fast(X, check_input=check_input)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 206, in _forward_pass_fast
    X = self._validate_data(X, accept_sparse=["csr", "csc"], reset=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 633, in _validate_data
    out = check_array(X, input_name="X", **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  8
Best root_mean_squared_error score: -0.04025023342473779
Generation:  32%|███▏      | 8/25 [56:49<2:06:37, 446.94s/it]Generation:  9
Best root_mean_squared_error score: -0.04006062190120545
Generation:  36%|███▌      | 9/25 [1:04:31<2:00:26, 451.63s/it]Generation:  10
Best root_mean_squared_error score: -0.04006062190120545
Generation:  40%|████      | 10/25 [1:12:22<1:54:25, 457.72s/it]Generation:  11
Best root_mean_squared_error score: -0.039634987027288904
Generation:  44%|████▍     | 11/25 [1:20:12<1:47:38, 461.34s/it]Generation:  12
Best root_mean_squared_error score: -0.039634987027288904
Generation:  48%|████▊     | 12/25 [1:29:31<1:46:26, 491.24s/it]Generation:  13
Best root_mean_squared_error score: -0.039634987027288904
Generation:  52%|█████▏    | 13/25 [1:37:25<1:37:09, 485.78s/it]Generation:  14
Best root_mean_squared_error score: -0.039634987027288904
Generation:  56%|█████▌    | 14/25 [1:45:20<1:28:27, 482.49s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545f8b9cc0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  15
Best root_mean_squared_error score: -0.039634987027288904
Generation:  60%|██████    | 15/25 [1:53:06<1:19:35, 477.55s/it]Generation:  16
Best root_mean_squared_error score: -0.039634987027288904
Generation:  64%|██████▍   | 16/25 [2:00:49<1:10:59, 473.30s/it]Generation:  17
Best root_mean_squared_error score: -0.039634987027288904
Generation:  68%|██████▊   | 17/25 [2:08:29<1:02:33, 469.15s/it]Generation:  18
Best root_mean_squared_error score: -0.039634987027288904
Generation:  72%|███████▏  | 18/25 [2:16:04<54:14, 464.97s/it]  WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545fe92170> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  19
Best root_mean_squared_error score: -0.039634987027288904
Generation:  76%|███████▌  | 19/25 [2:23:48<46:28, 464.76s/it]Generation:  20
Best root_mean_squared_error score: -0.039634987027288904
Generation:  80%|████████  | 20/25 [2:31:27<38:34, 462.95s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155456cc63e0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  21
Best root_mean_squared_error score: -0.039634987027288904
Generation:  84%|████████▍ | 21/25 [2:39:06<30:46, 461.71s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545fefde70> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  22
Best root_mean_squared_error score: -0.039634987027288904
Generation:  88%|████████▊ | 22/25 [2:46:44<23:02, 460.72s/it]Generation:  23
Best root_mean_squared_error score: -0.039634987027288904
Generation:  92%|█████████▏| 23/25 [2:54:26<15:22, 461.12s/it]Generation:  24
Best root_mean_squared_error score: -0.039634987027288904
Generation:  96%|█████████▌| 24/25 [3:02:09<07:41, 461.72s/it]Generation:  25
Best root_mean_squared_error score: -0.039634987027288904
Generation: 100%|██████████| 25/25 [3:09:47<00:00, 460.57s/it]Generation: 100%|██████████| 25/25 [3:09:47<00:00, 455.50s/it]
2024-10-09 07:36:32,978 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:37751' caused the cluster to lose scattered data, which can't be recovered: {'DataFrame-080ce934b85b3787e47c0dc7d682bfb6', 'DataFrame-9f575405dd824ee444b27dd6207c87af'} (stimulus_id='handle-worker-cleanup-1728484592.978505')
Fitted
Pipeline(steps=[('iterativeimputer',
                 IterativeImputer(estimator=RandomForestRegressor(),
                                  imputation_order='descending',
                                  n_nearest_features=67)),
                ('lgbmregressor',
                 LGBMRegressor(max_depth=4, n_estimators=78, n_jobs=1,
                               num_leaves=39, verbose=-1))])
transform worked
try transform
transform worked
score start
train score: {'explained_var': 0.549305407861614, 'r2': 0.549305407861614, 'rmse': 0.03550632651438647}
test score: {'explained_var': 0.3117821395506495, 'r2': 0.31036012721581874, 'rmse': 0.044319830817540484}
original test score: {'explained_var': 0.6192078070919591, 'r2': 0.6175654194833662, 'rmse': 0.033003917279886885}
score end
23515
lvl
0.5
type
MNAR
num_run
3
reg_full
finished
all finished
full run takes
16.415652410520448
hours
DONE
